### ISSUE TITLE
Please give us the option to change background on "Radio"

### ISSUE THREAD

**Issue by jasonatfreecast** [Xtraball/SiberianCMS#1]
![screenshot_7](https://cloud.githubusercontent.com/assets/8884686/15361724/b38b2336-1ce0-11e6-8630-818366d2d7f0.jpg)

**Comment by thehosting4you** [comment]
Perhaps another option to display the stream information and stream title.

**Comment by Mabudigital** [comment]
That would be great

**Comment by rogeroffer** [comment]
Change style.css 

Add this to the stylesheet in the section audio player. See screenshot. Upload file to the server (/var/apps/ionic/android/assets/www/css)

.audio-player .cover {position: absolute; top:0; bottom:0; left:0; right:0; height:100%; background:url("file:///android_res/drawable/screen.png") no-repeat center #000!important;background-size: contain!important;}

![screen shot 2016-08-27 at 12 22 42](https://cloud.githubusercontent.com/assets/2719620/18026487/2d7d0b0e-6c51-11e6-8ddd-de560ff6c655.png)

**Comment by alexyves** [comment]
Will be released soon

![1-radio-background](https://cloud.githubusercontent.com/assets/18324386/18406113/113ff570-76f9-11e6-86fb-2df5dfa6cbe5.png)
