### ISSUE TITLE
Duplicate Titles In RSS Feed

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#101]
The RSS feed unnecessarily contains duplicate Titles.  

I'm assuming that the 2nd title is a duplicate of the first because the feed post didn't posses a sub-title.  If this is the case, instead of duplicating the Title (which doesn't look good), it could be coded to leave the field null, or to include some verbiage from the post.  Again, I'm speculating as to why it's happening so I could be completely off-base... However, the feed would look more professional if the Title wasn't duplicated.

See attached image.

![rss_title_displayed_twice](https://cloud.githubusercontent.com/assets/21089972/20688784/4c20c2f2-b590-11e6-96cf-4f9e408e42bf.png)

**Comment by dbyzero** [comment]
Hi,

Sorry for the delay. Can you give us your RSS feed ? We need to be sure that our commit fixes the issue.

**Comment by Alboorii** [comment]
Helli @dbyzero,

I've the same issue, Check the screenshot.
![screen shot 2017-01-02 at 6 59 21 pm](https://cloud.githubusercontent.com/assets/13621788/21592340/99bc1888-d11d-11e6-943f-bc917b43243f.png)

Rss link:
http://lap.weappz.com/democontent/feed

**Comment by clifton11221** [comment]
Here's another one:

http://urbanareas.net/info/feed/

**Comment by dbyzero** [comment]
Fixed in 4.8.12
