### ISSUE TITLE
Offline mode not working

### ISSUE THREAD

**Issue by arbindbhagat** [Xtraball/SiberianCMS#104]
The offline mode is not working even after downloading the offline content during the app launch. When we are offline and then re-launch the app, the app just won't launch the first page, which is "custom" page.

**Comment by grafixpress** [comment]
For me with offline content enabled the first download hangs at 0% for hours both on Android and IOS. This is not server related - I have changed the server twice.

**Comment by PofMagicfingers** [comment]
Offline mode has been rewritten almost from scratch, new version will be available in a future release coming soon

**Comment by grafixpress** [comment]
That sounds really good! Thanx

Grafixpress email

Thomas F. Reich


Grafixpress Web & App Developements
+34 663 823 697 | SKYPE grafixpress

Grafixpress.de <http://www.grafixpress.de/>
DeinApp.de <http://www.deinapp.de/>

------------------------------------------------------------------------
Am 23.01.2017 um 17:57 schrieb Pof Magicfingers:

**Comment by Gibasam** [comment]
I am also having problem in the offline module. I opened a ticket but got no answer. In the facebook group Anders told me that a new release will soon be coming out fixing this problem. But do you have a date for this release?

**Comment by dbyzero** [comment]
It's currently in test process, it will be available on beta release at end or next week.

**Comment by SiberianCMS** [comment]
Available in beta in 4.8.11-beta.4
