### ISSUE TITLE
Feature Subtitle translation

### ISSUE THREAD

**Issue by Alboorii** [Xtraball/SiberianCMS#105]
I am trying to translate feature Subtitle string. I add it in default.csv but its not getting translated.

**Comment by dbyzero** [comment]
Looks like a missing translation. I add it to bug tracker, will be soon fixed.

**Comment by dbyzero** [comment]
Fixed, will be in next release.

**Comment by dbyzero** [comment]
Add your translation to application.csv and not default.csv.
