### ISSUE TITLE
Can't install SiberianCMS 4.7.12

### ISSUE THREAD

**Issue by sshcli** [Xtraball/SiberianCMS#106]
**The error:**
I Can't install SiberianCMS 4.7.12
The installation doesn't complete, It always stop in the part where says "Ending Installation..."
With the following error in the console:
Failed to load resource: the server responded with a status of 504 (Gateway Time-out)

![ending](https://cloud.githubusercontent.com/assets/12942731/21156625/e653cb9a-c14c-11e6-98ac-dfaae8802688.PNG)

![console](https://cloud.githubusercontent.com/assets/12942731/21156831/ac226002-c14d-11e6-98d3-76fd4bc6c6b4.PNG)

Tested with:
PHP 5.6.24 + MySQL 5.6.34 + Cpanel (Shared hosting)

**Comment by sshcli** [comment]
If I try to reload the page, I will get the login page
Seems good, but is not, because In this case I don't have an account
![login](https://cloud.githubusercontent.com/assets/12942731/21157421/9c9ea828-c14f-11e6-9d79-82e1a41d7853.PNG)

**Comment by sshcli** [comment]
Is there a difference in the package downloaded via your official website and the one hosted here on GitHub?

**Comment by dbyzero** [comment]
Hi,

I update package to last version (4.7.17). Try with it, we fix possibly on Cron install for some server.

Anyway if you still stuck, please contact contact@siberiancms.com.

I close ticket because it's not related to reproducible bugs.

**Comment by sshcli** [comment]
> I update package to last version (4.7.17). Try with it, we fix possibly on Cron install for some server.

I will test it today and I'll let you know the results 



> I close ticket because it's not related to reproducible bugs.

Ok, no problem, I understand.

**Comment by sshcli** [comment]
Sorry,
I've been trying to install it on 2 different servers with 2 different methods (Github package and single index.php from official website)
I Couldn't make it.

Thanks anyway for your help

**Comment by sshcli** [comment]
Just for the records,
I was trying in a top level domain, not subdomain
Also, I tried both (With / without .htaccess)

**Comment by dbyzero** [comment]
May be you miss a dependencies or a configuration. Please contact contact@siberiancms.com and post here what was your issue, we will try to avoid it for future users.

**Comment by sshcli** [comment]
Ok,
I have installed siberian on my VPS with success.

The documentation for installation process needs to be modified, maybe source code too:

1. On CPanel environment, If you want to install it by only downloading the index.php from the official website, you also need to download and rename the htaccess file included here in the source code, otherwise you will get a 500 Internal server error.
2. Also need to modify the source code and include an error message for those people who has allow_url_fopen disabled 

Regards
