### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by Alboorii** [Xtraball/SiberianCMS#107]
Hello team,

Here is some of missing translations i found:

1. Your application in few numbers
2. Feature Top 5 visits
3. AVERAGE CART
4. My Users List
5. Create / Edit a User
6. CREATE A NEW USER
7. This user can access the pages locked by the "Locker" feature
8. Promote your app!
9. Advanced options
10. Customize your app's colors

**Comment by dbyzero** [comment]
Thanks.

**Comment by Alboorii** [comment]
New Missing Translate:

YOUR DESIGN
LAYOUT OPTIONS
Use background into all of your application's pages
Add a picture ( Its in default.csv but its not working )

**Comment by SiberianCMS** [comment]
@Alboorii are you sure of that, see pictures below, please confirm ...

the translations are in "application.csv"

![capture d ecran 2017-01-06 a 11 36 54](https://cloud.githubusercontent.com/assets/7977082/21715394/80a4586c-d404-11e6-95ed-0ae69b7b6db7.png)
![capture d ecran 2017-01-06 a 11 37 00](https://cloud.githubusercontent.com/assets/7977082/21715395/80a4ecd2-d404-11e6-957b-5a689ae88486.png)

**Comment by Alboorii** [comment]
Hello,

Sorry for that, I've double check now.

YOUR DESIGN - OK
LAYOUT OPTIONS - OK
Use background into all of your application's pages - Still i didn't find it

**Comment by rivman** [comment]
Hello,
Also don't find the string "Use background into all of your application's pages" in applications.csv (using fresh download from Market for French translation). Atached screenshot:

![capture](https://cloud.githubusercontent.com/assets/11364533/21933078/2588d3cc-d9a4-11e6-9bfd-e43e6b5e25b5.PNG)
