### ISSUE TITLE
Wordpress Plugin

### ISSUE THREAD

**Issue by Alboorii** [Xtraball/SiberianCMS#109]
Hello

When trying to active wordpress plugin, Its say:
Plugin could not be activated because it triggered a fatal error.

Wordpress Version: 4.7

Best regards

**Comment by AvinashPanchal** [comment]
Hi 	Alboorii,
The error is caused by the use of an anonymous function, which only became available as of version 5.3.0. 
upgrade your PHP version.

Thanks

**Comment by Alboorii** [comment]
@AvinashPanchal Even with 7.0 its give an error:

The plugin generated 260 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

**Comment by fouineux** [comment]
Hello,

We didn't manage to reproduce this bug, it might be an issue specific to your wordpress.
