### ISSUE TITLE
WordPress / RSS Module Doesn't Properly Separate Text Paragraphs

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#110]
The WordPress and RSS modules doesn't properly separate the various paragraphs of texts when it's displayed in the app. 

For example, if the article has separate paragraphs, upon being displayed in the app, the paragraph breaks are removed and it looks like one big blob of text.  It's even worse if the article is long and contains multiple paragraphs of text.

See the attached images.

**PROPERLY FORMATTED ON WEBSITE**

![paragraph_bug_01](https://cloud.githubusercontent.com/assets/21089972/21443500/ef0bd3f8-c873-11e6-9b56-a3871f200b98.PNG)

**IMPROPERLY FORMATTED ON APP**

![paragraph_bug_02](https://cloud.githubusercontent.com/assets/21089972/21443632/daed01c0-c874-11e6-90d6-0b0f20b4b77d.PNG)

**Comment by dbyzero** [comment]
Thanks, we will fix it asap.

**Comment by rivman** [comment]
The possibility to have some unique CSS classes or ID's for customize the text / titles is a must for a better user experience. 
Thank you.

**Comment by PofMagicfingers** [comment]
You can already customize it through custom CSS/SCSS : 

```css
.item-description p {
    margin-top: 10px;
}
```
