### ISSUE TITLE
MAE Language switcher

### ISSUE THREAD

**Issue by Alboorii** [Xtraball/SiberianCMS#111]
Hello

In MAE the Language switcher is hidden, must to hover to view it. In PE its okay.
![language-selection](https://cloud.githubusercontent.com/assets/13621788/21611773/53bca42a-d1df-11e6-95c8-63368bc9aff7.gif)

**Comment by dbyzero** [comment]
It's confirmed thanks.

**Comment by fouineux** [comment]
Hello, this issue will be solved in a forthcoming update. Thanks for your report!
