### ISSUE TITLE
Radio Module sae and mae

### ISSUE THREAD

**Issue by rogerdavis198** [Xtraball/SiberianCMS#112]
Bug been ages for fix guys , not working ie no audio playback via radio module on android 6 (iconic version)

non iconic sites before v4 will play ok with older radio module till upgraded to iconic then no go on android 6.

cheers

**Comment by dbyzero** [comment]
For 2017 we will focus on debugging and stabilization. Sorry for delay.

**Comment by gonzoradio** [comment]
First....I would love if you guys could stabilize the radio player. Plus bring back purchase links with choice for itunes, google play and amazon, and make it so our Now Playing data xml can be loaded in as a song list with options to purchase and room for our affiliate codes to be added. Most radio stations (like the 6 i'm building apps for right now) use an xml 'now playing' url to send song information that is then parsed into a playlist. PLEASE!!!??!!

Second....i use a fix for the radio player right now, on android. Apple seems ok without it.

in the following linked file you will find replacement code for both Audio.Player.java and Audio.Handler.java.....found in approot/java/org.apache.cordova/media/....

https://www.zap-media.ca/docs/source-code-changes.java

replace your app build code in Android Studio with the code in the file above. (there are several in the file, only use for the 2 mentioned above)

good luck!!

**Comment by Slicit** [comment]
We won't fix audio, rather we will rework it completely at some point because the code is old and not maintainable anymore.
