### ISSUE TITLE
socket.io its not recognized by siberiancms

### ISSUE THREAD

**Issue by tecnologiaterabyte** [Xtraball/SiberianCMS#115]
hi @dbyzero , i try to install module chatrooms, the error messages #19-015: The module are about install requiere the following one, SockeIO @1.0.4.

Version SAE: 4.8.8.

Regards,

Wilmer.

![error_socketio](https://cloud.githubusercontent.com/assets/4957021/22075529/b87f2438-dd82-11e6-9fe9-0993773b74cd.jpg)

**Comment by dbyzero** [comment]
Sorry for the delay, when you bought Chatroom, there was two zip in purchase page. One for chatroom module, one for socketio module.

Please contact contact@siberiancms.com if socketio module is missing.

Regards
