### ISSUE TITLE
Video - Youtube

### ISSUE THREAD

**Issue by rivman** [Xtraball/SiberianCMS#116]
Adding YouTube channel address don't show channel videos.
Using: https://doc.siberiancms.com/knowledge-base/videos/ on v4.8.8

Youtube function totally unusable.
Thank you for fixing it.

**Comment by rivman** [comment]
Seems to work only with channels that have videos, playlists are not taken in consideration.

**Comment by fouineux** [comment]
Hello,

Actually, in channel mode, you can just use the id of your channel : UCg72Hd6UZAgPBAUZplnmPMQ. The feature will get all videos from this is.

Anyway, the size of the database field will be increased in 4.10 update.

Thanks for your report.
