### ISSUE TITLE
menu on homepage not showing

### ISSUE THREAD

**Issue by wouter76** [Xtraball/SiberianCMS#117]
When updating to 4.8.8 the menu's on the homepage do not appear anymore. 
This is a problem in the homepage-layout.js on line 144 where a check for a custom width is done on HomepageLayout.properties.layoutOptions.sidebarWidth but the script fails loading the homepage menu when HomepageLayout.properties.layoutOptions is undefined, so I suggest to change line 144 to: 

`if (typeof HomepageLayout.properties.layoutOptions !== "undefined" && typeof HomepageLayout.properties.layoutOptions.sidebarWidth !== "undefined") {`

**Comment by dbyzero** [comment]
Thanks for the fix, we add it to the next release (`4.8.10-beta1`).
