### ISSUE TITLE
Color Editor Not working 

### ISSUE THREAD

**Issue by RoczWebDev** [Xtraball/SiberianCMS#118]
HI Guys , Color editor does not seem to work anymore , only icon color changes but no other styling works , any solution to fix ? I've logged a ticket but no response

**Comment by clifton11221** [comment]
It works for me but sometime I have to put the hex color twice in order to make it save.  

I put it in once, close the screen... Then open the dialog box and put in the hex color again.

**Comment by grafixpress** [comment]
For me it accepts the color change but doesn´t show the changes in emulator. Or it shows changes after switching the emulator to "List" and back. But then going to features all changes are lost, though visible in the color editor correctly.

**Comment by SiberianCMS** [comment]
The issue vas related to a validator not "validating" in some servers for an unknown reason.

We changed the validators, it's released in 4.8.11-beta.4 and will be part of 4.8.11 next week.
