### ISSUE TITLE
Cover Photo Image Sometimes Doesn't Show In Simulator  

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#120]
The "Cover Photo" (new feature) image often doesn't show in the Simulator.  I'm not sure what triggers it to show or not show. 

I'm using Siberian version 4.8.9.

**Comment by clifton11221** [comment]
This NOT a bug.  I had to clear my browser cache.

**Comment by dbyzero** [comment]
Ok thanks :)
