### ISSUE TITLE
Tips for mouse over 

### ISSUE THREAD

**Issue by rivman** [Xtraball/SiberianCMS#122]
enhancement:

Hello,
It would be wonderful for users to be able to actually read the text of the buttons of those many features.
Sometimes the translations contain more than accepted number of characters, so the name of the feature became truncated like for exemple "News"  -- > Actualités  (in French) that became in feature button something like "Act...és".
Having some tips on mouse hover in Add Feature part alse in already addes features band will be great. Something like http://qtip2.com/demos
The function already exist with modern browsers but one has to hold very still the mouse cursor more than 3 seconds to see it. 
It is such a simple feature that could do so much pleasant user experience.

**Comment by dbyzero** [comment]
Click and Tips are different for UX, but it's a good idea and enahancement that you propose. Anyway, we have an issue with the ellipsium CSS.

**Comment by rivman** [comment]
The enhancement is not for the generated application. Only for the platform. 
Thank you, have a great day.
