### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by rivman** [Xtraball/SiberianCMS#123]
**Missing translations :**

From Facebook page, the link that open the Facebook post:
![translation1](https://cloud.githubusercontent.com/assets/11364533/22168970/ea1de8b8-df70-11e6-96bc-933a40d29dd8.PNG)

Once opened, the bottom "Done" need translated also:
![translation2](https://cloud.githubusercontent.com/assets/11364533/22168990/03943f0e-df71-11e6-9d23-f604c32a0464.PNG)

In "Design" , dropdown to chose to show or hide shadows:
![translation3](https://cloud.githubusercontent.com/assets/11364533/22169220/cadbd026-df72-11e6-81b1-aca63c116dfb.PNG)

In "Design" after home page images:
![translation4](https://cloud.githubusercontent.com/assets/11364533/22169257/10867a9a-df73-11e6-9609-f2b8cd8bf4b9.PNG)

In "Privacy Policy" feature, the button to reset to default:
![translation5](https://cloud.githubusercontent.com/assets/11364533/22169384/f6cd5fa0-df73-11e6-8f50-a9af4e7efcb4.PNG)

"Places" feature > Adding image for a place
![translation9](https://cloud.githubusercontent.com/assets/11364533/22170648/011dc69a-df81-11e6-8bd6-f6947c07c965.PNG)

"Places feature" > Display filters  "Order places by distance":
![translation7](https://cloud.githubusercontent.com/assets/11364533/22170603/3001fad6-df80-11e6-97e0-85f3abd93a5e.PNG)

"Places feature" > Adding elements, element "Cover" upper band.
![translation8](https://cloud.githubusercontent.com/assets/11364533/22170633/b20c4914-df80-11e6-9a3a-d881ed97adfc.PNG)

Adding products, product format, add fields (1nd, 2nd, ...) put simply 1, 2, 3:
![translation6](https://cloud.githubusercontent.com/assets/11364533/22169502/d30bf3e6-df74-11e6-8c86-54cbd0aab175.PNG)

WooCommerce feature button named "WooCommerce Link" can't be translated (don't exist in weblink.csv)

**Comment by nevergiveup007** [comment]
Il est top to back end en orange!
Je vais mettre le mien aussi dans cette couleur..

**Comment by Slicit** [comment]
Most translations will be fixed in 4.12.1, some are irrelevant, please re-open a ticket after 4.12.1 release, if you still have missing translations, thank you.
