### ISSUE TITLE
RSS Doesn't display images

### ISSUE THREAD

**Issue by theeugenegroup** [Xtraball/SiberianCMS#128]
Feeds from RSS 2.0 doesn't display images

**Comment by PofMagicfingers** [comment]
This is a known issue with feeds using relative protocol schemes. (i.e. `//mysite.com/myimage.png`)  We'll work on it soon.

**Comment by PofMagicfingers** [comment]
@theeugenegroup can you please give us the URL of the RSS feed so we can be sure it's the relative protocol scheme issue ?

**Comment by theeugenegroup** [comment]
here you go

http://www.brandpointcontent.com/PrintSite/CategoryFeed.aspx?CategoryId=14&MemberId=89491&format=rss2

**Comment by karargaht** [comment]
Yes, RSS no longer shows pictures

**Comment by PofMagicfingers** [comment]
found the issue, this should be fixed in next release.
