### ISSUE TITLE
contact module

### ISSUE THREAD

**Issue by dirkbrans** [Xtraball/SiberianCMS#131]
In the contact module, load Google Maps not good
![2017-01-24 10 45 03](https://cloud.githubusercontent.com/assets/4491704/22242169/a9ac7d6c-e222-11e6-8011-e630c09c8c33.png)

**Comment by dbyzero** [comment]
Did you set API key ?

**Comment by dirkbrans** [comment]
Yes, the card is very short in the picture.
further works Maps properly

**Comment by PofMagicfingers** [comment]
Which version of SiberianCMS do you use ?

**Comment by dirkbrans** [comment]
PE - v4.8.9

**Comment by PofMagicfingers** [comment]
We'll investigate and get back to you

**Comment by dirkbrans** [comment]
The dashboard in the works.
On the iPhone it does not work.
On the android phone  it works

**Comment by rogeroffer** [comment]
Same here

**Comment by dbyzero** [comment]
It was an API issue, it's fixed since few days.
