### ISSUE TITLE
Issue With GeoLocation When No Sim

### ISSUE THREAD

**Issue by yoyummy12** [Xtraball/SiberianCMS#132]
We need this adjusting according to one of my Team   Usually been testing on Iphone and Samsung but cheaper phones/ Tablets  we face an issue with for geolocation services if there is no SIM 

When phone Ipad etc has no sim just WiFi
Geo Location  wasn't working without ACCESS_WIFI_STATE permission. 

[24/01/2017 13:21:24] 
this is whats in ionic app code
[24/01/2017 13:21:26]   "AndroidManifest.xml": {
                "parents": {
                    "/*": [
                        {
                            "xml": "<uses-permission android:name=\"android.permission.INTERNET\" />",
                            "count": 2
                        },
                        {
                            "xml": "<uses-permission android:name=\"android.permission.WRITE_EXTERNAL_STORAGE\" />",
                            "count": 4
                        },
                        {
                            "xml": "<uses-permission android:name=\"android.permission.ACCESS_NETWORK_STATE\" />",
                            "count": 1
                        },
                        {
                            "xml": "<uses-permission android:name=\"android.permission.ACCESS_COARSE_LOCATION\" />",
                            "count": 1
                        },
                        {
                            "xml": "<uses-permission android:name=\"android.permission.ACCESS_FINE_LOCATION\" />",
                            "count": 1
                        },
                        {
                            "xml": "<uses-permission android:name=\"android.permission.RECORD_AUDIO\" />",
                            "count": 1
                        },
                        {
                            "xml": "<uses-permission android:name=\"android.permission.MODIFY_AUDIO_SETTINGS\" />",
                            "count": 1
                        },
                        {
                            "xml": "<uses-permission android:name=\"android.permission.READ_PHONE_STATE\" />",
                            "count": 1
                        }
                    ],
[24/01/2017 13:21:36]     ---
"ACCESS_NETWORK_STATE"

See https://github.com/driftyco/ng-cordova/issues/743

and comment by 
MikhailRoot commented 27 days ago
I've tried cordova-plugin-geolocation with ngCordova but it always returned me Timeout error, meaning it can't get device's position in my even 5 minutes set timeout, so the final solution for Android 5.1 at least:
i've added permissions to AndroidManifest.xml

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.NETWORK_ACCESS" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
it wasn't working without ACCESS_WIFI_STATE permission. Now it works even without a sim card, with wifi connected and location enabled.
In case someone will find it helpfull.

**Comment by PofMagicfingers** [comment]
Could you explain us what is exactly the issue ? what OS are you using ? iOS, Android ? And what you're trying to do, what is happening and what should be happening instead ?

We do some of our tests on an iPhone with no SIM and on a Samsung Galaxy Tab with no SIM, and we never had any issue.

Thanks.

**Comment by yoyummy12** [comment]
See above I edited original post with the problem and the answer     Im having issues with Location on certain devices like lenovo phones

**Comment by PofMagicfingers** [comment]
We'll look into it. Thanks for the informations.

**Comment by dbyzero** [comment]
It's probably because your low cost device use triangulation as a GPS position... so it needs a SIM Card.
