### ISSUE TITLE
App previewer

### ISSUE THREAD

**Issue by glopr** [Xtraball/SiberianCMS#133]
I can't see the new Popup menu Layout on apps using it when viewd from app previewer.

**Comment by clifton11221** [comment]
Same here...

**Comment by krypt3d** [comment]
Might have to wait for new version of previewer app possibly to test. Had similar occurrence before. For example, the Job Board module didnt open in previewer and I tested using editor. When App was live it worked normally.

**Comment by SiberianCMS** [comment]
When you don't see new features and/or layouts in the App Previewer, this is likely that it's not up-to-date.

There is two way to update it.

I. The update-way
1. Run the Previewer
2. Log-in
3. Open any Application
4. Put the App previewer in background for about 30 seconds
5. Re-open it & it should be up-to-date.

II. If the previous didn't worked.
1. Rebuild the Previewer APP.
