### ISSUE TITLE
Ready to publish does not trigger e-mail anymore

### ISSUE THREAD

**Issue by rogeroffer** [Xtraball/SiberianCMS#134]
The ready to publish my app does not trigger e-mail anymore for the admin to generate the apk file
![screen shot 2017-01-25 at 10 36 47 am](https://cloud.githubusercontent.com/assets/2719620/22283361/76c8b398-e2ea-11e6-9dd4-f2406ac9faaf.png)

**Comment by dbyzero** [comment]
Did your SMTP parameters are correctly set in https://<your siberian>/system/backoffice_config_email ?

**Comment by rogeroffer** [comment]
yes they are, I also tried it with disabling the smtp and no email is triggered

**Comment by dbyzero** [comment]
Ok a dev will check the issue.

**Comment by SiberianCMS** [comment]
As far as we remember, there was no e-mail sent during this step.

**Comment by rogeroffer** [comment]
Lets refresh your memory
![screen shot 2017-01-25 at 12 14 26 pm](https://cloud.githubusercontent.com/assets/2719620/22286497/09abc29c-e2f8-11e6-9c59-a8efb5f9c4f5.png)

**Comment by SiberianCMS** [comment]
Okay thanks, found it, I was searching in PE, this mail is only sent in MAE

**Comment by rogeroffer** [comment]
Yes MAE

**Comment by SiberianCMS** [comment]
It's scheduled for the 4.8.11, thanks.
