### ISSUE TITLE
radio player and layout 9

### ISSUE THREAD

**Issue by rogeroffer** [Xtraball/SiberianCMS#135]
When using layout 9 and the radio player, when you try to close the radio player or to go back (back button) it will go to the white loading screen. So it is trying to load the radio player again instead of going back to the last page or menu

**Comment by Slicit** [comment]
The issue was bypassed in 4.12.0, if radio is in the first position on layout 9 the first valid Feature is loaded instead, the changes required for radio to work nicely are too important, and could impact Audio feature.
Thanks.
