### ISSUE TITLE
Real-Time Chat Bug

### ISSUE THREAD

**Issue by Kaharian** [Xtraball/SiberianCMS#137]
Hi team,

We found a bug on the Real-Time Chat module. Whenever I try to click message so I can start writing, It opens up the other page... so there is no chance for me to write a message. When you close it again and try to compose  a message... it will just be a vicious cycle, it will open up the other page... please check the images below...  These are just the two pages that you can see... and you cant type in message box at all because the moment you touch the box, the other page opens.
![screenshot_20170125-204728](https://cloud.githubusercontent.com/assets/25316236/22302562/c873bb0c-e2db-11e6-971b-a6b110189030.png)

![screenshot_20170125-204719](https://cloud.githubusercontent.com/assets/25316236/22302579/d5a079aa-e2db-11e6-934b-bc8f44016a1c.png)

**Comment by PofMagicfingers** [comment]
This should not be happening, we have not heard of this issue before. Could you give us the following details : 
- Version of Siberian CMS (SAE/MAE/PE and version number)
- Mobile OS (Android or iOS) and version of this OS.

Thanks !

**Comment by Kaharian** [comment]
My version is the latest. 4.8.10
Mobile is Samsung Galaxy S7 Edge, Android 6.0.1

**Comment by portalidea** [comment]
You're lucky...I can't write message because I've a connection error
4.8.10
iOS and Android

**Comment by PofMagicfingers** [comment]
@portalidea Did you open port range 35500 to 36000 in your server firewall ? You can check if it is accessible with this [online port checker](http://www.ipfingerprints.com/portscan.php). If you still have an issue, please submit another issue, or open a ticket.

**Comment by PofMagicfingers** [comment]
@Kaharian do you have any way to record your screen so I can be sure about the issue you encounter ? thanks.

You can use something like [AZ screen recorder](https://play.google.com/store/apps/details?id=com.hecorat.screenrecorder.free) or such kind of apps

**Comment by Kaharian** [comment]
Here's the result...

![screenshot_20170126-164720-01](https://cloud.githubusercontent.com/assets/25316236/22333449/bfda592c-e382-11e6-9cf4-2cb4cd6f3b7c.jpeg)

**Comment by PofMagicfingers** [comment]
@Kaharian Your backoffice must show "External extensions Socket IO running", and if your Siberian is using SSL, you must access the chatrooms using SSL, so apps must be regenerated, recompiled and republished, and web app must be accessed via HTTPS. 

If you comply to these requirements, and it still doesn't work : open a support tickets.

Thanks.

**Comment by Kaharian** [comment]
Yes... Socket IO running SSL is okay etc... I'll open a suppoet ticket about this. Thanks...

**Comment by portalidea** [comment]
All 501 scanned ports on xxxxxx.info (xxxxxxx) are filtered
Socket IO running SSL is okay

**Comment by dbyzero** [comment]
It's a specific issue, you bought chatroom so you can send a mail contact@siberiancms.com and support will help to find your issue.

**Comment by PofMagicfingers** [comment]
@Kaharian  Okay I just understood what was your issue : 

When you click on message, look carefully the modal appearing : it says "please choose a nickname". Please, choose a nickname ;)

Then you'll be able to send messages. You cannot send messages without providing a nickname.

@portalidea : like @dbyzero said, it's a server/installation specific issue, send an email to contact@siberiancms.com Thanks.
