### ISSUE TITLE
Feature Backoffice / Advanced / Modules List Template Instaled.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [Xtraball/SiberianCMS#139]
Hi, It would be great to have the template list installed with your version, below the list of installed layouts, and you might have the option to remove them,

Thks,

Wilmer.

**Comment by SiberianCMS** [comment]
The problem with removing templates, is that if a Template is used within an Application, it will break all references to it and, break the app along.

Disabling them, however is possible and the best option.

**Comment by tecnologiaterabyte** [comment]
@SiberianCMS You can add a field that indicates if the application is published, for example if I have a client and no longer pay for the service because keep your application active, there must be a way to delete it

**Comment by Slicit** [comment]
You can't `delete` a template, but you can now disable it.
![screen shot 2019-02-12 at 12 03 05](https://user-images.githubusercontent.com/4389060/52631121-3aff8900-2ebe-11e9-9de6-901dbfe7afed.png)
