### ISSUE TITLE
Publish Section 

### ISSUE THREAD

**Issue by haskah** [Xtraball/SiberianCMS#14]
when customers try to publish their apps  it shows our main administrator account  id and pass 
didnt find where from get this informations
<a href="http://y64i.imgup.net/apple-id7ac8.jpg" target="_blank"><img src="http://y64t.imgup.net/apple-id7ac8.jpg" alt="apple-id.jpg - Free Image Hosting by imgup.net" title="apple-id.jpg - Free Image Hosting by imgup.net" style="border-width:0;"></a>

**Comment by SiberianCMS** [comment]
It's an autocomplete issue, recent browser automatically fills text/password input even if they are not intended too.
