### ISSUE TITLE
multiple linker warnings : ( was built for newer iOS version than being linked)

### ISSUE THREAD

**Issue by unilater** [Xtraball/SiberianCMS#140]
Hi,
When i compile in xcode (last version) there are many warning (about 300) with message: ...was built for newer iOS version () than being linked ( ) . how can i fix? I use single app edition

**Comment by krypt3d** [comment]
Try using Xcode 7 to compile app.

**Comment by PofMagicfingers** [comment]
Those are just warning and can be ignored. I got those daily and compiled apps works fine.

**Comment by unilater** [comment]
Possible update all Cordova plugin toast latest version? Or not worked with update? Many plugin are deprecated or old version. I try submit to the store.

**Comment by PofMagicfingers** [comment]
Not sure what you mean by this... ? Could you please rephrase that ? Sorry.

**Comment by clifton11221** [comment]
Though it would be nice to not have the warnings, as stated, you can ignore them and all will be fine.

**Comment by SiberianCMS** [comment]
Seing all the stack, and even in Android builds, it's almost impossible to eliminate all warnings ...
