### ISSUE TITLE
UI Style, Colours and Fonts Enhancements

### ISSUE THREAD

**Issue by krypt3d** [Xtraball/SiberianCMS#141]
Enhancement:

I think with how currently the industry is moving, we should perhaps look into more UI updates. We already have very strong modules as is. I have attached some screenshots below with a competitor for reference to Calendar and Log In Interface to give an example. 

The trend seems to be continually moving towards more of a simple flat design with good use of white space. Hoping we can also integrate modern Google Fonts into apps.

Also attaching a website link that can hopefully be of use for future development in terms of design colour palettes.

https://material.io/guidelines/style/color.html   <---- Design Guidelines

Thanks guys keep up the great work.

![img_0641](https://cloud.githubusercontent.com/assets/25313885/22315964/2ef79272-e327-11e6-97f9-62ae1d3e87c7.jpg)

![img_0698](https://cloud.githubusercontent.com/assets/25313885/22315960/2456f3bc-e327-11e6-88c2-07b50cd8a80b.jpg)

**Comment by clifton11221** [comment]
I agree...

**Comment by rivman** [comment]
+1

**Comment by dbyzero** [comment]
looks really nice! We will try to implement it soon. I tag it as a prior enhancement in our internal bug tracker.
