### ISSUE TITLE
RSS Module: Design 2 Bug... Doesn't Display Latest Post

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#142]
The 2nd Design option in the RSS Module has a bug... It doesn't display the latest post in the rss feed.

I'm using MAE - v4.8.10

See the images below... When I select the default design, the latest post display.  When I select the 2nd design option the latest post is missing.

**_Below is the default design.  It shows the latest post (see "Google's New Privacy Policy" (blue Privacy image))._**

![rss_design_2_bug_01](https://cloud.githubusercontent.com/assets/21089972/22340229/b3060c4a-e3ba-11e6-93f5-ec351454a2bb.png)

**_This is the 2nd Design option, the latest post is missing ("Google's New Privacy Policy")._**

![rss_design_2_bug_02](https://cloud.githubusercontent.com/assets/21089972/22340262/cfe366f0-e3ba-11e6-9a97-70d2226f9ffc.png)

**Comment by dbyzero** [comment]
Fixed in 4.8.12
