### ISSUE TITLE
SocketIO 

### ISSUE THREAD

**Issue by dirkbrans** [Xtraball/SiberianCMS#143]
SocketIO Server: Offline  versie 1.2.1

**Comment by PofMagicfingers** [comment]
Please update to Socket.IO 1.2.2
You can find the last version in your purchase history here : https://www.siberiancms.com/checkout/purchase-history/

Thanks.

**Comment by amjadhadi** [comment]
I have same Problem with Socket.IO 1.3 version 
Port range enabled also 33500-36000

**Comment by dirkbrans** [comment]
Update to Socket.IO  	1.6.0
You can find the last version in your purchase history here : https://www.siberiancms.com/checkout/purchase-history/
