### ISSUE TITLE
New Layout: Popup Menu

### ISSUE THREAD

**Issue by glopr** [Xtraball/SiberianCMS#144]
Bug:

On new popup menu layout I've found three issues that would be good to fix on new updates.

#1. If you setup transparency to menu icons, there are a duplicated trigger menu when it is not expanded. See image at https://scontent-mia1-1.xx.fbcdn.net/v/t1.0-9/15977411_10211295040795914_8970572401777924241_n.jpg?oh=e0e172a13b64931fed545a73257b1068&oe=594AC2E3 

Also, on same image you will see other menu icons behind main menu when it have transparency.

#2. When I open my app using popup layuot, the buttom icon (Facebook in this case) doesn't display the word "Facebook" as other icons. The word "Facebook" is hidden behind black android menu bar. This test has been made using LG K7 device. See screenshot at http://prntscr.com/e1n97x

#3.  When closing menu after opening some features and closing again, the three horizontal bars on trigger menu button disappears and there remains a complete white circle. See screenshot at http://prntscr.com/e1n7wl

**Comment by clifton11221** [comment]
Confirmed... I have this issue with one of my apps.

**Comment by LikoV2** [comment]
#1 is intended, you will see the other menu icons stacked.

#2 I tried to reproduce it, but failed, so I guess it's fixed.

#3 Can't reproduce it either.
