### ISSUE TITLE
My account deconnexion

### ISSUE THREAD

**Issue by arthurkai** [Xtraball/SiberianCMS#145]
Hi Guys,
Users are automatically logout from their account for unknown reason. It affects a lot of features that request user login (Mcommerce, Loyalty Card, Scratch Card, appointment, Inbox...). Users have to login each time they want to use this features.
Siberian support told me that they are aware of this issue but will take a lot of time to find from where it comes from.
So may I suggest Siberian Developer to insert an automatic login based on Mobile UID when the App lauch. This solution may be easier and quicker to do than to find the issue.
But please try to find a solution as soon as possible. I receive a lot of complains.
Thank you

**Comment by PofMagicfingers** [comment]
Hi !

We actually already have an automatic login at launch... The real issue is sessions being renewed when they shouldn't. We're actively looking into sessions issues, and if we cannot find the origin of the issue, we'll probably rewrite our session system to have something more stable.

Thanks for the suggestions.

**Comment by arthurkai** [comment]
Hi PofMagicfingers,
If you already have an auto-login at App lauch...that means that it does not really works as user have to login again once the App lauched. Please Check. Thank you.

**Comment by PofMagicfingers** [comment]
Yes. That's exactly what I was saying. :slightly_smiling_face: 
Issue is not really on the mobile side. On some servers, the session id is changed, and a new 'not logged in' session is used instead of the real logged in session and we haven't found why yet.

**Comment by arthurkai** [comment]
Ok merci et bon courage a toute l'equipe.
