### ISSUE TITLE
Form validation popup

### ISSUE THREAD

**Issue by arthurkai** [Xtraball/SiberianCMS#146]
Hi Siberian Team,
HTML code appears in validation form popup. Please see attached image.
Thank you.
![screenshot_20170130-141152](https://cloud.githubusercontent.com/assets/19501632/22415937/e09db144-e6fd-11e6-9e4f-147cbc541cc9.png)

**Comment by fouineux** [comment]
Hello,

This isssue will be solved in the upcoming 4.8.12 update.

Thanks for your report.
