### ISSUE TITLE
Layout 9 If Source Code Is the First Feature

### ISSUE THREAD

**Issue by yoyummy12** [Xtraball/SiberianCMS#147]
If source code is first feature, the system is failing to invoke it after login

Let me explain 

All my Apps require account / login

- in my source code modules user is passed to other server and logged in

here is scenario

![img_1891](https://cloud.githubusercontent.com/assets/15705465/22417868/49b76ef2-e6ce-11e6-9dbf-f07cbce57a95.PNG)

user logs in and then goes to plain background screen

![img_1892](https://cloud.githubusercontent.com/assets/15705465/22417893/6098ff78-e6ce-11e6-8ae7-03d9c25d2705.PNG)

when they should be going to here 

![img_1893](https://cloud.githubusercontent.com/assets/15705465/22417915/7f2ecb5c-e6ce-11e6-912f-0f409f8b0712.PNG)

There is some adjustment that needs to be made when First Feature is Source Code to replicate invoking the manual selection of this feature

Thanks

**Comment by SiberianCMS** [comment]
fixed in 4.8.12.5
