### ISSUE TITLE
Wrong Homepage image background for Tablet

### ISSUE THREAD

**Issue by arthurkai** [Xtraball/SiberianCMS#148]
Hi Siberian Team,
After several tests, it seems that Tablet (Ipad,Galaxy Tab) is taking the homepage background 640x1136 size for background instead of 1536x2048 size. In result, if logo is placed on the top it is cut.
Thank you.
![tablet](https://cloud.githubusercontent.com/assets/19501632/22419508/6a9a5cdc-e710-11e6-89e0-177a5199ffe2.jpg)

**Comment by clifton11221** [comment]
How did you give the language option in your app?

**Comment by arthurkai** [comment]
I have just made 2 folders.

**Comment by dbyzero** [comment]
It's due to sb-background directive, we will improve it, thanks Arthur.

**Comment by arthurkai** [comment]
Merci Cyril.
Pouvez vous voir aussi pour le Splash Screen.

**Comment by Slicit** [comment]
This is fixed in 4.12.0 branch, will be released as stable next week probably.
