### ISSUE TITLE
Translations missing (Facebook page view)

### ISSUE THREAD

**Issue by rivman** [Xtraball/SiberianCMS#149]
Hello,
Missing translation in Facebook page view:
In the screenshot: [109 more words]
Also "Open link" in main list.

![translation-fb-in-page](https://cloud.githubusercontent.com/assets/11364533/22430511/d23edd92-e70e-11e6-8db2-3b400766ff35.PNG)

Thank you !

**Comment by Slicit** [comment]
`Open link` is fixed for 4.12.1, for `more words` it comes from the Facebook API, i'm not sure it can be translated.
