### ISSUE TITLE
Source code in Custom Page feature

### ISSUE THREAD

**Issue by arthurkai** [Xtraball/SiberianCMS#150]
Hi Siberian Team,
Is it possible for you guys to modify the text color in Custom Page > Text section > Source code.
It is really hard to read and work on it because the text color is very light grey on white background.

Thank you guys.

**Comment by SiberianCMS** [comment]
In 4.8.11-beta.4

![siberiancms-custom-page-ckeditor-source-code-color](https://cloud.githubusercontent.com/assets/7977082/22598983/8f4bd15a-ea35-11e6-9253-1581a100e970.png)
