### ISSUE TITLE
COSMETIC - PRIX in catalogue field should be PRICE

### ISSUE THREAD

**Issue by herobe** [Xtraball/SiberianCMS#151]
![screen shot 2017-02-02 at 11 47 11](https://cloud.githubusercontent.com/assets/25324997/22546578/f8f14052-e93d-11e6-9d0f-503f764e2b31.png)

edited in /app/sae/design/desktop/siberian/template/catalog/application/create

But as this data will be overwritten upon future releases. I let you know. 

Only to rectify when all other issues are solved.

**Comment by fouineux** [comment]
Hello,

This issue will be fixed in the 4.8.12 upcoming update. 

Thanks for your report.
