### ISSUE TITLE
Calendar Module Facebook issues

### ISSUE THREAD

**Issue by grafixpress** [Xtraball/SiberianCMS#152]
In Flat Design: Facebook calendar can´t be created. Clicking on Add and the Facebook button there is no reaction. Using the old design it works.
Once created the calendar starts at 26th of June. All events before this date are not shown.
I tested this on MAE and my testing SAE, both with same results.

**Comment by dbyzero** [comment]
It looks like very bugged, it's an old feature that we have to improved, thanks.

**Comment by fouineux** [comment]
Hello,

I didn't managed to reproduce this bug. I can easily add a Facebook calendar, and it shows all the events. 

Can you tell me if you have this issue only with a specific browser, or on all of them?

**Comment by grafixpress** [comment]
I normally use Firefox, Chrome only to check webpages for correct function.  
But the live app shows only events from late June onwards. I´ll test on Chrome now.

**Comment by grafixpress** [comment]
Yes on Chrome all 3 Links work fine, not on Firefox though.
The newly in Chrome created Facebook events give the same starting date in late June

**Comment by grafixpress** [comment]
"Once created the calendar starts at 26th of June. All events before this date are not shown."
I created a new Facebook page and added all events from the old page, and linked the module to this page - I thought maybe the Facebook page is corrupted, becaus events from other Facebook pages worked fine.
Result: All went alright, until a certain amount of events were added. When I was finished with the last event of this year I encountered the same issue: 1st event was event from 26th of May.
Took me a day to find out the module holds only a certain amount of events starting from the last event.
Plain horror.

**Comment by grafixpress** [comment]
Hello,
after update to 4.8.12 beta1 the sort is even worse. 
Please reproduce with facebook ID fuerteventuraevents.
Listing starts in December 2017 and goes back to May 2017. 
Al events before this date are not shown.
Listing should start today and list all events beyond that date.

**Comment by Slicit** [comment]
Please update to 4.11.7, and re-open if still relevant, Facebook Calendar is working in latest release, and order has been fixed.

**Comment by grafixpress** [comment]
Yes sort is alright now. Events over more than 1 day disappear after starting date. But well...
