### ISSUE TITLE
Quiz Module: Only Allows You To Take A Quiz Once

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#153]
The Quiz module only allows you to take a quiz once. This needs to be fixed to allow people to take a quiz more than once… 

Actually, there should be an option (like the other options at the bottom of the Quiz during setup) to allow the app admin to select whether or not retaking the particular Quiz is allowed.

**Comment by PofMagicfingers** [comment]
Thanks for the suggestion, we added it, and the module will be updated soon !
