### ISSUE TITLE
Feature Image enhancement

### ISSUE THREAD

**Issue by arthurkai** [Xtraball/SiberianCMS#156]
Hello Siberian Team,
In Feature Image>Facebook, could you please make that Facebook folder names are displayed instead of the Facebook id name.

Thank you.
![facebook_image](https://cloud.githubusercontent.com/assets/19501632/22643345/9e4c31b0-ec90-11e6-86ff-15de8f80904d.jpg)

**Comment by fouineux** [comment]
Hello,

In a future update, you'll find an input for setting up a label for your gallery.

Thanks for your report!
