### ISSUE TITLE
Missing translation texts

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#158]
**xxx.com/sales/admin_invoice/view/id/1**

![screenshot](https://cloud.githubusercontent.com/assets/8930862/22646738/8b39d6aa-ec76-11e6-95cd-90f18963b13d.png)

**xxx.com/application/customization_features/list**

![screenshot3](https://cloud.githubusercontent.com/assets/8930862/22646798/ded9a812-ec76-11e6-8b74-4aed6c7d324d.png)

**xxx.com/application/customization_design_style/edit** (Layout 10)

![screenshot1](https://cloud.githubusercontent.com/assets/8930862/22646301/58e2210a-ec74-11e6-8641-8fda878f52e0.png)

**xxxx.com/application/customization_publication_infos**

![screenshot4](https://cloud.githubusercontent.com/assets/8930862/22646691/50ab65ee-ec76-11e6-9412-7e128b53d826.png)

**xxxx.com/application/customization_publication_infos**

![screenshot5](https://cloud.githubusercontent.com/assets/8930862/22646692/50ccaeca-ec76-11e6-97c9-29ac7bd29907.png)

**xxx.com/application/customization_features/list** (Push)

![screenshot6](https://cloud.githubusercontent.com/assets/8930862/22646935/87682bac-ec77-11e6-959e-a75c5d108300.png)

**xxx.com/application/customization_features/list** (Catalog)

![screenshot7](https://cloud.githubusercontent.com/assets/8930862/22647072/25812118-ec78-11e6-879a-f30e4e5a6b83.png)

V: 4.8.11 beta 4

**Comment by jumenta1960** [comment]
Hola. Esas traducciones también las he  solicitado en español y Siberiam está demorando esas solicitudes y llevo más de un mes y no resuelven.

**Comment by dbyzero** [comment]
English only, thanks.

**Comment by jumenta1960** [comment]
Buenos dias 

Cómo me van a prohibir que yo escriba en otro idioma distinto al mio cuando siempre he tenido contacto con ustedes y sin problema. 

Cordial saludo
 GUSTAVO BERNAL ORTIZ
Contador Público 
Especializado en Derecho Tributario
https://www.appcolombia.net.co
Ayúdenos a Ayudarle
  
 

    El Martes 28 de febrero de 2017 2:56, Cyril ALFARO <notifications@github.com> escribió:
 

 English only, thanks.—

**Comment by Slicit** [comment]
Please check latests updates, most of the translations are fixed, others will be in 4.12.1
Thank you.
