### ISSUE TITLE
View Code Source Enhancements

### ISSUE THREAD

**Issue by rivman** [Xtraball/SiberianCMS#159]
Hello braves Dev's!
Since you corrected the text color on view source code can it be possible to add the CodeMirror plugin for CK editor in future updates ? I will try to implement it and post here the result if possible. 

Thank you, have a nice day !

**Comment by SiberianCMS** [comment]
As we already added some CodeMirror in Source code & SCSS, it's cool to have it too in CKEditor source.

**Comment by SiberianCMS** [comment]
4.8.12-beta.1 introduces CodeMirror in CKeditor inside Custom Page, Places & Inbox.
