### ISSUE TITLE
Inbox Date is Always changing to the latest Inbox message

### ISSUE THREAD

**Issue by Kaharian** [Xtraball/SiberianCMS#160]
Hi there team!

I found a bug in the inbox module. I have about 4 inbox messages and those were sent and received by me on different dates... some are weeks and maybe event months interval. We should assume that all dates of messages have to be different from each other since the dates of sending and receiving of each are from different dates. But it is not... The date of the last message is automatically copied to all other earlier messages. Please see the attached image file below. Kindly try it also yourselves if this is the same with your or if this is unique to my copy of Siberian... Thanks!
![date](https://cloud.githubusercontent.com/assets/25316236/22685375/2a10475e-ed31-11e6-82a4-0997fda657d0.png)

**Comment by SiberianCMS** [comment]
Inbox will have a big update right after the 4.8.11 stable release, I'm not sure this issue is still existing and/or relevant.

Will inform you asap.

Thanks for the feedback.

**Comment by Kaharian** [comment]
This is good to know... I hope this issue is resolved with that... dates are important and we should never be wrong in this one.

Thanks!

**Comment by SiberianCMS** [comment]
Like in #164, this will be for the 4.8.12 (both Siberian & Inbox)
Closing this one.
