### ISSUE TITLE
accented by inserting text or with the "'' character appears the escape code &#39

### ISSUE THREAD

**Issue by euroonesistemi** [Xtraball/SiberianCMS#161]
Error in conversion in module NEWS.

insert new "News", title     > l'accentro <, save.
Error.
Best regards.

![bug-photo_2017-02-07_19-38-29](https://cloud.githubusercontent.com/assets/1251660/22705749/124f4d90-ed6d-11e6-91a1-0ee17c42a12c.jpg)

**Comment by PofMagicfingers** [comment]
Seems to be working in version 4.11.6, it might have been fixed in a previous release.
