### ISSUE TITLE
All Rich Text Editors Contain A Broken Image Symbol In Text Section

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#165]
All of the Rich text editors (Custom Pages, Places, etc) contain a symbol on the top-right-hand-side of the text portion that appears to be a broken image.

I'm using Siberian MAE v4.8.11

See the attached image.

![text_editor_bug](https://cloud.githubusercontent.com/assets/21089972/22804455/2460f2e2-eee7-11e6-970c-47899a49bb0a.png)

**Comment by clifton11221** [comment]
This is NOT a bug.  The issue stemmed from some cached data... The app was old. Once all temp files and cached data was removed from the server the issue was resolved.

**Comment by SiberianCMS** [comment]
It's a cross update/cache issue, gone for sure in 4.8.11.2

Thank you.
