### ISSUE TITLE
RSS Module No Longer Displays Images

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#166]
Since installing v4.8.11 on my MAE version, the RSS module no longer displays images (even when checking the option to display the image).

**Comment by clifton11221** [comment]
I updated to 4.8.11.1 and the issue is still there.

**Comment by PofMagicfingers** [comment]
Duplicates #128 

Can you give us the rss feed you're testing with ? Thanks.

**Comment by PofMagicfingers** [comment]
This will be fixed in a future release.

**Comment by PofMagicfingers** [comment]
This will be fixed in 4.12.x. Thanks for reporting the issue
