### ISSUE TITLE
Feature Place

### ISSUE THREAD

**Issue by arthurkai** [Xtraball/SiberianCMS#167]
Hey Guys,
Since 4.8.11, in Feature Places:
1.Whatever you decide to select or deselect to display address or location button, it is always shown by default in Overview and in Mobile App Also (no issue in 4.8.10)
2.In Search setting, when enter Thai text,warning message appears and can not register, only accept English.
3.When edit a place, language is not translate anymore.
4."Tags separated by comma" : translation is missing.
![place type](https://cloud.githubusercontent.com/assets/19501632/22816398/5da96e00-ef94-11e6-92af-46af4e4e35af.jpg)
![places](https://cloud.githubusercontent.com/assets/19501632/22816399/5daba1a2-ef94-11e6-864f-ceaf29ef28b9.jpg)
![place](https://cloud.githubusercontent.com/assets/19501632/22816400/5dac733e-ef94-11e6-8f4f-286e4732cbb4.jpg)

See picture.

Thank you
![location](https://cloud.githubusercontent.com/assets/19501632/22816203/2445b6c4-ef93-11e6-9eee-4c40c961e2b9.jpg)

**Comment by SiberianCMS** [comment]
So well :)

> 1.Whatever you decide to select or deselect to display address or location button, it is always shown 

this one is fixed in 4.8.12-beta.1 for the other ones, we need to do some tests.

**Comment by SiberianCMS** [comment]
I'm closing the issue as it's partially closed, and Places feature completely changed.

Please try again, and report a re-open a new ticket if some issues persists.

**Comment by dbyzero** [comment]
I confirm that bug is fixed
