### ISSUE TITLE
YouTube module: since updating to 4.8.11, doesn't show all of the latest videos from "channel"

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#168]
Since I installed 4.8.11 (doesn't work with 4.8.11.1 either) on my MAE edition, the YouTube module no longer shows the latest videos when using the "Channel" option.

When using "User" it works properly.

**Comment by dbyzero** [comment]
Thanks for the ticket, it's a prior issue and will be fixed in 4.8.13.

**Comment by fouineux** [comment]
Hello,

This issue will be fixed in the future 4.10 update.

Thanks for your report.
