### ISSUE TITLE
My account

### ISSUE THREAD

**Issue by arthurkai** [Xtraball/SiberianCMS#170]
Hey Siberian Guys,
When users create an account, all field should be mandatory otherwise. Please see attache file.

Thank you

![account](https://cloud.githubusercontent.com/assets/19501632/22861652/ff3549ac-f150-11e6-84f1-796de258a3ab.jpg)
![users_list](https://cloud.githubusercontent.com/assets/19501632/22861658/27a07d44-f151-11e6-9b07-5715e3665033.jpg)

**Comment by krypt3d** [comment]
On another note, could we remove the civility part. I don't think people need that information and many have asked to remove it on the SiberianCMS forums. 

It can be quite awkward to have depending on user base. For example, app that may be tailored towards younger audience.

**Comment by clifton11221** [comment]
Making fields mandatory should be optional.

I agree with the civility part.  It's not needed.

**Comment by dbyzero** [comment]
Thanks, I add a priority for the mandatory part on our internal enhancement tracker.
