### ISSUE TITLE
Weather 

### ISSUE THREAD

**Issue by champier** [Xtraball/SiberianCMS#172]
Hi, 
I found 2 bugs:
1. When its the first feature, do not show nothing (Only LOADING).

![image](https://cloud.githubusercontent.com/assets/15213215/22881618/0c255072-f1f0-11e6-92d6-8b101a7640cf.png)

2. when you add a background,  the background don't show in the app...

![image](https://cloud.githubusercontent.com/assets/15213215/22881433/201125f8-f1ef-11e6-829a-f03ff8d9deb0.png)

**Comment by Slicit** [comment]
1. It's fixed in 4.12.0
2. It's not an issue, you have to change opacity of the list in the page Colors.
