### ISSUE TITLE
Creating an account

### ISSUE THREAD

**Issue by arthurkai** [Xtraball/SiberianCMS#173]
Hi Siberian Team,
When creating an account, keyboard is hiding field so user can not see what he is writing. It is not possible to scroll down.
Please see video
https://files.mycloud.com/home.php?brand=webfiles&seuuid=d6468f39efdaa02a258467b3224792e3&name=20170214_165735
Could you please leave some blank after all forms in order to let users scroll down and see what he is writing.

Thanks a lot

**Comment by dbyzero** [comment]
Thanks for the report and the video. This native keyboard is a pain in the ass to manage... I will try to reproduce it on our devices, some device are ok, some device has the issue...

**Comment by arthurkai** [comment]
Merci Cyril,
Pouvez vous juste laisser des "blancs" a la fin de chaque formulaire (genre des <br/>). Ce qui permettrait de scroller vers le bas.

**Comment by dbyzero** [comment]
Pas bête ;).

**Comment by arthurkai** [comment]
Hi Guys,
As I see, you still did not make any modification in last update 4.8.12.4, could you please do it for all forms including the one in Commerce...it is really pain in the ass to fill form with invoicing and delivery address as you can not scroll.

Thank you.

**Comment by Slicit** [comment]
We will think of adding it where it's necessary, this shouldn't alter the way apps are working.
