### ISSUE TITLE
no button location asked but still you get button 

### ISSUE THREAD

**Issue by herobe** [Xtraball/SiberianCMS#175]
![sib_nolocation](https://cloud.githubusercontent.com/assets/25324997/22941228/f7881ae6-f2e4-11e6-9acc-c188bc07d1eb.png)

Adding an entry in places 
disabled the location button 
but Locate button is displayed

**Comment by SiberianCMS** [comment]
Fixed in 4.8.12-beta.1 ;)

You can however wait the 4.8.12 if you want to stay on stable branch.
