### ISSUE TITLE
generate qrcode employee password - .jpg missing

### ISSUE THREAD

**Issue by herobe** [Xtraball/SiberianCMS#177]
when user adds a code 
clicks QR icon 
qr code does not have the jpg extension 

workaround : while saving add .jpg 

solution : add .jpg extension in script export qr

**Comment by PofMagicfingers** [comment]
Will fix thanks

**Comment by PofMagicfingers** [comment]
@herobe Can you tell me on which feature the issue appears ? thanks

**Comment by herobe** [comment]
@PofMagicfingers  hey, thank you for response. 
This issue arises in v 4.8.11:2 but was there earlier. 
when hitting the QR icon next to passwords in loyalty there is no extension specified. 
now i discovered I can open it on my mac, but when you send it by email there is no extension so can't be opened. 
when adding extension .jpg you can open the QR. 
hope this clarifies. 
Issue is present in all features where you have the tab My passwords

**Comment by PofMagicfingers** [comment]
Issue has been fixed and is planned for 4.8.13. Thanks for the help !
