### ISSUE TITLE
Sharing Feature Posts Incorrect Information

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#178]
When sharing to Facebook, it posts the link to the app server and not the information that should be shared. Please see attached image.

![facebook](https://cloud.githubusercontent.com/assets/21089972/23041683/b436e29c-f463-11e6-876b-fa8b986eefe3.jpg)

**Comment by dbyzero** [comment]
Looks like a big issue, we will try to reproduce and if so fix it asap, thanks.

**Comment by clifton11221** [comment]
Just hoping this is still on the agenda :-)

**Comment by dbyzero** [comment]
Still in bug tracker as an Important update, for now we are focused on critical ones.

**Comment by clifton11221** [comment]
Just a note, the feature works on Twitter and LinkedIn but not on Facebook.

**Comment by PofMagicfingers** [comment]
Social Sharing is different on all features, can you please tell us which features you were using to share ? thanks

**Comment by userdevel** [comment]
@clifton11221 It is solved? The picture is here now?
