### ISSUE TITLE
Enhancement : WYSYWIG editor for modal function 

### ISSUE THREAD

**Issue by herobe** [Xtraball/SiberianCMS#180]
when adding function modal content is called 
editor should be in wysywig editor to allow more beautiful styled content

**Comment by dbyzero** [comment]
It's done in 4.8.12.

**Comment by herobe** [comment]
@dbyzero  Cyril, I am sorry.. with MODAL I meant the Modal window when adding a module. 
Now I see that you use Modal in the previewer app. 
Sorry, with MODAL I mean the preview text. 

see screenschot 

![screen shot 2017-02-20 at 18 15 47](https://cloud.githubusercontent.com/assets/25324997/23135412/d564854a-f798-11e6-9a3e-1600afafa859.png)
