### ISSUE TITLE
RSS feeds not displaying images

### ISSUE THREAD

**Issue by theeugenegroup** [Xtraball/SiberianCMS#181]
Even after update RSS still not displaying images

**Comment by clifton11221** [comment]
Yeah... I posted about this here:

https://github.com/Xtraball/SiberianCMS/issues/166


There's a note that states it will be fixed in a future release.

**Comment by PofMagicfingers** [comment]
Issue has been fixed in 4.8.12 beta 1. If you still have the issue with this release please give us the rss feed URL, we'll look into it.

**Comment by theeugenegroup** [comment]
Here is the RSS http://www.brandpointcontent.com/PrintSite/CategoryFeed.aspx?CategoryId=2&MemberId=89491&format=rss2

**Comment by PofMagicfingers** [comment]
@theeugenegroup there's no image inside this rss feed.

**Comment by theeugenegroup** [comment]
Yes there are.
<img width="1127" alt="screen shot 2017-02-17 at 10 06 15 am" src="https://cloud.githubusercontent.com/assets/8466469/23075214/d66ed2f8-f4f8-11e6-977e-1cf4520ce24c.png">

**Comment by PofMagicfingers** [comment]
Oh, yes, as enclosure tags. Anyway this should work with 4.8.12 beta 1... We'll look into it.

**Comment by PofMagicfingers** [comment]
This will be fixed in 4.12.x. Thanks for reporting the issue
