### ISSUE TITLE
Booking Feature

### ISSUE THREAD

**Issue by arthurkai** [Xtraball/SiberianCMS#182]
Hey guys,
Date error in Booking Feature:

1. when users choose date of booking: If day>12 there is a pop up error (example 20 February). But if the day is less than 12, the form is validate.

2. Email sent: The month is shown is Thai language but user has book in English. Could you change the month name by month number (03 instead of March) to avoid this Time Zone translation error on date. See attached pic.
![booking_email](https://cloud.githubusercontent.com/assets/19501632/23099324/5a231b4c-f696-11e6-82f3-1fbf8abee40d.jpg)

**Comment by dbyzero** [comment]
Thx for the ticket.

**Comment by fouineux** [comment]
Hello,

The displayed date format in email will be fixed in next update. For the first bug, we didn't manage to reproduce it. Can you be more specific please? Is this issue only happen on mobile phone?

**Comment by arthurkai** [comment]
ok let's look at example : 

1. Date selected is 26 February 2017 20:00 . See pics
![screenshot_20170224-211128](https://cloud.githubusercontent.com/assets/19501632/23306574/b34a8ca2-fad6-11e6-9a45-50a0ff1a8868.png)

2. After date selected it is well shown on screen : See Pics
![screenshot_20170224-211145](https://cloud.githubusercontent.com/assets/19501632/23306646/feeb3fee-fad6-11e6-8232-016e377e9010.png)

3. When sending the Booking form, here is pop up : See pics
![screenshot_20170224-211203](https://cloud.githubusercontent.com/assets/19501632/23306685/28dac734-fad7-11e6-80ec-d6368bc0eebe.png)

I think that your validation form script consider the day as month, so if the day is superior than 12, the script consider that month 13 does not exist and return the error in pop up.

**Comment by arthurkai** [comment]
Hi Guys, did you manage to reproduce the bug?

**Comment by dbyzero** [comment]
No, I try in French, Chinese and English and there is no problem at all. I'll do more test and try to find a potential issue in code.

**Comment by arthurkai** [comment]
Ok,
hers is 2 mobiles settings where bug was found : 

1. Mobile 1: Samsung S7 Edge
-Language : Thai
-Time zone : GMT+07:00 Indochina Time

2. Mobile 2: Huawei Mate 9 Pro
-Language : English (UK)
-Time zone : GMT+07:00 Indochina Time

Both return Pop Up error on form validation. Did you try a day date superior to 13?.

Thank you

**Comment by fouineux** [comment]
Hello,

We didn't manage to reproduce this bug on mobile, but we suspect it could be a locale issue. To be sure that this unwanted behavior will not happen anymore, we changed the way dates are computed while generating the email. We did some tests with Chinese, Thai and indochina locale, all is working fine so far.

This changes will be included in the 4.10 update.

**Comment by rivman** [comment]
PE - v4.8.12.4
The bug is still present if one chose >12 as day. 
Cleaned cache, republish the app. 
Already lost one customer. Others on the way. 
At last admit it as bug and please do something about it. Maybe date and hour as separate fields ?
Thank ou. 
![img_7773](https://cloud.githubusercontent.com/assets/11364533/23518373/85f83ad2-ff73-11e6-9125-6a6e044e0e89.PNG)

**Comment by arthurkai** [comment]
Updated to PE V4.8.9
Time Zone : Asia Bangkok GMT+7

After testing : 
1. Form validation script is now OK. Users can choose day>12
2. Time sent by email is still Time Zone issue

Thank you
