### ISSUE TITLE
Form Feature

### ISSUE THREAD

**Issue by arthurkai** [Xtraball/SiberianCMS#183]
Hey Guys,
This is a bug in Form module (different from Bug in Booking module)
Error in time when sending form to app owner:
user has fill the date with 20 February 2017 at 20:35 and App owner receive the email with 13:35 instead.
I think this is a Time Zone issue. My Platform is setting on Asia Bangkok Time Zone (+7).
See attached pic

![form_bug](https://cloud.githubusercontent.com/assets/19501632/23099535/20e8b854-f69c-11e6-81dd-6a65f844fba5.jpg)

**Comment by dbyzero** [comment]
Thx again.

**Comment by fouineux** [comment]
Hello,

This issue will be fixed in a future update. 

Thanks for your report.
