### ISSUE TITLE
Feature Place duplicate on same app

### ISSUE THREAD

**Issue by campoleo77** [Xtraball/SiberianCMS#184]
When there are more places features (ex. 1-services places  2-associations places) on the same app, there are problems on display and filter the right places. I open the 1 feature places (services) is ok, I go on the 2 feature places (associations) and I see the places of the first feature and reverse. Tested on android and on 4.8.11.2 version.

**Comment by dbyzero** [comment]
Thx for the report, we will check this ASAP.

**Comment by SiberianCMS** [comment]
Please update to latest version, and re-open a ticket if the issue is stil relevant.

**Comment by campoleo77** [comment]
Update and republished, problem not solved
