### ISSUE TITLE
Creating Custom Modules with cordova plugin inside.

### ISSUE THREAD

**Issue by fallen90** [Xtraball/SiberianCMS#185]
I was wondering if you could create a custom module with a cordova plugin as a dependency? I could't find it on the documentation or I haven't looked hard. But anyway If someone can actually shed some light to this one, I would be eternally glad for your help.

**Comment by dbyzero** [comment]
Platform we release in `var/` folder are already compiled with cordova modules. Some cordova modules are forked and modified, we not yet shared our custom modules or our dev environment but we think about it, may be for expert users.

So, for now, you cannot add native cordova plugin in siberiancms compiled apps.
