### ISSUE TITLE
Contacts Page

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#186]
I'm having problems on the Contacts page, where in the app editor it is correct as per the second image, but after the app is generated it looks like the first image appearing a border and images as pointed by the arrows in the first image.
I would like that when generating the app it would be the same as the second image.

Can someone help me please.

![image](https://cloud.githubusercontent.com/assets/25539714/23143706/923be99e-f7a1-11e6-8c53-ba17907ce7ca.png)

**Comment by ciadoreino** [comment]
I am using in version 4.8.11.12

**Comment by dbyzero** [comment]
Why did you close the issue ?

**Comment by ciadoreino** [comment]
Sorry, I did not want to close

**Comment by SiberianCMS** [comment]
Issue is opened for about 4 months, please update to latest version & re-open a ticket if the issue persists.

**Comment by rivman** [comment]
Contact use default page content css. You need to customise the display for that specific page to display it without border (it's a box-shadow). 
Icons are font awesome. You need to duplicate / create your own function layout or hide the icons in CSS.
