### ISSUE TITLE
Place feature enhancement

### ISSUE THREAD

**Issue by arbindbhagat** [Xtraball/SiberianCMS#189]
Currently, if you have 1000 places listed (for the yellow page type of app), all the places display at once, causing the app to use lot of memory and hence crash.

Since we already have a search option in the Place feature, it would be the best to display at most, say, 20 places at once, with a load more button which would load next 20 everytime a user clicks on load-more button. That way, the Place feature would be much more powerful and would open lots of possibilities.

**Comment by dbyzero** [comment]
I add it as a prior enhancement, we will first show 20 result and add more on scrolling.

**Comment by arbindbhagat** [comment]
Has there been any update/progress on this? Any expected date?

**Comment by Slicit** [comment]
Places have been updated to v2, closing this thread.
