### ISSUE TITLE
Video in Custom Page

### ISSUE THREAD

**Issue by arthurkai** [Xtraball/SiberianCMS#192]
Hey guys,

In Custom Page>Video>My Video, Loading Picture and Description are not saved in DB

**Comment by dbyzero** [comment]
Added as a critical bug, thanks.

**Comment by arthurkai** [comment]
Hey Guys,
PE 4.8.13
Browser cache cleared
Manifest manually rebuilt

bug is still here and getting worse : Now video is not played !!

**Comment by SiberianCMS** [comment]
Fix will be in 4.8.12.4 today.
