### ISSUE TITLE
Custom Page Section Name

### ISSUE THREAD

**Issue by arthurkai** [Xtraball/SiberianCMS#194]
Hey guys,

PE 4.8.12.1
My Backoffice setup is :
Default Language : Thai
Timezone : Asia Bangkok (GMT+7)

After update to 4.8.12.1 in Feature Custom, sections name are not translated anymore. See attached pic.

![custom](https://cloud.githubusercontent.com/assets/19501632/23288461/58155b06-fa76-11e6-947c-881457686325.jpg)

**Comment by dbyzero** [comment]
We had cache issue, can you try to update to 4.8.12.1 and check it again please ? Thanks.

**Comment by arthurkai** [comment]
Updated to 4.8.12.1 already and 
- delete server cache
- delete browser cache
- manualy rebuilt manifest

Section is still not translated

**Comment by dbyzero** [comment]
Ok thx

**Comment by arthurkai** [comment]
STP Cyril, trouves moi une solution pour au moins 1 des 2 bugs suivant : 

- Form Feature : https://github.com/Xtraball/SiberianCMS/issues/183 
- Booking Feature : https://github.com/Xtraball/SiberianCMS/issues/182

Merci

**Comment by fouineux** [comment]
Hello,

Translations will be fixed in the next hotfix.

Thanks for your report.
