### ISSUE TITLE
Push Date

### ISSUE THREAD

**Issue by arthurkai** [Xtraball/SiberianCMS#195]
Hey Guys,

Comme vous m'aviez dit que les bugs concernant le Time zone serait resolu a fur et a mesure  :
My Backoffice setup is : 
Default Language : Thai
Timezone : Asia Bangkok (GMT+7)

1. Editor is in english but push date is in Thai. see pic
![push_date_editor](https://cloud.githubusercontent.com/assets/19501632/23293734/62bbc4c2-fa9a-11e6-8e5e-798ff2823749.png)

2. In Mobile App (english language) but date is in Thai. see pic
![push_date_editor_mobile](https://cloud.githubusercontent.com/assets/19501632/23293760/895dd99e-fa9a-11e6-9a4a-3d9dc01fcfe9.jpg)

**Comment by dbyzero** [comment]
Thx.

**Comment by PofMagicfingers** [comment]
Should be fixed in 4.12.x. Thanks
