### ISSUE TITLE
Activate/deactivate not working

### ISSUE THREAD

**Issue by theeugenegroup** [Xtraball/SiberianCMS#198]
Activate/deactivate not working.

Feature still appears in menu on users device even though it has been deactivated

**Comment by clifton11221** [comment]
It appears to be a cache issue.

**Comment by dbyzero** [comment]
Did you update to last version, we try and have no issue.

![tg-1364_gh-198-nocache](https://cloud.githubusercontent.com/assets/2214094/23355981/718c146c-fcd8-11e6-8088-d022baae061b.png)

Use last version of your browser too.

**Comment by dbyzero** [comment]
Are you using firefox ?

**Comment by theeugenegroup** [comment]
Happens with Chrome and Safari

**Comment by dbyzero** [comment]
Try to click on button clear cache in backoffice.

**Comment by dbyzero** [comment]
Issue is on all maps or only few ?

**Comment by theeugenegroup** [comment]
Cleared cache, the problem is with all apps.
