### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#199]
I'm having problems on the Contacts page, where in the app editor it is correct as per the second image, but after the app is generated it looks like the first image appearing a border and images as pointed by the arrows in the first image.
I would like that when generating the app it would be the same as the second image.

Can someone help me please.

image

**Comment by ciadoreino** [comment]
Can someone help me please.
![image](https://cloud.githubusercontent.com/assets/25539714/23334630/919a1536-fb81-11e6-8fff-258d699615ff.png)

**Comment by dbyzero** [comment]
Dupplicate #186
