### ISSUE TITLE
Custom Page: CKEDITOR Options Not Available After Saving

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#200]
When using the CKEDITOR in the Custom Pages, all of the style options are available (Bold, Size, Txt Color, etc).  However, after clicking "Save", all of those options disappear and only the text and the code view is available. 

See attached images.

**BEFORE SAVING**

![ckeditor_bug_01](https://cloud.githubusercontent.com/assets/21089972/23341058/1376497a-fc0f-11e6-8653-25b4b6d90b49.png)

**AFTER SAVING**

![ckeditor_bug_02](https://cloud.githubusercontent.com/assets/21089972/23341062/1f6d2f1e-fc0f-11e6-8388-db1e5a89c894.png)

**Comment by theeugenegroup** [comment]
Same issue

**Comment by dbyzero** [comment]
Did you update to last release ?

**Comment by theeugenegroup** [comment]
Version 4.8.12.2

**Comment by clifton11221** [comment]
Yes... I'm using 4.8.12.2.

**Comment by SiberianCMS** [comment]
We tried a fix in 4.8.12.3 which will be released asap, I think this is due to too short timeout when initializing ckeditor instances.
