### ISSUE TITLE
Hamburger Icon Missing From Top Of 1st Page Of Layout 9

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#201]
The Hamburger Icon is missing from the 1st page of Layout 9.  As a result, there is no way for the app user to know that more options are available.

**Layout 9 - 1st Page Missing Hamburger Menu**

![layout_9_01](https://cloud.githubusercontent.com/assets/21089972/23344572/dc8b96f2-fc4c-11e6-8f79-b5338f439b17.png)

**Layout 9 - After Selecting A Page... Hamburger Menu Appears**

![layout_9_02](https://cloud.githubusercontent.com/assets/21089972/23344584/0feb6702-fc4d-11e6-8624-61ecdd8ada23.png)

**Comment by dbyzero** [comment]
Thanks for the report, we are aware of this issue and already have a task on our internal bugtracker, I close this task because it duplicates.

**Comment by clifton11221** [comment]
This bug still exist in MAE 4.8.12.6.

Below are screenshots of the menu in the app simulator and again where the menu icon is missing in the app previewer.  Also, after a while, the menu also disappeared from the app simulator.

When I first open the app previewer the hamburger menu is gone.  If I slide the menu with my hand, then click another icon/link, the hamburger menu appears.  

But if I go out, then go back in, it's gone again.

**MENU IN APP SIMULATOR**

![layout_9_bug](https://cloud.githubusercontent.com/assets/21089972/23876289/2173c218-0813-11e7-872a-225d18d95104.png)


**MENU IN APP PREVIEWER**

![layout_9_bug2](https://cloud.githubusercontent.com/assets/21089972/23876294/2c106690-0813-11e7-8db2-bddb222d2310.png)

**Comment by SiberianCMS** [comment]
This layout 9 has been partially fixed, from the mobile side, it remains an issue from the editor, which sets the visibility of the layout to homepage instead of toggle, which prevents the first feature to load.

I'll check when it will be fixed.
