### ISSUE TITLE
Hidden Folder Module

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#202]
There needs to be a way to add an app module (Custom Page, Form, etc) and NOT have it in a menu or Folder.  

This is a necessary feature to create complex apps (with a lot of components) yet only having modules visible when they are necessary.  Similar to designing web pages in a website.  When we design websites, we don't put every web page in a menu.  We only "call" the web page when it's needed...

I think to accomplish this you can add a "Hidden Folder" module.  A tree component like the regular Folder module isn't necessary.  

This would simply be where an app designer can place modules that he/she don't want "visible" (unless they are linked to).  By "visible" I mean that the module won't appear in the app menu or regular Folder module.  Modules placed here will only be shown if it is linked to (and clicked by the app user).

**Comment by dbyzero** [comment]
Good idea, I add it to our enhancement tracker.

**Comment by PofMagicfingers** [comment]
@clifton11221 In the meantime, you can actually just add a Folder and deactive it. All features inside it will remain activated, but as the folder is deactivated, they will not be visible.

**Comment by clifton11221** [comment]
@PofMagicfingers - Thanks for the tip!

**Comment by savsani** [comment]
You can also hide pages using li:nth-child(2+n) method.
