### ISSUE TITLE
after update to version 4.8.12,  error in creation / loading of Places feature

### ISSUE THREAD

**Issue by Pogg** [Xtraball/SiberianCMS#203]
After updating to version 4.8.12:

- adding Places feature results in an "an error occurred during loading" message (see picture);
- clicking on an existing Places icon to edit it results in the same message:

In both cases it results impossible to access to the configuration of the Places feature.

Furthermore, the /var/log/output.log reports the following error when adding and when removing the Places feature:

    Siberian_Json::decode(), unable to decode json.
    Syntax error

Thanks for any help.

![screen1](https://cloud.githubusercontent.com/assets/22890106/23377521/99e8ab34-fd30-11e6-8275-bbdb1c84ddd4.jpg)

**Comment by dbyzero** [comment]
We had cache issue with 4.8.12, did you try to update to 4.8.12.3 ?

**Comment by dbyzero** [comment]
Try to clear cache in backoffice after update to 4.18.2.3. It will be fixed with 4.9.0.

**Comment by Pogg** [comment]
I cleared the cache in backoffice and reloaded the page  `http://[my.siberian.url]/backoffice/index/clearcache/type/app_manifest`, then all worked again.

I haven't upgraded to 4.18.2.3 yet. Anyway please note that I can see the 4.18.2.3 upgrade if I check "Settings/Modules" in the backoffice, but the upgrade is not listed in the "Messages" section.

**Comment by SiberianCMS** [comment]
Closing as solved.
Only a cache issue.

Note: the message has been sent for the 4.8.12.3 you can update.

**Comment by teamtu3w** [comment]
I´m having a similar issue in version MAE - v4.12.7: 

> ERR (3): Siberian_Json::decode(), unable to decode json

The issues I´m having with my current installation are the followings:

- Cannot load the content editor for any app (hangs on loading page)
- Cannot login or register (when clicking on login, attached error appears: "An error occurred, please try again."). Neither the 'lost password' or Facebook option works.

P.S. The login issue is happening already before upgrading to the latest version.
