### ISSUE TITLE
Módulo Maps, taxi ride, jobs

### ISSUE THREAD

**Issue by jumenta1960** [Xtraball/SiberianCMS#206]
Es importante que se revise la función maps, presenta error de localización no deja registrar la longitud y latitud, adicionalmente, en el módulo jobs en la parte del correo del administrador se visualiza que allí también se encuentran los usuarios que se han registrado en la app. Y taxi ride el pasajero al solicitar un vehículo se da cuenta que no tiene alguien disponible, cuando si hay conductores disponibles. Cada vez que realizan cambios en los módulos no tienen en cuenta la traducción. Marca blanca al crear el cname la url sigue siendo la de la plataforma cuando en los mensajes o lecturas de tiger y siberian se lee que puede uno creaar su propia marca. Y no cambia tampoco en marca blanca la imagen. Ahora uno solicita soporte y llevo más de 90 días solicitando la colaboración y la contestación el problema lo tienen los desarrolladores.

**Comment by fouineux** [comment]
Please, reopen your ticket in english.

Thanks.

**Comment by jumenta1960** [comment]
Cómo me van a prohibir que yo pueda escribir en mi lenguaje nativo sino se escribir en ingles

**Comment by dbyzero** [comment]
Github is a community tool to exchange issue, idea and enhancement with all community. It's a dev oriented tool and everyone needs to understand what you are writing.

Switch to English or stay with SiberianCMS user support.

Regards.
