### ISSUE TITLE
Modules: Maps,Taxi Ride, Jobs

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#207]
__This is the translated version of this closed ticket:_ 
[https://github.com/Xtraball/SiberianCMS/issues/206](url)

It is important to check the **maps function**, it presents location error does not let register the length and latitude.

In addition, in the **module jobs** in the part of the mail of the administrator it is visualized that there are also the users who have registered in the app . 

And **taxi ride** the passenger when requesting a vehicle realizes that no one is available, when there are drivers available. Each time they make changes in the modules they do not take into account the translation. White mark when creating the cname the url is still that of the platform when in the messages or readings of tiger and siberian it is read that one can create his own brand. And it does not change in white mark the image either. 

No one support the requests I made 90 days ago...

**Comment by dbyzero** [comment]
These bugs are already in our bug tracker, since 90 days but we fix a LOT of bug currently and soon switch to these.
