### ISSUE TITLE
Make a change of plans

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#21]
It must be possible to switch between packages.

For example: A user is using a monthly package. However she wants to get the annual package.Unfortunately does not have such an option in user settings.

**Briefly objective: to make a change of plans.**

Of course, this is not a bug. I think this is a very important feature that needs to be.

Regards...

**Comment by alexyves** [comment]
As we focus on SAE issues/enhancements here on Github, and this concern the PE, I'm closing the issue.

However, we will keep the idea and will look if we could integrate it in a future release.

Thank you.
