### ISSUE TITLE
Translation in All App Home Page Title

### ISSUE THREAD

**Issue by arthurkai** [Xtraball/SiberianCMS#210]
Hi Guys,

Icon Title is not detecting phone and browser language anymore in Overview and App Previewer. Just Icon Title because header and feature are still translated in App. See pic.

![language](https://cloud.githubusercontent.com/assets/19501632/23500646/5b8f7798-ff63-11e6-9310-d5ac61d3864c.jpg)

**Comment by arthurkai** [comment]
OMG Published Apps are also affected!!!!

**Comment by PofMagicfingers** [comment]
Icon titles are not "translations" they're labels, I think this issue is cache related. We'll fix it asap.
