### ISSUE TITLE
Layout Swipe 

### ISSUE THREAD

**Issue by RoczWebDev** [Xtraball/SiberianCMS#211]
Layout Swipe  only Shows 1 Icon when app is open for the for the first time , when you go back from out of the 1 icon the rest of icons then show

**Comment by SiberianCMS** [comment]
Can you test it again with the latest update 4.8.12.5 ? (and a fresh APK)

**Comment by RoczWebDev** [comment]
Hi I will rebuild source code on 4.8.12.6 and revert

**Comment by SiberianCMS** [comment]
@RoczWebDev so what's the final result ?

**Comment by RoczWebDev** [comment]
Hi Still the same

**Comment by Slicit** [comment]
Please update to latest version, and re-open if issue is still relevant, thank you.
