### ISSUE TITLE
RSS Module: Option Design 2 & 3 Bugs (Still Doesn't Display Latest Post)

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#213]
This issue relates to this closed issue. [https://github.com/Xtraball/SiberianCMS/issues/142](url)

**DESIGN 2**
The 2nd Design option in the RSS Module doesn't display the latest post in the rss feed. In fact, the first few posts are missing and the first few displayed posts are out of order.  

There is no issue with the 1st Design Option

I'm using  - v4.8.12.4.

I'm testing with a feed from two different WP sites:

http://jadoremiamor.com/feed/
http://urbanareas.net/info/feed/

**DESIGN 3**

For Design option 3, the 2nd post contains "1-" that needs to be removed.

As posted above, I'm using  - v4.8.12.4.

I'm testing with a feed from two different WP sites:

http://jadoremiamor.com/feed/
http://urbanareas.net/info/feed/

**Comment by SiberianCMS** [comment]
Both issues are fixed in 4.12.0 which will be release soon.

For Design 2, the "Cover" was simply wiped out 
For Design 3, The "id" was appended to the title, probably a debug purpose which wasn't removed.
