### ISSUE TITLE
Inbox module: no send buttons at registration or login

### ISSUE THREAD

**Issue by grafixpress** [Xtraball/SiberianCMS#214]
I used inbox module in 4 applications.
In 2 apps all works alright
in 2 further apps I encounter the following issue:
The send buttons in login and registration form disappeared in all features that need login, also in my account. 
when deleting the inbox feature the buttons reappeared.
I tried Inbox module again with same result - deleted again and now the buttons are gone for good.
All cache deleted.

**Comment by SiberianCMS** [comment]
Update inbox to 4.8.12.2

Clear cache, and test again, thanks.

**Comment by grafixpress** [comment]
Updated and cache cleared, no change.

**Comment by Slicit** [comment]
Closing as inactive, update Siberian & Modules, and re-open if still relevant.
