### ISSUE TITLE
Remove icons

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#215]
Hello,
How do I remove the icons as pointed out in the image below?

![image](https://cloud.githubusercontent.com/assets/25539714/23589736/7a553a78-01b1-11e7-9013-993926a64d4d.png)

**Comment by dbyzero** [comment]
For now, you cannot. I add your demand as an enhancement. It's third ticket so we will check in priority after current debug session.

**Comment by campoleo77** [comment]
You can remove person icon editing SCSS on color section with this code:

.item.item-icon-left.item-custom {
.icon.ion-person {
display:none;
}
}

**Comment by ciadoreino** [comment]
thanks!
