### ISSUE TITLE
empty apps proliferation in backoffice

### ISSUE THREAD

**Issue by Pogg** [Xtraball/SiberianCMS#218]
Actually we have about 40 apps developed and shown in our backoffice (including those that were used as test and those that were aborted before their pubblication). After the last version upgrades I noticed that a lot of "empty apps" are listed in our backoffice (see picture). At moment there are about 25 more empty apps that apparently no one of our personnel claims to have created.

What's happening ? How could I clean all those (unuseful?) empty apps ? Does it represent a threat in terms of system corruption?

![empty-aps](https://cloud.githubusercontent.com/assets/22890106/23756655/a579c68e-04e4-11e7-862a-a0fc0eb75914.jpg)

**Comment by Pogg** [comment]
The support says it's a known bug that will be fixed with version 4.9. By the way it's always difficult for me to serch for a "known bugs list".

**Comment by dbyzero** [comment]
@Pogg More than a "Know bugs list", an "Incoming changelog" will be a good idea. I am still searching about best way to share it (i'm not a trello fan).

**Comment by dbyzero** [comment]
We started a public roadmap : http://board.siberiancms.com/#/board/3

**Comment by teamtu3w** [comment]
Is this public roadmap still available? Cannot find it..
