### ISSUE TITLE
The SCSS "Save" button on the Colors tab is not saving changes

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#219]
Olá,
The SCSS "Save" button on the Colors tab is not saving changes.

**Comment by ciadoreino** [comment]
Eu também percebi que no modo de design "Flat" funciona, mas no modo "Siberian" não funciona.

**Comment by clifton11221** [comment]
Sometime you have to re-add the hex color (do it twice)... Then it saves.

**Comment by ciadoreino** [comment]
I am changing the CSS code and clicking save, then if I close the screen I open again my change had no effect.

**Comment by dbyzero** [comment]
You probably have custom dev issue, we tried on different install without any error.

**Comment by SiberianCMS** [comment]
Are you up-to-date ? (4.8.12.6) ?

And is you CSS/SCSS valid ?

@ciadoreino  can you try this one

* {
  color: red !important;
  border: 1px solid yellow !important;
}

And let us know, with a screenshot for example !

Thanks.
