### ISSUE TITLE
APK mail

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#22]
APK created but the mail is not going (APK generator)

**Comment by SiberianCMS** [comment]
The mail is sent to the first user created on the platform, 
we planned to sent it to the user who initiated the APK generation.

**Comment by karargaht** [comment]
I am the platform Manager. Mail does not come to me.

**Comment by alexyves** [comment]
Mails will be sent to the person who clicked on he generate button on 4.4 or 4.4.1 next week.
