### ISSUE TITLE
Delete applications in Backoffice

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#220]
In the Backoffice application list a few applications have been created for testing, now I want to delete these applications and I would like to know how I delete them.

**Comment by ciadoreino** [comment]
I also noticed that in Design Mode "Flat" works, but in "Siberian" mode does not work.

**Comment by krypt3d** [comment]
Just an FYI, only flat design mode is supported now since the start of the new year.

**Comment by ciadoreino** [comment]
In the list of Backoffice applications a few applications have been created for testing, now I want to delete these applications and I would like to know how I delete

**Comment by krypt3d** [comment]
I believe currently there is no option to fully delete from backoffice but the devs are working on it for a future release as per siberian forums.

**Comment by ciadoreino** [comment]
Thanks!!

**Comment by dbyzero** [comment]
@krypt3d exactly, thanks
