### ISSUE TITLE
PDF Attachments

### ISSUE THREAD

**Issue by RoczWebDev** [Xtraball/SiberianCMS#221]
Hi App Stops working when accessing PDF attachments in the Custom Module

**Comment by PofMagicfingers** [comment]
Hi! 

Define "stops working" please. 

Thanks

**Comment by RoczWebDev** [comment]
Message Pops up " Application NAme has stopped working" , then app closes

**Comment by dbyzero** [comment]
In 4.10 on Custom Page, link behavior can be configurate. You will can choose "open in external app" to open it with PDF viewer on device (or native browser by default). It will fix the issue.

**Comment by RoczWebDev** [comment]
HI And where exactly does one configure this ? In the Dashboard there is no option for that
