### ISSUE TITLE
Taxi Cab Module: A Number Of Issues/Enhancements

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#223]
There are a few issues with the Taxi Cab module.  They aren't bugs but they are important issues that needs to be addressed:

**A) OPERATOR ASSIGNING JOBS** - The main function of a Taxi Cab Operator is to assign cab jobs to the Taxi Cab fleet.  However, this function is missing from the TaxiCub module.  

It would be a great benefit to app (cab) operators if they could use the admin section to assign cab jobs (that were either called in or sent to them via email) to their Drivers.  

The admin section could have an "Assign" section... The admin could then complete a simple From/To form (that contains the customer info, from/to address, etc) and select the Driver to assign the job to.  The Driver would then receive a Notification and could "Accept" or "Reject" the job as they would a job from a Customer.

**B) NOT BEING NOTIFIED OF NEW DRIVERS** -  Currently, there is no way for the app owner to know if a new driver signed-up for their service.  Even if they log into the app settings, they won't know unless they sort through their list of drivers.  This is very time-consuming... having to check unnecessarily multiple times throughout the day to see if a Driver signed-up.

Upon a person signing-up to be a Driver, the app owner should receive a notification email.

**C) APP OWNER CAN'T CONTROL PRICING** - Currently the app owner cannot control the prices that are charged to the Customers. What if the app owner wants to use one set price that all Drivers must use (because they only operate in a certain region)? Likewise, what if an app owner wants to offer a discount to all of their customers?  

There needs to be an option that will enable the app owner to override the price set by the Driver.

 

**D) APP OWNER CANNOT SEE DRIVER PRICES** - Currently there isn't a way for the app owner to see the prices that the Driver set in the app.  Upon viewing the driver details, the prices that the Driver set upon signing-up isn't visible. As the app owner, they should be able to see everything that's going on with pricing.

**Comment by clifton11221** [comment]
**E) APP OWNER CANNOT SEE ONLINE DRIVERS** - There needs to be a way for the app owner to see which drivers are currently online/working.

**Comment by Slicit** [comment]
TaxiRide module is a commercial module, bug fixes & improvements are handled via mail.

Thank you.
