### ISSUE TITLE
Remove border

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#224]
Hello,
I would like to know which command I include in SCSS to remove the pointed border with the red arrow in the image?

![image](https://cloud.githubusercontent.com/assets/25539714/23871843/d2efbec4-080a-11e7-8da1-cbcb0885de4f.png)

**Comment by dbyzero** [comment]
I don't have same look and feel. Looks like you custom your page. 

![selection_339](https://cloud.githubusercontent.com/assets/2214094/23891972/0bc2c55a-0899-11e7-89c3-492f5199d9f0.png)

To remove your border, find the element with inspector then change style to `border:0px`. cf : https://developer.mozilla.org/fr/docs/Web/CSS/border
