### ISSUE TITLE
Place feature duplicate on the same app filter problem 

### ISSUE THREAD

**Issue by campoleo77** [Xtraball/SiberianCMS#226]
When there are more places features (ex. 1-services places 2-associations places) on the same app, there are problems on display and filter the right places. I open the 1 feature places (services) is ok, I go on the 2 feature places (associations) and I see the places of the first feature and reverse. Tested on android, IOS and on 4.8.12.6 version.

**Comment by PofMagicfingers** [comment]
This should be fixed on 4.12.0 beta !
