### ISSUE TITLE
Push delivery.

### ISSUE THREAD

**Issue by arttex** [Xtraball/SiberianCMS#23]
When sending a message to the alert in the window a little room for text. How can I enlarge the text in the title and in the message. And to add a translation in buttons? PE.

![default](https://cloud.githubusercontent.com/assets/19585230/15687198/1b03c072-277c-11e6-87cb-18af91fb1a15.jpg)

**Comment by alexyves** [comment]
It has been improved/fixed in 4.4.0

http://updates.siberiancms.com/release-notes/sae/4.4.0.html

![14102639_10153788956904212_2088124888464009000_n](https://cloud.githubusercontent.com/assets/18324386/18017835/c81a3278-6bd3-11e6-911c-3d2b95de03bf.jpg)

**Comment by himdan** [comment]
Cool man
o
