### ISSUE TITLE
Email recipient

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#230]
Hello,
I'm creating a resource with a list of fields to be send by email, but after clicking the "Send" button the app monitors the message that was sent successfully, but the email does not reach the recipient.
Acredito que esteja faltando alguma configuração.
![image](https://cloud.githubusercontent.com/assets/25539714/23981472/9393de2c-09e5-11e7-8ad7-abc462d69f93.png)

**Comment by glopr** [comment]
Same issue for me...

**Comment by fouineux** [comment]
Hello,

After some tests we didn't manage to reproduce this bug. All data are sent successfully. 

It might be a configuration issue with your server. You can try to send an email via another service, like the mail command for example, to test your configuration.
