### ISSUE TITLE
Radio Module & Layout 5

### ISSUE THREAD

**Issue by glopr** [Xtraball/SiberianCMS#231]
Radio & Layout5: If back button is pressed (on phone, not app button) with Radio module openned, the Radio player doesn't close and loops trying to close with music listening on background. If I double click, then the radio close but music still listening. When I re-open radio module, the loop screen is displayed again. In my case, the app have multiple radio station modules.

**Comment by gonzoradio** [comment]
So one year almost, and no response to this?  I can confirm this is still the case with layout 10.  The radio module definitely needs some help on android, even with the recent upgrades.

**Comment by Slicit** [comment]
Fixed.
