### ISSUE TITLE
Link Module: In-App browser

### ISSUE THREAD

**Issue by glopr** [Xtraball/SiberianCMS#239]
When I try to use link module, the links open in external browser (not in-app browser). In some cases, I want to hide link url from address bar so using In-app browser will be helpful. Tested on Android only,

**Comment by dbyzero** [comment]
Fixed in 4.10.

![selection_349](https://cloud.githubusercontent.com/assets/2214094/24093527/8cdc8e5e-0d54-11e7-82cd-c4bec312be93.png)
