### ISSUE TITLE
APK size...

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#24]
![aaa](https://cloud.githubusercontent.com/assets/8930862/15708303/930a28c4-2806-11e6-8946-f16b8234dd6a.png)
![ddd](https://cloud.githubusercontent.com/assets/8930862/15708304/95689d08-2806-11e6-9f2e-2ec47abce5bc.png)

![fff](https://cloud.githubusercontent.com/assets/8930862/15708472/587ae058-2807-11e6-8d7d-9583e0cb3836.png)

![gggg](https://cloud.githubusercontent.com/assets/8930862/15708478/5c0e10c8-2807-11e6-954e-4ee758806757.png)

![size](https://cloud.githubusercontent.com/assets/8930862/15708305/97b0f66e-2806-11e6-843c-c994ebb132d1.png)

**Comment by dbyzero** [comment]
It's due to Cordova Ionic webview. I'll try to use wkwebview instead and check size.

**Comment by alexyves** [comment]
Reduced APK size with media optimization.
