### ISSUE TITLE
Dailymotion videos

### ISSUE THREAD

**Issue by glopr** [Xtraball/SiberianCMS#240]
Maybe this is an enhancement instead a bug but Dailymotion videos aren't playable on SCMS apps. I've tried with link module, custom page and source code without success.

**Comment by dbyzero** [comment]
Enhancement, thanks.

**Comment by dbyzero** [comment]
There is no reason that a simple link to dailymotion is not working. I change Label to bug.

**Comment by LikoV2** [comment]
Links to Dailymotion videos are working in external and internal browsers.
