### ISSUE TITLE
Scratch Card cannot validate

### ISSUE THREAD

**Issue by theeugenegroup** [Xtraball/SiberianCMS#241]
Scratch Card will not accept password, errors to "wrong password even though correct password is entered.

Previous cards are not deleted, old card still appear in the app even though they have been deleted in the CMS

**Comment by dbyzero** [comment]
What is your edition, SAE, MAE or PE ?

**Comment by theeugenegroup** [comment]
PE

**Comment by dbyzero** [comment]
We cannot reproduce, please create a support ticket and a developer will investigate the issue on your platform.
