### ISSUE TITLE
Inbox Bug - Doesn't Show Message Options Automatically (Text, Image, Video, Etc)

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#243]
When sending an message via the Inbox module, it doesn't show the editor options automatically (Text, Image, Video, Etc). Under the "Custom Thumbnail" button option nothing shows unless you scroll the page a certain way.  See below:

**When you first go to the page:**

![inbox_bug_01](https://cloud.githubusercontent.com/assets/21089972/24224792/9707285e-0f33-11e7-881f-8832466d55a0.png)

**After I scroll up to a certain point:**

![inbox_bug_02](https://cloud.githubusercontent.com/assets/21089972/24224813/a86e7d22-0f33-11e7-8752-5e0d7c71863a.png)

**Comment by dbyzero** [comment]
The reason is when you scroll the "Add section" panel is fixed at top of screen, it permit to manage section on smaller screens.

Look at the bottom of your first screen, there are buttons.

**Comment by dbyzero** [comment]
Indeed, behavior is strange. I reopen it.

**Comment by Slicit** [comment]
It will be fixed in the Inbox module update 4.11.7 which should be released by next week, thank you.
