### ISSUE TITLE
Icons on weather and maps function not showing

### ISSUE THREAD

**Issue by emo44** [Xtraball/SiberianCMS#245]

**Comment by dbyzero** [comment]
I cannot reproduct bug, please contact support it's probably an issue with your installation.

![selection_355](https://cloud.githubusercontent.com/assets/2214094/24344544/4f614dee-12cc-11e7-9885-27d2e9ea9675.png)

**Comment by clifton11221** [comment]
He/she probably needed to clear cache in backoffice.  That works for me.
