### ISSUE TITLE
I can't edit any feature You cannot have multiple sessions to manage apps, so the session for this app is closed. This page is about to be reloaded.

### ISSUE THREAD

**Issue by momostafa** [Xtraball/SiberianCMS#252]
Hello,

I am having session issue when i login to the backend only when i go to features and try to edit any of the published features I am getting this message "You cannot have multiple sessions to manage apps, so the session for this app is closed. This page is about to be reloaded." and when i click on the pop messages the page keeps reloading forever 

I have Latest version SAE - v4.9.3
I checked var folder and its subfolders are all writable

Thank you for your help

**Comment by dbyzero** [comment]
Strange, this issue was fixed. Did your app_id is 1 in your database (table `application`). You you give me access to your siberiancms ?

**Comment by momostafa** [comment]
Hi, 
Thank you for your reply and very sorry for the delay, the app_id in table application is 1 but I found that admin_id in table application is 0 so changed to 1 logged out and logged in again and problem is the same the page keeps refreshing even without clicking on anything 
and  app_id in  table application_admin is 1 

I looked into the logs and found out the error is coming from /app/sae/modules/Application/controllers/SecurityController.php

only when I commented out this block then I was able to work normaly

           /* $this->getResponse()->clearBody();
            $this->getResponse()->clearHeaders();
            $this->getResponse()->setBody(Zend_Json::encode(array("refresh" => true)));
            $this->getResponse()->setHttpResponseCode(400);
            $this->getResponse()->sendResponse();*/

I am managing 5 Apps I noticed this issue only when i updated 2 of my apps to latest version  SAE - v4.9.3 the 3 other Apps are running SAE - v4.8.12.3 and they don't have this issue

I hope this helps

Thanks

**Comment by ananayamata** [comment]
Hi
i m facing same issue 
You cannot have multiple sessions to manage apps, so the session for this app is closed. This page is about to be reloaded.
i have updated the syberian cms to the latest version 4.11.0
can you help me in solving this pls?

**Comment by ananayamata** [comment]
http://app.srikrishan.com/admin/account/login

http://app.srikrishan.com/backoffice

**Comment by dbyzero** [comment]
We cannot reproduct, did you fix your issue ? I close anyway because it's a specific bug. You can contact contact@siberiancms.com to give your server access and support will investigate the issue.
