### ISSUE TITLE
Facebook event

### ISSUE THREAD

**Issue by wouter76** [Xtraball/SiberianCMS#255]
Hi,

When trying to implement the event module connected to Facebook Events we do not receive any data.
After debugging I detected that in the `Event_Model_Event` the `_parseFBAgenda` function requests the access_token from the Facebook graph api. That api returns a json, but in the function the response is handled as a single string. This json using as a string causes the graph api to return errors inteat of the data requested.

I sugest to change the functing and replace line 
`$access_token = str_replace('access_token=','',file_get_contents($url));`
with
`$arr = Zend_Json::decode(file_get_contents($url));
$access_token = $arr["access_token"];`

Cheers

**Comment by SiberianCMS** [comment]
Thanks that's, it for an unknown reason, Facebook changed the old API to return json unless of a query string. 
It's fixed in the coming 4.10.0-beta.1
