### ISSUE TITLE
Path of the on line APP

### ISSUE THREAD

**Issue by OscarLate** [Xtraball/SiberianCMS#256]
Hi,

I want see the code of my ON LINE (not offline ) app  ( if I'm not wrong is path + .html and js ) but I only found the images, becouse I want modify the returned of QR text depending on some parameters.
I was trying modify  /httpdocs/var/apps/browser/prod.js but didnt works

**Comment by dbyzero** [comment]
`prod.js` resulting all sources for browser. If you "rebuild manifest" in backoffice (button on dashboard) you regenrate prod.js sources and loose all your modifications.

I recommand to change your sources in appropriate JS files (var/apps/browser/js/**) and rebuild manifest.

But be aware that an update can erase your changes so keep a patch or a diff of your modification!

**Comment by dbyzero** [comment]
note: your need to be in developper mode to see rebuild manifest button.

**Comment by OscarLate** [comment]
Sorry for re-post but I put this in /httpdocs/var/apps/browser/js/controllers/codescan.js and when I open my Android App  continue showing "Scan result". What Am I doing wrong? When am I doing some modify in /httpdocs/var/apps/browser/ the changes are in real time?
```
                        //Dialog.confirm($translate.instant("Scan result"), barcodeData.text, buttons, "text-center").then(function(res) {
                         Dialog.confirm("TEST", barcodeData.text, buttons, "text-center").then(function(res) {
```
