### ISSUE TITLE
Inbox Module: Notifications Aren't Working

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#257]
The Notifications from the Inbox module are not working. The message is received but the Notification isn't received.

Regular Notifications are working fine.

**Comment by clifton11221** [comment]
FYI... I'm using MAE 4.9.3

**Comment by clifton11221** [comment]
This has been resolved.  Support advised me to delete the module then re-add it.  That worked.

**Comment by Spotcloudtk** [comment]
How did you delete the form? Do you say step by step?
