### ISSUE TITLE
Audio module tracks delete...

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#26]
Tracks is being deleted, but refresh the page is coming again. So not deleted.

![screenshot](https://cloud.githubusercontent.com/assets/8930862/15778924/e7b70062-29a1-11e6-93a8-ab6da0d65e07.png)

**Comment by alexyves** [comment]
Fixed in 4.1.6.

**Comment by karargaht** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/8930862/15867742/4ad64e8e-2ced-11e6-864b-c5435b498913.png)
don't clicks save, the problem is solved.

**Comment by SiberianCMS** [comment]
@karargaht it's solved in the 4.1.6 even when clicking save !
You must click save :) http://updates.siberiancms.com/release-notes/sae/4.1.6.html
