### ISSUE TITLE
Booking Feature

### ISSUE THREAD

**Issue by arthurkai** [Xtraball/SiberianCMS#260]
Hi Guys,

Booking feature still send a wrong time in email confirmation (7 hours difference). Time zone issue is still not resolved.
Tested on PE 4.9.3 setting for time zone asia Bangkok GMT+7
Also tested on PE 4.10.1 beta setting for time zone asia Bangkok GMT+7

Thanks

**Comment by Slicit** [comment]
Fixed in 4.11.7.
