### ISSUE TITLE
Folders module: No content or sub folders shown

### ISSUE THREAD

**Issue by grafixpress** [Xtraball/SiberianCMS#261]
Vers. 4.10.0 beta.1:
Some Folders dont show any content anymore. Affected are folders with RSS inside, or with subfolders with RSS or Radio module in it. This is both in app and webapp. This is crucial because it worked before update.

**Comment by grafixpress** [comment]
If the RSS module is in subfolders even disabling doesn´t help. The whole folder strukture is blocked - no content. 
Horrifying.

**Comment by SiberianCMS** [comment]
Duplicated.
Fixed in 4.10.0*
