### ISSUE TITLE
Internal linking - not possible to link to shop module

### ISSUE THREAD

**Issue by herobe** [Xtraball/SiberianCMS#263]
possible to link to loyalty card, promotions, and all other modules.. 
except to the Mcommerce module. 
Or is the data-state="cms-view"> not declared yet. 
if so what is the data-state for Mcommerce ?

**Comment by SiberianCMS** [comment]
MCommerce in-app links are not enabled yet.

We should add them in next updates.

And for now you have this state 
`mcommerce-category-list` along with the`value_id` associated with your mcommerce feature.

**Comment by herobe** [comment]
Thank you ! 
works like a charm ! perfect guys !

**Comment by Slicit** [comment]
closing as fixed!
