### ISSUE TITLE
Taxi Cab Module - Pin Point Should Not Be Used For Pick-up Address Because It's Inaccurate

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#266]
The Pin Point feature in the Taxi Cab module is very buggy and inaccurate.

When selecting their Pick-up Address (current location) in the app, it appears that the default selection is the Pin Point and alternatively, the app user can type in their Pick-up Address.  This should not be the case due to the inaccuracy of the Pin Point.  

In addition, since the Pin Point takes the focus, when the app user tries to type in their address, the app often tries to utilize the address of the Pin Point and it generates an error messages stating that the route to the destination can't be found... It's a whole back and forth trying to get the error message to go away (it keeps coming back).  It's very frustrating for the app user.

By default, the app user should type in their Pick-up Address (current location), and then the Pin Point should go to that location on the map.  This way the app user don't have to deal with their location coming-up incorrect and having to deal with an error message unnecessarily.

**Comment by PofMagicfingers** [comment]
Thanks for your suggestion. Anyway TaxiRide module is not included in SiberianCMS, therefore this should be in this repository. We copied it in our internal private repository.
