### ISSUE TITLE
Update to 4.10.1 : APK generation fails.

### ISSUE THREAD

**Issue by grafixpress** [Xtraball/SiberianCMS#268]
Generate APK fails after update to 4.10.1. 
My server had JAVA 1.8 installed before the update. 
I get this  error now in logfile:
Checking the license for package Android SDK Platform 25 in /home/domain/public_html/app4/var/apps/ionic/tools/android-sdk/licenses
Warning: License for package Android SDK Platform 25 not accepted.
FAILURE: Build failed with an exception.
I can see that /licenses doesn´t exist. It seems that SDK is not updated correctly during the update to vers. 4.10.1

**Comment by dbyzero** [comment]
You probably can't download last SDK. Do you have enought free space on your hard drive ?

**Comment by grafixpress** [comment]
Hello, I have got 82 GB of free disk space. What to do?

**Comment by SiberianCMS** [comment]
go inside `var/apps/ionic/tools`
delete the folder `android-sdk`
`rm -rf android-sdk`
then run 
`php -f sdk-updater.php`

Then you should be done.

**Comment by grafixpress** [comment]
In the meantime I tried to restart Android tools via system tasks. Should I have deleted the folder first?

**Comment by Slicit** [comment]
Closing issue.
