### ISSUE TITLE
Facebook login returns 404 error

### ISSUE THREAD

**Issue by wouter76** [Xtraball/SiberianCMS#27]
Hi,
When using the Facebook login in the angular view. Since migration the login doen't work anymore. Debugging a bit it turns out that the process of getting the Facebook response back is ok, but the registration post to the sae servers returns a 404 "not found" response. I know this from before as when a script/function is not recognized in the Zend include structure based on the requested url. But in this case that can't be because the login post method is working fine and the url for the script is the same.

Hope you can fix this soon because we didn't expect something which was working not to work ater the update and now a lot of clients can't login using their Facebook anymore.

Kind regards,
Wouter

**Comment by SiberianCMS** [comment]
We are fixing it as an emergency.
