### ISSUE TITLE
Module M-commerce: issue with dropdowns

### ISSUE THREAD

**Issue by grafixpress** [Xtraball/SiberianCMS#270]
Dropdowns in m-commerce (sizes etc.) don´t work in Html5.
I want to show more than 1 shop within an app, by linking to external shops installed on the same platform. All works fine except the dropdowns.
Same applies for forms by the way. Dropdowns not working in html5.

**Comment by LikoV2** [comment]
Hi,

Working fine on my end:

![image](https://user-images.githubusercontent.com/34651209/35572312-9feebd54-05d4-11e8-8232-bbb2a30e4f28.png)
