### ISSUE TITLE
How do I upgrade JAVA to 1.8 on the Siberiancms platform?

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#271]
How do I upgrade JAVA to 1.8 on the Siberiancms platform?

![image](https://cloud.githubusercontent.com/assets/25539714/25058816/f6cbbef8-2153-11e7-81ac-728eb7d9f27e.png)

**Comment by tecnologiaterabyte** [comment]
Its Very Simple:

````
Tip for updating Java to 1.8 via SSH (for non-hosted users):

```
CentOS/RedHat/Fedora:

yum install -y java-1.8.0-openjdk.x86_64 java-1.8.0-openjdk-devel.x86_64
```

Debian/Unbuntu:
apt-get install openjdk-8-jdk openjdk-8-jre`
```
Regards,

**Comment by ciadoreino** [comment]
I use hosting on Sentora

**Comment by tecnologiaterabyte** [comment]
You must ask your hosting the installation, which version of siberiancms you have (SAE / MAE / PAE)

Regards,

**Comment by valneysl** [comment]
hello guys I installed the java on the vps but does not recognize the installation, would anyone know how I can solve it, my server and vps hundreds 64b whm

Thank you very much in advance


![gggg](https://user-images.githubusercontent.com/40365319/102702440-6d5c3900-4241-11eb-944f-fe27c787236d.png)
