### ISSUE TITLE
IOS AUTO-PUBLISH (PEM CERTIFICATE NOT GENERATED)

### ISSUE THREAD

**Issue by glopr** [Xtraball/SiberianCMS#272]
PE - v4.9.3

I've published an app update using IOS Auto-Publish and I got the following message:
We have discovered one or more issues with your recent delivery for "App Name". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

""Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode 8 does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. ""

It is not supposed that Auto-Publish module auto create the PEM certificate on BackOffice?

**Comment by dbyzero** [comment]
Sorry for late answer.

Autopublish create a PEM certificat first time your app is build by our service. The PEM certificate is then upload to your siberian cms installation.

Can you open a ticket to support if there is no PEM linked to your app please ? We will force the generation of your PEM on a dedicated build.

Regards.
