### ISSUE TITLE
Module "Quiz" - No statistics

### ISSUE THREAD

**Issue by arttex** [Xtraball/SiberianCMS#275]
The problem of viewing the results of passing the quiz by users.
 There is only a link to the folder tmp!
![default](https://cloud.githubusercontent.com/assets/19585230/25315908/ce9633b4-2865-11e7-8305-7df32c028a58.jpg)

![default](https://cloud.githubusercontent.com/assets/19585230/25315876/318ba8b0-2865-11e7-9fdd-5f88a02b280a.jpg)

**Comment by dbyzero** [comment]
May be a specific issue with your serveur, do you have a valid support license ? MAE/PE ? If so, please open a ticket to support team.

**Comment by arttex** [comment]
PE. I opened it three weeks ago. Silence.

**Comment by Slicit** [comment]
Issue is fixed in latest quizz update, due to a download error.
