### ISSUE TITLE
Android app:  'SQLiteConnection object was leaked' warning

### ISSUE THREAD

**Issue by wouter76** [Xtraball/SiberianCMS#276]
hi,

When I have the latest build of the Android app (from pe version 4.10.3) in the Android studio I constantly have warnings about a database leak:
```
W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/com.google.android.gms/databases/metrics.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/com.google.android.gms/databases/help_responses.db.18' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/com.google.android.gms/databases/auto_complete_suggestions.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
```

As far as my knowledge goes this has something to do with the Google Cloud messaging plugin. Does somene expirence the same ond/or  know how to fix.

Cheers Wouter

**Comment by dbyzero** [comment]
We are not using directly SQLite on embed devices. It's GCM plugin that use it, we have a limited control on it.

**Comment by wouter76** [comment]
I undestand. But I report this because of it occured after the update from 4.9.x to 4.10.3 and I think in the update the google cloud messasing cordova plugin has been updated too (complete update of android library on the server as requested in the update description).
