### ISSUE TITLE
In app linking : add all modules

### ISSUE THREAD

**Issue by herobe** [Xtraball/SiberianCMS#279]
Not all modules can be linked to using the inapp linking feature. 
for ex. appointment and mcommerce. 
Now bypassing by applying namemodule-view 
but while linking to appointment locations are not loaded.

**Comment by dbyzero** [comment]
We are aware about this limitation, in app link have to be developed manually be feature. We are working on a better implementation of this feature. I cannot give you date yet.

**Comment by herobe** [comment]
no reason to close but to put it as 'pending release" or something more userfriendly. 
anyway, have a nice day ! :)

**Comment by dbyzero** [comment]
GitHub is not our main bug tracker, I keep the refactorization ticket open on the main one. I close this issue to have a better overview for developer community on knows issues.
