### ISSUE TITLE
Set meal: Layout problems...

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#28]
**Module:** Set meal. **Bug:** Layout 2 not working...Layout 1 and 3 working.

![setmeal](https://cloud.githubusercontent.com/assets/8930862/15850430/769dad84-2ca0-11e6-83e0-a0e0cc24930c.png)

**Comment by alexyves** [comment]
Fixed (I don't remember when but it' working)
![28-layout-2-set-meal](https://cloud.githubusercontent.com/assets/18324386/18406752/8562e810-7701-11e6-978b-4e6d3d98cf02.png)
