### ISSUE TITLE
Custom Page Module: Bug Inserting Images Into Text Blocks

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#299]
When using the custom page module, if you have multiple text blocks and insert images (inline with the text) into each text block, in order - as you create the text blocks, there isn't a problem.

However, if you have multiple blocks of texts, and attempt to insert images (inline with the text) in a text block **AFTER** the custom page was saved (or if you attempt to go to a text block and change the image, etc) the image layout for the inline image will be distorted or the image will disappear completely

**Comment by bluesnap-rock** [comment]
I concur.......same if you edit source in text box. Saves once. When you go back to edit no source appears.

**Comment by rivman** [comment]
Same. Scroll the page. It will display it.

**Comment by clifton11221** [comment]
The source appears/text appears when you scroll (or move the text block) but the image won't appear or fix.

**Comment by Slicit** [comment]
Fixed in 4.12.10
