### ISSUE TITLE
Newswall: Layout problems...

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#30]
**Module:** Newswall **Bug:** in Layout 3 last share does not seem. 

Layout 1, 2, 4 working.
![screenshot](https://cloud.githubusercontent.com/assets/8930862/15852613/5d311a5c-2caa-11e6-942d-88a5a580c49e.png)
![screenshot2](https://cloud.githubusercontent.com/assets/8930862/15852614/5f0a16b2-2caa-11e6-9473-81c3bbad0751.png)

**Comment by alexyves** [comment]
Fixed.
