### ISSUE TITLE
Errors Generating Application in Xcode 8.3.2

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#301]
Hello,

I started using Xcode 8.3.2 to generate PE 4.11.3 platform applications and when compiling several errors appear, it forms the attached image.
Does anyone know how to solve this?
![erro](https://cloud.githubusercontent.com/assets/25539714/26379094/d6654a5e-3fed-11e7-9552-8b35814fbb1b.jpeg)

**Comment by bluesnap-rock** [comment]
I believe these errors dont make a difference to compiling the APP, albeit annoying because it takes longer to compile/simulate/screenshot the app....but still...it wont stop you compiling and uploading the APP.

**Comment by ciadoreino** [comment]
The problem is that when I publish to Apple I receive the Rejection message due to performance problems and so I can not publish with acceptance on Apple.

**Comment by ciadoreino** [comment]
The problem is that when I publish to Apple I receive the Rejection message due to performance problems and so I can not publish with acceptance in Apple.

**Comment by theeugenegroup** [comment]
Try going back to version 8.2.1 of X-Code and recompiling

**Comment by ciadoreino** [comment]
How did I get back the version of Xcode?

**Comment by ciadoreino** [comment]
I compiled it in Xcode 8.2.1 and it continues with the same error as the image, and this error appears soon when the app asks for location authorization.
![sem titulo](https://cloud.githubusercontent.com/assets/25539714/26423772/4383e444-40a5-11e7-8f32-030daba43727.jpeg)

**Comment by theeugenegroup** [comment]
Did you download a fresh file from your Siberian or try to use the same one you had issues with previously?

**Comment by ciadoreino** [comment]
That's right, I downloaded the file again from Siberian and compiled, but it does not open.

**Comment by ciadoreino** [comment]
Can anyone help me with this problem? I am not able to test and publish the application after compiling in Xcode. I'm using Macbook Sierra 10 with Xcode 8.2.1

**Comment by dbyzero** [comment]
Sorry but it's hard to help you without reproduct issue. I can only recommand you to use our iOS autopublication service or try to contact siberian cms support.
