### ISSUE TITLE
Facebook events loading takes up to one minute

### ISSUE THREAD

**Issue by wouter76** [Xtraball/SiberianCMS#302]
Since updating to 4.11.3 calander items from facebook take up to 1 minute before loading into the app. The issue is due to a slow resonse from Facbook graph while itterating over the events. I am not well educated in the graph api but it looks to me that it could be possible to load the required fields for the list view can be requested at the events requests.

I hope this can be fixed.

**Comment by LikoV2** [comment]
API Changed, it's no longer supported.
