### ISSUE TITLE
Simple module

### ISSUE THREAD

**Issue by Chayuthh** [Xtraball/SiberianCMS#309]
Can you give me an example of the simple(code) module to show a weather using the API from Yahoo. Thank you

**Comment by clifton11221** [comment]
Did you see this already:

https://developers.siberiancms.com/module/

**Comment by Chayuthh** [comment]
@clifton11221 I see it already but I'm confused that how to start.

**Comment by dbyzero** [comment]
I close your issue because it's just a question. But you still can speak on this ticket.
