### ISSUE TITLE
QR Coupons module: Layout and pictures...

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#31]
**Module:** QR Coupons, **Bugs:** the pictures do not appear.  in Layout 3 last share does not seem.

![imagesno](https://cloud.githubusercontent.com/assets/8930862/15853125/78fa9e82-2cac-11e6-9d1e-4675926164d6.png)

![lay](https://cloud.githubusercontent.com/assets/8930862/15853131/7d578af8-2cac-11e6-9181-4334b8ddfe6e.png)

![lay2](https://cloud.githubusercontent.com/assets/8930862/15853130/7d3948c2-2cac-11e6-93ef-8b243009a69a.png)

**Comment by SiberianCMS** [comment]
Fixed & Planned in 4.2.0
