### ISSUE TITLE
utf8 encoding problem on text field in layout options

### ISSUE THREAD

**Issue by lsmod** [Xtraball/SiberianCMS#311]
addSimpleText encode poorly (when used in layout options form )
example:
êtes vous là? becomes u00eates vous lu00e0?

**Comment by lsmod** [comment]
When making a get on mysibdomain.com/overview/front/mobile/loadv2/sid/rehjg6smjho6lo94qsjdnvfmu3/
we can see that slide2Text field has been not correctly espaped at some point
"layout": {
            "layout_id": "l30",
            "layout_code": "layout_baguera_13",
            "layout_options": {
                "slide2Text": "u0420u043eu0441u0441u0438u0439u0441u043au0430u044f",

"u0420u043eu0441u0441u0438u0439u0441u043au0430u044f" should be
"\u0420\u043e\u0441\u0441\u0438\u0439\u0441\u043a\u0430\u044f"

**Comment by lsmod** [comment]
In database everything looks fine (table: application; column: layout_options)
"slide2Text": "\u0420\u043e\u0441\u0441\u0438\u0439\u0441\u043a\u0430\u044f",

**Comment by lsmod** [comment]
$application->getLayoutOptions()
return slide2Text option without \

**Comment by lsmod** [comment]
if I add backslash into database everything works fine:
table: application; column: layout_options I replaced this:
"slide2Text": "\u0420\u043e\u0441\u0441\u0438\u0439\u0441\u043a\u0430\u044f"
by this:
"slide2Text" "\\u0420\\u043e\\u0441\\u0441\\u0438\\u044f" 

So that's an escaping problem on backslash probably use addsplash() before saving then json_encode will give me a \u0420 and not u0420. 
I'm not an zend or a siberian expert so I wont continue digging on the matter but I hope you know enough so it could be fixed quickly

**Comment by Slicit** [comment]
Merged in develop, will be released in 4.12.0
