### ISSUE TITLE
ADD AdMob Mediation

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/SiberianCMS#313]
Not sure if its already included, but would be nice to have AdMob Mediation SDK included allowing serving adds from multiple networks?

https://support.google.com/admob/answer/3063564?hl=en-GB&ref_topic=7383089

**Comment by SiberianCMS** [comment]
AdMob mediation is to take with lot of care as to "what mediation to choose" embedding all mediations can increase app size way too much, as the actual goal we are researching os to decrease app sizes ... I'm not sure it's a good idea.

**Comment by bluesnap-rock** [comment]
Maybe just MoPub....their flexibilty of adding in house advetising is much better and more reliable than AdMob. Or maybe adding the MoPub SDK as a seperate choice to AdMob. Just an idea because I have had many tell me they find AdMob in house advertising to be very complicated for users due to the cpm.

**Comment by Slicit** [comment]
Closing, as this won't be added in a close future.
