### ISSUE TITLE
Custom module edit image by text editor not working 

### ISSUE THREAD

**Issue by dssjitendra** [Xtraball/SiberianCMS#318]
When we used more then 1 editor in the custom module and then edit the 1st text editor image its now edit and first remove the previous images also. 
![screenshot_2](https://user-images.githubusercontent.com/15323392/26969099-32803f9c-4d22-11e7-8f63-6aecfb97e701.png)

**Comment by clifton11221** [comment]
This issue is confirmed in this Issue here:

https://github.com/Xtraball/SiberianCMS/issues/299

**Comment by Slicit** [comment]
Closing duplicate #299
