### ISSUE TITLE
Facebook content not loading

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#32]
**Module:** Facebook, **Bug**: content not loading.

![aaaa](https://cloud.githubusercontent.com/assets/8930862/15855904/f3e4f738-2cba-11e6-9040-b8d152191718.png)

**Comment by thehosting4you** [comment]
Hey,
Here no problems.
Sincerely André

![face-goed](https://cloud.githubusercontent.com/assets/8598623/16132633/4e653a00-3414-11e6-98a9-5d7a684faff2.PNG)

**Comment by karargaht** [comment]
I'm trying. Content not loading.

**Comment by thehosting4you** [comment]
Hey,
Can you show me the facebook page id to me for test to my systeem.
M.v.g.

**Comment by SiberianCMS** [comment]
I've tried the galatasaray page too, there is no problem.

I am closing the issue.
