### ISSUE TITLE
Home Page Slider not displaying/positioning - Beta 4.12

### ISSUE THREAD

**Issue by theeugenegroup** [Xtraball/SiberianCMS#326]
Home Page Slider does not display in overview but does in preview app.

Positioning of images does not change

**Comment by Slicit** [comment]
Have you tried to change position top to 0 ?

**Comment by theeugenegroup** [comment]
Yes,
<img width="1952" alt="screen shot 2017-06-27 at 8 31 32 am" src="https://user-images.githubusercontent.com/8466469/27593013-4bd04c04-5b13-11e7-9c51-7c029b944470.png">

![img_0914](https://user-images.githubusercontent.com/8466469/27593074-73831ff6-5b13-11e7-92f9-79c176f58e71.PNG)

**Comment by Slicit** [comment]
Found the issue, thanks it's due to the Table not updating, so opacity stick to 0, will be fixed in beta.2 (or stable)
