### ISSUE TITLE
Tour will not launch - Beta

### ISSUE THREAD

**Issue by theeugenegroup** [Xtraball/SiberianCMS#327]
Tour Editing mode launches a new editor session but does not open up to create a tour.

**Comment by savsani** [comment]
Goto Manage section from backoffice then goto users oage here you have to give access for manage tour for particular user, now goto appearance and tour, click on editing mode button a new window will open and here you will see manage tour option in navigation menu

**Comment by theeugenegroup** [comment]
I am signed in as admin, the option in roles for the tour does not appear. 
The I click on the tour option it does launch a new session but it is just a normal session.

**Comment by Slicit** [comment]
Manage > Users > User > Edit your user, and allow Tour Edit

**Comment by Slicit** [comment]
It's fixed, will be either in 4.12.0-beta.2 or 4.12.0 stable. same for #329
