### ISSUE TITLE
letsencrypt

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/SiberianCMS#328]
not sure if this is correct, but its happening for me : -

the cron for the lets encrypt runs consistently, if siberiancms is running on a sub domain (like mine) and you have a separate cert for the main domain, lets encrypt wont let you renew the cert as per their rate limit

There's a rate limit of 5 certificates per domain (TLD + 1, so subdomains count too) per 7 days in place.

Error form server side
Let's Encrypt SSL certificate installation failed: Invalid response from https://acme-v01.api.letsencrypt.org/acme/new-cert: Error creating new cert :: too many certificates already issued for exact set of domains

Also
When manually renewing / uploading cert from Siberian backoffice - I get two email errors from the server

**Error 1**
Template_Exception: nginx: [emerg] BIO_new_file("/usr/local/psa/var/certificates/cert-K7Emqt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/usr/local/psa/var/certificates/cert-K7Emqt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed

file: /usr/local/psa/admin/plib/Template/Writer/Webserver/Abstract.php
line: 75
code: 0

**Error 2**
Template_Exception: Syntax error on line 108 of /etc/httpd/conf/plesk.conf.d/server.conf:
SSLCertificateFile: file '/usr/local/psa/var/certificates/cert-K7Emqt' does not exist or is empty

file: /usr/local/psa/admin/plib/Template/Writer/Webserver/Abstract.php
line: 75
code: 0

However Siberian renews successfully and the cert is renewed and available via Siberian

**Comment by Slicit** [comment]
First check you have the latest Siberian version.
Then if you hit the rate limit, don't touch ssl for at least seven days.
In the latests updates we added a security to avoid reaching the rate limits, it seems the certificate was badly uploaded to Plesk we will check that thanks.
