### ISSUE TITLE
Mcommerce dont sending email conformation

### ISSUE THREAD

**Issue by amjadhadi** [Xtraball/SiberianCMS#330]
Mcommerce dont sending email conformation for both side App Admin and Clint's . Delivery not showing in app also

**Comment by Slicit** [comment]
Can you check your SMTP settings (if there is) and check the SPAM inbox

**Comment by amjadhadi** [comment]
I used sparkpostmail and everythings is ok .. But still there is no conformation email

**Comment by Slicit** [comment]
Does the store main e-mail domain part is allowed to send e-mails from `sparkpostmail ` ?

**Comment by amjadhadi** [comment]
No they are using webmail under their website domain info@domain.com
