### ISSUE TITLE
News Wall - Auto Refresh Cycle 

### ISSUE THREAD

**Issue by champier** [Xtraball/SiberianCMS#331]
PE - v4.11.7

Hi Everyone, 

I don't know if its only me or everybody issue...

when i use News Wall the  browser enter on a cycle of auto refresh....
And freezes the browser...
I saw the issue on many devices :( ...

watch the video: https://www.facebook.com/claude.champier/videos/10211105580454346/

**Comment by Slicit** [comment]
Can you please specify what version you are using

**Comment by champier** [comment]
PE - v4.11.7

**Comment by Slicit** [comment]
Wait for 4.12.0, then re-open if the issue is still relevant, thanks for the feedback.

**Comment by champier** [comment]
Oky, thanks .... do you have any date ?
