### ISSUE TITLE
Can not login to users 

### ISSUE THREAD

**Issue by amjadhadi** [Xtraball/SiberianCMS#332]
Hello 
in PE - v4.12.0-beta.1 I cant login to users from backoffice - mange> users > users

**Comment by Slicit** [comment]
Tested in 4.12.0-beta.1, can you try to clear your cache and retry ?

**Comment by amjadhadi** [comment]
I did also I checked in two different pc with many browsers but I got same thing

**Comment by Slicit** [comment]
It's fixed, will be either in 4.12.0-beta.2 or 4.12.0 stable.

Thank you @amjadhadi
