### ISSUE TITLE
Taxi Module Translate

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#334]
![screenshot](https://user-images.githubusercontent.com/8930862/27761068-265673ec-5e5e-11e7-903a-00789d4cc74a.png)

"The address you're looking for does not exist."

![screenshot2](https://user-images.githubusercontent.com/8930862/27761101-6c8aa676-5e5e-11e7-94e2-00763c3da51e.png)

"CREATE VEHICLE TYPE"

Can not be translated.

**Comment by Slicit** [comment]
Same here.

You can get the support directly via e-mail on contact@siberiancms.com 
Thanks ;)
