### ISSUE TITLE
Error generating APK

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#336]
When I try to generate the APK in Android Studio this message appears and does not generate the APK

Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/zzc;

**Comment by ciadoreino** [comment]
I'm using PE 4.11.7

**Comment by ciadoreino** [comment]
i´m using JAVA version 1.8.0_131,

**Comment by gonzoradio** [comment]
Having same issue using SAE 4.11.7

**Comment by gonzoradio** [comment]
I managed to solve this by not installing the latest updates to Android Studio.
I've gone back to version 2.3.1 and the apk has built and installed on a test device without issue. (2 warnings regarding Warning:(5) warning: string 'google_app_id' marked untranslatable but exists in locale 'en')
Will submit to Google Play now and check back in with the results.

**Comment by gonzoradio** [comment]
Just to confirm, the app was accepted by play store, no issues found so far (other than you have to change the app code to centre the admob banners, which is always the case)

**Comment by ciadoreino** [comment]
Thank you very much!!! I went back to version 2.3.1 of Android Studio and resolved.
