### ISSUE TITLE
News Wall Dates are wrong

### ISSUE THREAD

**Issue by theeugenegroup** [Xtraball/SiberianCMS#337]
Just added an item to the News Wall feature and it shows that it was posted 118 days ago even though I just posted it
<img width="1836" alt="screen shot 2017-07-03 at 6 27 31 am" src="https://user-images.githubusercontent.com/8466469/27792870-f11cb810-5fb8-11e7-84fa-bb42c952ed5f.png">

**Comment by Slicit** [comment]
Can you try in 4.12.0-beta.1 please, if fixed, just wait for stable then.

**Comment by theeugenegroup** [comment]
It's is the same in 4.12.0 beta, although a new post from today shows it was posted 88 days ago.

**Comment by Slicit** [comment]
It seems you are using `en_GB`, but there is an issue with the date picker being en_GB and behind the server is taking the date for a `en` and invert month/day that's why the 188 days and 88 days ....

Will try to fix the issue asap!

**Comment by Slicit** [comment]
Issue fixed in 4.12.14, scheduled for tomorrow.
