### ISSUE TITLE
Chat push notification times

### ISSUE THREAD

**Issue by theeugenegroup** [Xtraball/SiberianCMS#338]
The Push message is better but the time is still wrong.

My test message was sent at 5:42 MDT from my devices but it shows as 4:42 on my device and the CMS shows it was created 2 hours after
<img width="1244" alt="screen shot 2017-07-03 at 5 46 00 am" src="https://user-images.githubusercontent.com/8466469/27792950-454f132e-5fb9-11e7-849b-0bf31a998dc4.png">
 it was sent.

**Comment by PofMagicfingers** [comment]
Date is server time not device time. Also : the real issue is that you're seeing chat push inside the list, they should not be visible in any list on editor side.

By the way, this is the SiberianCMS github. This is not a support channel for paid module. Stop opening issues here, thanks !
