### ISSUE TITLE
"Delivery" page not shown and blank

### ISSUE THREAD

**Issue by Breewather** [Xtraball/SiberianCMS#34]
Hello ! I experienced a strange issue, I hope someone could help me.

 In the "e-commerce" module, the "delivery" page is blank on some phones, impossible to  go further.

![unknown-1](https://cloud.githubusercontent.com/assets/19819937/15909912/eec07e3a-2dc8-11e6-84cb-6ed77a8444a6.jpeg)
![unknown](https://cloud.githubusercontent.com/assets/19819937/15909913/eef7aa40-2dc8-11e6-85e4-77b8ead149c0.jpeg)
 Any ideas ? Thank you in advance

**Comment by louisaas** [comment]
It will apeer blank when the user is out of store delivery range ! I think siberian need put a message to tell the users that!

**Comment by SiberianCMS** [comment]
Postponed.
