### ISSUE TITLE
QR Code from Promote Tab

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/SiberianCMS#340]
Hi Guys - using Version 4.11.7

I see it doesn't throw the error it was prior to update.

However, the qrcode.png it now downloads via the link is a blank corrupted file.

The only way of getting it is right click/save image as.

**Comment by Slicit** [comment]
Bug confirmed.

**Comment by Slicit** [comment]
The fix will be released in 4.12.0 thank you.
