### ISSUE TITLE
Facebook login option not hided

### ISSUE THREAD

**Issue by wouter76** [Xtraball/SiberianCMS#341]
Hi,

In the [customer login.html](https://github.com/Xtraball/SiberianCMS/blob/develop/var/apps/browser/templates/customer/account/l1/login.html) the Facebook login option is showed even when in the $scope the `$scope.can_connect_with_facebook` is set to `false`. I discovered the problem is due to the check in the login.html on `can_connect_with_facebook`  is missing. I suggest a quick fix to this in the next update round like this:

login.html line 20:
`<div class="item item-text-wrap item-icon-left item-custom" ng-click="loginWithFacebook()" ng-if="!is_logged_in && can_connect_with_facebook ">`

Hope this can be fixed in the next update.

Kind regards
Wouter

**Comment by Slicit** [comment]
I'll close the issue as this is already fixed in 4.12.0-beta.1 if after the 4.12.0 stable released the issue still applies please re-open.
