### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by tondanovak** [Xtraball/SiberianCMS#344]
Hi, 
just tested 4.12.0 beta1 and found there are some translation, which were before OK, missing.
For example BACK button, MY ACCOUNT (header in my account feature), NO COMMENTS FOR NOW (news feature), etc...

**Comment by karargaht** [comment]
same...

**Comment by karargaht** [comment]
![aaaa](https://user-images.githubusercontent.com/8930862/28469485-0c77c6a6-6e3f-11e7-941e-530cc6cc4df5.png)

v: 4.12.2
