### ISSUE TITLE
Places feature - map view without links

### ISSUE THREAD

**Issue by tondanovak** [Xtraball/SiberianCMS#346]
![img_6386](https://user-images.githubusercontent.com/30071348/28061724-cb2bd162-662b-11e7-9049-c589ed76413f.PNG)
In PLACES feature there are missing links to particular Place in MAP VIEW (when tap on the place and tooltip is opened).
It was OK before update to 4.12.0. beta1

**Comment by Slicit** [comment]
These are links, but not "highlighted" you can click on popup's, I'll consider adding an icon of something like.
