### ISSUE TITLE
Login via Facebook

### ISSUE THREAD

**Issue by tondanovak** [Xtraball/SiberianCMS#347]
Hi,
login via Facebook doesnt work in 4.12.0. beta1.
The button is inactive for me...

**Comment by Slicit** [comment]
What do you mean by `inactive` ?

**Comment by tondanovak** [comment]
That it doesnt seems like button - it doesn do anything when tap on it
Seems like pure text...

**Comment by Slicit** [comment]
Bug confirmed & Fixed for next 4.12 update
