### ISSUE TITLE
error data

### ISSUE THREAD

**Issue by obaviet** [Xtraball/SiberianCMS#348]
i  can not connect databe and error: Mixed Content: The page at 'https://domain.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://domain.com/installer/installation_database/check'. This request has been blocked; the content must be served over HTTPS.

**Comment by Slicit** [comment]
Install from HTTP ;)

**Comment by obaviet** [comment]
yes, but  It only fulfills 66% of installation and stops

**Comment by Slicit** [comment]
At what step does the process stops ?

**Comment by obaviet** [comment]
Installation stuck on 66% Data : importer.
  
I deleted and reinstalled many times

**Comment by Neustradamus** [comment]
linked to https://github.com/Xtraball/SiberianCMS/issues/393

**Comment by Slicit** [comment]
It's fixed, some files were not deleted from the github as they were in MAE/PE
You can pull and install again ;)
