### ISSUE TITLE
Buttons overlapping - FAcebook Import/ Import&Export

### ISSUE THREAD

**Issue by tondanovak** [Xtraball/SiberianCMS#351]
Hi, there is overlapping of buttons and text in Editor
"FAcebook import" , "Import/Export" and headert text "you selected pages" are overlaped together and it is not very nice... AND IT IS VERY CONFUSING WHAT THAT BUTTONS ARE MADE FOR
Should be fine to play with CSS little bit:-)

**Comment by Slicit** [comment]
The `import & export` button is shown only in development, and not relevant here :)

**Comment by tondanovak** [comment]
ok, thanks:-)
