### ISSUE TITLE
Weird behavior while browsing app

### ISSUE THREAD

**Issue by tondanovak** [Xtraball/SiberianCMS#352]
Hi, is this normal behavior? 
https://www.useloom.com/share/2e1eccff7cbe4f68a3a75621ba46608a
As it wasnt so weird in versions before 4.12.0 beta1?
Menu or feature is moved partially to side and overlap with another feature... This is really not nice behaviour:-(
Is it possible to do someting with this? As said in previous version was it really really better...

**Comment by Slicit** [comment]
It's due to the new the backgrounds are handled to allow for full transparency (even the header bar)
However i'll check if we can do something about it.

**Comment by Slicit** [comment]
Fixed ;)
