### ISSUE TITLE
PLACES feature - slider with pictures does not work

### ISSUE THREAD

**Issue by tondanovak** [Xtraball/SiberianCMS#354]
Hi,
in PLACES feature, when is used Slider - it not work (not posible to swipe pictures on place detail... And the last picture is displeyed...)
Only when tap on picture (slider) - it open picture detail - and only here is possible to swipe the pictures (but it is the last picture, so I only can swipe back)

PE 4.12.0 beta1

**Comment by Slicit** [comment]
Seems it's working in latests builds, let retry when 4.12.0 is released and re-open if still relevant.

https://ufile.io/oox9w
