### ISSUE TITLE
Newswall - Auto Refresh cycle 

### ISSUE THREAD

**Issue by champier** [Xtraball/SiberianCMS#357]
PE - v4.12.0

Hi Everyone,I don't know if its only me or everybody issue...when i use News Wall the browser enter on a cycle of auto refresh....And freezes the browser...I saw the issue on many devices :( ...

watch the video: https://www.facebook.com/claude.champier/videos/10211105580454346/
--

**Comment by movensoft** [comment]
After update SAE - v4.12.1 i found that in Newswall Layout 2 doesn't load all content, load only first.
When i change it to Layout 1,3,4 work fine. 
![capture](https://user-images.githubusercontent.com/24564525/28457173-c50b7276-6e0d-11e7-9059-f4987ba82834.JPG)
![capture1](https://user-images.githubusercontent.com/24564525/28457174-c5105200-6e0d-11e7-9f54-8773983832d9.JPG)

**Comment by champier** [comment]
@movensoft your issue its solve :) . just UPDATE

**Comment by champier** [comment]
The cycle of auto refresh  continues  :(

**Comment by movensoft** [comment]
@champier , today i update to 4.12.3 and for now its working normally.
