### ISSUE TITLE
What is the best version of OS X and Xcode?

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#358]
What to improve version of OS X and better version of XCode to generate the Siberian APP?

**Comment by ciadoreino** [comment]
I am using a Mac Pro with OS X Sierra 10.12 and with XCode 8.3.1, and when compiling is generating many errors where it can not be published. I would like to know which version of Mac OS X and Xcode generates the application correctly.

**Comment by Slicit** [comment]
When compiling with Xcode, when asking to convert to swift syntax, always ask later ;)
