### ISSUE TITLE
Version 4.12

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/SiberianCMS#359]
Source code pages are taking way to long to load in new 4.12 APP version?

**Comment by Slicit** [comment]
In overall apps performs better and slightly faster, at least in all the tests we made during development, beta, and after release.

**Comment by bluesnap-rock** [comment]
Hi Slicit
Please see how slow this APP is running

https://www.dropbox.com/s/j8gis3qhuf8hst6/screen-recording_20170720-105446_1.mp4?dl=0

Especially the source code view (BOOK) wasnt like this before.

Thanks

**Comment by clifton11221** [comment]
I agree... I'm specifically referring to the Places feature. I checked with a couple of apps.  It's really, really, slow.

**Comment by Slicit** [comment]
Places loading should improve in the next updates starting from 4.12.13, we removed some payloads to reduce overall page size.
