### ISSUE TITLE
Prestashop

### ISSUE THREAD

**Issue by glopr** [Xtraball/SiberianCMS#36]
Prestashop feature isn't working. When you setup a prestashop store, it only show the standard store website.

**Comment by SiberianCMS** [comment]
This is not a bug, Prestashop is an "alias" for the WebLink feature with the Prestashop icon.

Same for Magento, Woocommerce, Volusion & Shopify.

**Comment by Hyperians** [comment]
but the links are not showing in app main screen , how to make it show
