### ISSUE TITLE
unable to adjust quantity in Commerce feature

### ISSUE THREAD

**Issue by theeugenegroup** [Xtraball/SiberianCMS#360]
Quantities cannot be adjusted, increase in the Commerce feature

PE 4.12.1

**Comment by euroonesistemi** [comment]
Yes i test same problem on 4.12.1. MAE.
Unable to increment qty on making order. BUG.

**Comment by Slicit** [comment]
It's partially fixed in 4.12.5 we are checking to fix it once for all.
