### ISSUE TITLE
My Account feature showing always

### ISSUE THREAD

**Issue by rogeroffer** [Xtraball/SiberianCMS#361]
My account feature in 4.12.1 is showing always even if is not used by any feature

**Comment by Slicit** [comment]
Are you using the "Push feature ?"

**Comment by rogeroffer** [comment]
No push

2017-07-21 12:12 GMT+03:00 Alex-Yves CREPIN <notifications@github.com>:

**Comment by Slicit** [comment]
Solved in 4.12.6!
