### ISSUE TITLE
Global Push Notifications

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#362]
"No message sent, there is no available applications."

The app is on store publication. (Google Play)

![222](https://user-images.githubusercontent.com/8930862/28456960-de5d8bb6-6e0c-11e7-8d83-2947efe1193d.png)

V: 12.1 PE

**Comment by Slicit** [comment]
Does the application is in "published" in the backoffice ? it must be in "published state"

**Comment by karargaht** [comment]
Published. Back Office / Settings / Push Notifications / Global Push.

This way I can send you a notification. However, the user is not being sent with an input.

**Comment by Slicit** [comment]
The user account can send Push only to the Apps that belongs to him

**Comment by karargaht** [comment]
I already talk about my own account. In short, does this normally work properly? Is not that a bug?
The problem is my system too? I'm trying to understand her.

**Comment by wouter76** [comment]
I see this is a bug. the problem is that the selected app is atted to a not excisting field holding the id of `checked`. Serverside this results in non apps to send the app to. Hope this is fexed soon by the dev team.

**Comment by Slicit** [comment]
The fix is scheduled for 4.12.10 thanks
