### ISSUE TITLE
White Label 12.1

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#363]
CNAME recording was done.

The domain is not registered.

![11](https://user-images.githubusercontent.com/8930862/28456992-fc7953be-6e0c-11e7-9113-88811e50ae10.png)

**Comment by Slicit** [comment]
These two fields are required from 4.12 you can input whatever package_name/bundle_id base you want it will apply for all new created apps.

**Comment by Slicit** [comment]
Solved in 4.12.6!
