### ISSUE TITLE
Module Update

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/SiberianCMS#364]
When installing a new module or update. Module page just stays on spinner....?? Doesnt auto refresh when installed.

**Comment by karargaht** [comment]
I solved this problem by reinstalling the entire site. I wiped everything and got it install.

I guess it conflicts with the previous files.

**Comment by bluesnap-rock** [comment]
Havent really got the option reinstalling. Not sure if I can do that. Siberian Team have any ideas?

**Comment by bluesnap-rock** [comment]
This could also have something to do with  my APPS running slow?

**Comment by karargaht** [comment]
My website is 2 years old. The database is too big. 
We can not completely erase the apps. This is a database problem.
The changing file structure may also be causing problems.

**Comment by bluesnap-rock** [comment]
I rolled back to 4.11.7 it was way to slow loading source code pages and a lot of my APPs have source code. Maybe this is something to do with specific servers?

**Comment by Slicit** [comment]
In most case, apps are faster with 4.12+ 
Maybe your server is mis-configured or something like
Also you can increase PHP/CGI/FPM/Apache timeout to 90 seconds at least, this can help for updates/rebuild manifest

**Comment by bluesnap-rock** [comment]
Must be server issue. As soon as I rolled back APPs went so much faster. Especially source code. In 4.12x source code was way way way too slow. Plus couldnt deactivate a feature so was too buggy for current APPS.

**Comment by Slicit** [comment]
Well if you want to go stable, you can always have your prod/dev servers, and keep your prod server 4-5 versions away, test on dev, and when it's ok for you, move production, it's better than rushing all the updates as they are released, we do lot of tests for stable release with beta and more, but can't catch everything, so big updates are always likely to have issues in the two first weeks after the release.
Just advise :)

**Comment by Slicit** [comment]
Closing!
