### ISSUE TITLE
Chatroom module

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#366]
There is no problem when you log into the application. However, when you log in and send a message, the chat history does not appear. Because the page does not slip up.

You can install the app for the first time and look at the chat history.But you can not see the chat history when you write something to talk about it.

**Comment by karargaht** [comment]
Chat v:1.4.1
Siberian v:12.2

**Comment by tecnologiaterabyte** [comment]
Update Real Chat v. 1.4.3,

Regards

**Comment by karargaht** [comment]
Update, the problem continues.

The screen does not scroll up to see previous comments.

**Comment by PofMagicfingers** [comment]
Please open a support ticket, here is not the right place as Chatroom is a paid module. See : https://github.com/Xtraball/SiberianCMS/issues/356#issuecomment-315691209
