### ISSUE TITLE
Editor Create?

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#367]
![screenshot](https://user-images.githubusercontent.com/8930862/28491955-664dd738-6f02-11e7-80ff-88691cf38aad.png)

Editor and Create words are written in the same place.
Normally both are used in different places.

Words that are both translated separately.

v: 4.12.2

**Comment by Slicit** [comment]
Issue is confirmed.
Fix is scheduled for 4.12.3 tomorrow.

Thanks.
