### ISSUE TITLE
Lack of translation

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#370]
![33333](https://user-images.githubusercontent.com/8930862/28565365-b4dadea8-7134-11e7-88c7-4ed9f466b8b1.png)

NEWS WALL

![newsswall](https://user-images.githubusercontent.com/8930862/28544639-99990bdc-70cc-11e7-8a62-0094f5cf5c9e.png)

PRIVACY

![8888](https://user-images.githubusercontent.com/8930862/28544645-9e97d0be-70cc-11e7-929f-d3c9188241e4.png)

WHITE LABEL

![kkkk](https://user-images.githubusercontent.com/8930862/28544535-36bbbda2-70cc-11e7-8c76-5a93901fa290.png)

FROM

![6666](https://user-images.githubusercontent.com/8930862/28544220-259275ee-70cb-11e7-9cdc-d07ddfa7d4e9.png)

PUSH

![44444](https://user-images.githubusercontent.com/8930862/28544221-2598ec94-70cb-11e7-8dbd-75440ba1e6c8.png)

Forgot your password 

![111](https://user-images.githubusercontent.com/8930862/28544222-25992452-70cb-11e7-8193-e6d7ea2cbaaa.png)

CHAT

![3333](https://user-images.githubusercontent.com/8930862/28544223-259d6558-70cb-11e7-862d-808d7b4373f8.png)

PUSH

![555](https://user-images.githubusercontent.com/8930862/28544224-25a09b9c-70cb-11e7-9a19-5a430d85c035.png)

**Comment by Slicit** [comment]
These missing translations have been added in 4.12.5 and will be released today, please open a new ticket if you find new missing translations
