### ISSUE TITLE
Header Links / Easy Appointments Module

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#373]
Ever since upgrading to MAE v4.12 when I go to Easy Appointments, the header links are missing ("Back" link, etc).  I checked with the dev support of the Easy Appointments module and they stated its a Siberian issue. I have to agree with them because this wasn't an issue until utilizing version 4.12.

I'm currently using v4.12.4 and the issue is still there.

The problem only occurs with new apps that I add Easy Appointments to...  The old apps that utilized the module before I upgraded to v4.12 are fine.

**See below... The "Back" link in the header is missing.**

![appointments](https://user-images.githubusercontent.com/21089972/28579619-242a403c-712b-11e7-8969-545fcb66d28d.png)

**Comment by Slicit** [comment]
We sent the fix the module provider, there should be an update by today or tomorrow, when you have issues with paid modules you can open tickets directly on their support platforms or via e-mail.

**Comment by clifton11221** [comment]
This issue is now fixed with Easy Appointments version 1.2.1.

**Comment by Slicit** [comment]
Closing!
