### ISSUE TITLE
Chatroom frame

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#374]
![screenshot_20170726-010937](https://user-images.githubusercontent.com/8930862/28596075-893e7280-719f-11e7-8bca-1f5aa176010e.png)
Some pictures do not fit in the frame.

Also, the screen does not scroll.

1.4.3 v

**Comment by bluesnap-rock** [comment]
Yep happens on all my pics as well. Android.

**Comment by Slicit** [comment]
This will be fixed with next chatrooms update.

**Comment by Slicit** [comment]
Solved in the latest chatrooms update, you'll find it in your account!
