### ISSUE TITLE
Lack of translation - 2

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#375]
FAN WALL

![screenshot](https://user-images.githubusercontent.com/8930862/28616780-b7b88210-7206-11e7-9b8e-276444952fdf.png)

https://XXXX.com/customer/application/list

![5555](https://user-images.githubusercontent.com/8930862/28617055-91a951d4-7207-11e7-9837-8649ae2f6d04.png)

Analytcs

![4444](https://user-images.githubusercontent.com/8930862/28617072-9ce8b5da-7207-11e7-900f-89d840c18c2a.png)

SCSS ON/OFF

![222](https://user-images.githubusercontent.com/8930862/28617085-a685761e-7207-11e7-8e65-5b2ebccc8bbc.png)

CUSTOM PAGE

![nnn](https://user-images.githubusercontent.com/8930862/28617213-33e17b0c-7208-11e7-9d51-a3d2d62ccb70.png)

LINKS

![44654654](https://user-images.githubusercontent.com/8930862/28617235-48040bfe-7208-11e7-8ef7-5e37cee7038a.png)

NEWS WALL

![newsss](https://user-images.githubusercontent.com/8930862/28617340-a572efc6-7208-11e7-8116-29093f3880fb.png)

IN APP MESSAGES

![nnnnnncvc](https://user-images.githubusercontent.com/8930862/28617395-d3df1ff6-7208-11e7-85c6-639f4bf6e72f.png)

WORK

![workkk](https://user-images.githubusercontent.com/8930862/28617432-fc8876f0-7208-11e7-828e-96b0338ed577.png)

CATALOG - CATEGORY

![catalog](https://user-images.githubusercontent.com/8930862/28617487-1f27d980-7209-11e7-97f8-0f5eea8733c3.png)

LOCK

![lock](https://user-images.githubusercontent.com/8930862/28617539-583b82ee-7209-11e7-995d-58c5452f2cc0.png)

COMMERCE

![commerce](https://user-images.githubusercontent.com/8930862/28617677-fb14958c-7209-11e7-8415-d9c004e98069.png)
![lllll](https://user-images.githubusercontent.com/8930862/28617690-0a25d8ec-720a-11e7-9dbb-70eb7e3ff6ec.png)

PLACE

![placeee](https://user-images.githubusercontent.com/8930862/28617723-42caaac4-720a-11e7-9ee7-fe6b8d800bf0.png)

**Comment by karargaht** [comment]
I'm tired :)

Thanks

**Comment by Slicit** [comment]
Thanks we will add these asap :)

**Comment by Slicit** [comment]
Thanks, this should be almost done in 4.12.8
