### ISSUE TITLE
iOS Push Notifications

### ISSUE THREAD

**Issue by theeugenegroup** [Xtraball/SiberianCMS#376]
Push notifications are not appearing on home screen of iSO app (recently published) not is the notification bubble appearing. The message does appear on the notifications page.

When the app is opened a message appears that says "Notification" and "OK" 
When clicked they just go away.

Android Push work as it should as do older apps

**Comment by yoman2191** [comment]
Hello,

I have the same issue. Did you solve it?

Thank you !
