### ISSUE TITLE
Classifieds - Don't Show Map

### ISSUE THREAD

**Issue by champier** [Xtraball/SiberianCMS#379]
PE - v4.12.5
classifieds - 1.3.6

The Maps Key run, but dont show the maps 
![20431309_10211405127102825_3805475925802477307_n](https://user-images.githubusercontent.com/15213215/28707469-d98e5c5c-7378-11e7-9bd1-1955a6c6de52.jpg)

**Comment by clifton11221** [comment]
Please be sure to contact support because Classifieds is a paid module.

**Comment by dbyzero** [comment]
Please contact support directly, thanks.
