### ISSUE TITLE
Modal more not closing when clicking on X

### ISSUE THREAD

**Issue by lsmod** [Xtraball/SiberianCMS#380]
With 4.12.5 modal don't close anymore. This time is not when clicking on a feature but when clicking on X (closing button). Problem occurs with any layout using the modal.
I'm speaking about that modal:
"templates/home/l10/modal.html"

**Comment by Slicit** [comment]
Will be fixed in 4.12.6 thanks ;)

**Comment by theeugenegroup** [comment]
This is only partially fixed in 4.12.6. The modal close now works with Android but NOT iOS

**Comment by Neustradamus** [comment]
Any news on it?
