### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by CheGuevara68** [Xtraball/SiberianCMS#382]
My Siberian 4.12.6 suddenly crashed 404 when logged into the editor pages. My backoffice is also inaccessible.
The folders and files on the server are complete, not missing.
Does anyone have the same problem as me? Please share experience remediation. Thank you.

**Comment by clifton11221** [comment]
If you haven't done so already, I recommend that you contact support.

**Comment by dbyzero** [comment]
Please contact support, we cannot help you without access to your platform.
