### ISSUE TITLE
Commerce Pictures..

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#384]
![111](https://user-images.githubusercontent.com/8930862/28822624-a61a3650-76c2-11e7-89fd-a3ec2b37db60.png)

In the Commerce module, add multiple images does not appear in application. Only 1 picture appears.

The pictures in the application are not scroll to the right or left. 

In fact, this screen shift problem applies to all modules. In the chat module, the screen does not scroll up etc.

**Comment by dbyzero** [comment]
Thank for the report, I will check ASAP.

**Comment by Slicit** [comment]
In fact there was a "Slider" but with no indicators, We added indicators in the latest updates.
Thanks.
