### ISSUE TITLE
Places Module Not Opening The Address In Google Maps

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#385]
The places module isn't opening the business address in Google Maps when you click "Locate". It opens the map but not the address of the respective business. Sometimes it fails to load the map at all.

Also, the "Places" module runs slow (it takes a long time to load). Same with the "Folder" module… When accessing a "Folder" section of an app (not particularly this one) takes a very long time to load.

vMAE 4.12.6

**Comment by Slicit** [comment]
For the places "Locate" button, is takes two set of coordinates (your phone & the location) and finds the best itinerary, it doesn't "shows" the location itself
