### ISSUE TITLE
Enhancement: Allow "tel:" in link module

### ISSUE THREAD

**Issue by glopr** [Xtraball/SiberianCMS#386]
Will be very helpful allowing "tel:" protocol like "http://" in link module. This way we can easily add a click-to-call button.  http://prntscr.com/g4f1z7

**Comment by Vdvoem** [comment]
Hi!
This poser "tel:" is everywhere, after update )

**Comment by dbyzero** [comment]
You already have button named "Phone"

**Comment by dbyzero** [comment]
You have this behavior in custom page with Phone button.

**Comment by glopr** [comment]
Hello! I mean link function with allowing "tel:" hyperlink to inserting a "call us" as a click-to-call button on main menu, not inside a custom page. See screenshot --->  https://www.screencast.com/t/AgmWPe5lCm

**Comment by theeugenegroup** [comment]
This layout has a click to call feature

https://extensions.siberiancms.com/downloads/layout-103/

**Comment by glopr** [comment]
I know, I mean as a feature for all layouts, not only few ones. These layouts have the click-to-call feature but you can't disable it or move position easily (as you can do with standard layouts).

**Comment by glopr** [comment]
Why this request has been closed? It make sence to allow / add tel:// to the link module. This way we can create a quick click-to-call button in the main buttons of the app like layout-103 but with all layouts.

**Comment by userdevel** [comment]
@LikoV2 @dbyzero @Slicit: Can you reopen this issue?

tel: does not work and it does not work for xmpp: and mailto: too.

**Comment by userdevel** [comment]
@LikoV2 @dbyzero @Slicit: Have you seen my previous comment?
I need to create a new ticket?
