### ISSUE TITLE
padlock no login button showing issue

### ISSUE THREAD

**Issue by wouter76** [Xtraball/SiberianCMS#389]
Since the 4.12.x update I have an issue in the padlock view. The spinner below the padlock keeps spinning and no login option is provided.

After some investigation in the code the `value_id/0` in the url took my attention while in most cases `value_id` is checked in the factory by `!value_id` resulting a 0 in evaluating this to false and abort the call to the server.  Normally I agree on handling the validation on value_id like this but in this case, while value_id/0 is set by default in the `$stateProvider` (..js/features/padlock.js but also in the bundle file in this dir), I suggest to either skip the check or explicitly except 0 as a value too.

So my suggestion to change lines 45 and 61 of the ..js\factory\padlock.js (or actually all files holding the factory Padlock) from:
`if(!this.value_id) {`
to:
`if(this.value_id === undefined) {` or `if(this.value_id === undefined && this.value_id < 0 ) {`

Hope this is marked as a bug and will be fixed in an update soon.

**Comment by dbyzero** [comment]
Thanks for the report, we will check ASAP.

**Comment by Slicit** [comment]
Fixed in 4.12.8
