### ISSUE TITLE
Commerce Feature Tax Issue

### ISSUE THREAD

**Issue by glopr** [Xtraball/SiberianCMS#39]
Need to add option for non-taxable items. Currently system display an SQL error notifying that tax id cannot be null. See screenshot here http://prntscr.com/bgd5o1

**Comment by MarcReis** [comment]
sory, my english is no good, but  create tax with value 0.0 dont solve :)

**Comment by trafasi** [comment]
Create option with 0.0 and text NON-TAXABLE and is solved.

**Comment by SiberianCMS** [comment]
Thanks for the solution.

Also please check 4.7.10 for all the Mcommerce improvements.
