### ISSUE TITLE
Twice files?

### ISSUE THREAD

**Issue by Neustradamus** [Xtraball/SiberianCMS#390]
There are twice files:
In https://github.com/Xtraball/SiberianCMS/tree/master/lib/Siberian/Form/Element
- https://github.com/Xtraball/SiberianCMS/blob/master/lib/Siberian/Form/Element/Multiselect.php
- https://github.com/Xtraball/SiberianCMS/blob/master/lib/Siberian/Form/Element/MultiSelect.php

In https://github.com/Xtraball/SiberianCMS/tree/master/lib/Siberian/View/Helper
- https://github.com/Xtraball/SiberianCMS/blob/master/lib/Siberian/View/Helper/FormNumber.php
- https://github.com/Xtraball/SiberianCMS/blob/master/lib/Siberian/View/Helper/formNumber.php

Please remove the old and name correctly the files.

Thanks in advance.

**Comment by Slicit** [comment]
Fixed ;) thanks for the highlight.
