### ISSUE TITLE
with last packages, installer is stopped at 66% : Importer

### ISSUE THREAD

**Issue by Neustradamus** [Xtraball/SiberianCMS#393]
With last packages, the installer is stopped at 66% "Importer"

What is the problem?

**Comment by appsteroids** [comment]
I am having the same issue, tried reinstalling with no success.

**Comment by wbhagan** [comment]
Any luck with the resolution of this issue?

**Comment by Slicit** [comment]
Have you tried pulling latest github version and reinstalling?

**Comment by wbhagan** [comment]
Hi,
Yes, I just did that again and started all over.

Using firebug, I see this at the 66% mark.
http://localhost:8090/errors/500.php?log=error__599d4707c6161.log

Do find attached the referred log file (renamed with a .txt extension)
[error__599d4707c6161.txt](https://github.com/Xtraball/SiberianCMS/files/1244833/error__599d4707c6161.txt)

**Comment by mssavai** [comment]
I'm facing same problem.

**Comment by Slicit** [comment]
It's fixed, some files were not deleted from the github as they were in MAE/PE
