### ISSUE TITLE
How to transfer app from the version of PE in SAE ?

### ISSUE THREAD

**Issue by Vdvoem** [Xtraball/SiberianCMS#394]
Hello!
Can anyone suggest how to migrate the application from the version of PE in SAE ?

**Comment by Neustradamus** [comment]
Good idea but for all:
- SAE to MAE
- SAE to PE
- MAE to SAE
- MAE to PE
- PE to SAE
- PE to MAE

**Comment by alisgold** [comment]
Yes, this is very important! Please please please share with us this secret.

**Comment by Vdvoem** [comment]
When I turn it on in the BackOffice "Developer" mode in the admin panel in the section "Function" appears the "Export/Import" of application, but not working, anyone has a solution to this problem?

**Comment by Slicit** [comment]
The Export/Import is still in development (that's why it's visible only when in development mode).
What it will allow
1. Export/Import single features with options (privacy, etc ...)
2. Export complete App as a "Template"
3. Export/Import complete App from & to any Siberian Editions

**Comment by Vdvoem** [comment]
That would be great )

**Comment by davidwebs** [comment]
I look forward to this feature.

**Comment by Slicit** [comment]
Thread done, closing.
