### ISSUE TITLE
Can't add or change background image to Folder

### ISSUE THREAD

**Issue by singfa** [Xtraball/SiberianCMS#397]
Hello,

After updated to version 4.12.0 i can’t anymore to add background images to folders.

When i click on the BACKGROUND button the window is opening in the backgound of the DESIGN bar like in the picture below:

http://my.radioapps.eu/folder.gif 

I saw two more updates coming up and after installed it i hoped it would solve this problem but unfortunately this issue was not solved.

**Comment by alisgold** [comment]
Also, the problem is, the BACK button is gone, if you add news to the folder, you can not change the design.

**Comment by singfa** [comment]
So how can i to solve this issue?

**Comment by alisgold** [comment]
Strange question, if we knew how to solve this problem themselves and fixed it.
Check create function news and paste it in the folder after that, try to change the function design news

**Comment by singfa** [comment]
So i temporarily solved this issue by editing the file /app/sae/design/desktop/flat/template/folder/application/edit.phtml

and adding some `<br />` after the line 23 to push down the Design tab.
Now i can add or change the folder background.
http://prntscr.com/g78kfv

I know this isn't the right solution but until the developer solve this issue, i will use it.

**Comment by alisgold** [comment]
Thank you.

**Comment by Slicit** [comment]
Please update to latest version & re-open an issue if it's still relevant.

**Comment by singfa** [comment]
I have the latest version MAE - v4.12.7 but i have the same issue.

**Comment by singfa** [comment]
I have the latest version, MAE - v4.12.7 but i have the same issue.
