### ISSUE TITLE
Question: Taxi Ride

### ISSUE THREAD

**Issue by glopr** [Xtraball/SiberianCMS#398]
Is it possible to remove/hide/disable taxi ride driver registration from end-user app, but still registering drivers on back-office? If a Taxi Company want to use Taxi Ride app for their staff and not to allow new drivers... All other features will remain as is. If yes, how this can be disabled?

Thanks in advance!

**Comment by Slicit** [comment]
Taxi-Ride is a commercial module, all questions must be done via e-mail to contact@siberiancms.com thank you.
