### ISSUE TITLE
E-mails comes up blank

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#4]
I forgot my password, e-commerce etc. e-mails feels empty.

![1](https://cloud.githubusercontent.com/assets/8930862/15390916/2f7112da-1dc7-11e6-83eb-a99a1f1d303f.jpg)

![222](https://cloud.githubusercontent.com/assets/8930862/15390919/31b1f94c-1dc7-11e6-93b5-9ce37448f8fc.jpg)

![4444](https://cloud.githubusercontent.com/assets/8930862/15390924/33e2ec6c-1dc7-11e6-8374-537782170659.jpg)

![5555](https://cloud.githubusercontent.com/assets/8930862/15391015/a50dc754-1dc7-11e6-929c-e48dc6d8d950.jpg)

**Comment by dbyzero** [comment]
We are working on 4.1.1 to fix this issue.

**Comment by alexyves** [comment]
Closed http://updates.siberiancms.com/release-notes/sae/4.1.1.html
