### ISSUE TITLE
Generate APK for previewer SE edition 

### ISSUE THREAD

**Issue by trafasi** [Xtraball/SiberianCMS#40]
Hello, 
I am trying to generate APK file for the previewer. 
I installed latest previewer version. 
Solved the default gradle wrapper issue 
but now getting this error : 

Error:(15, 0) Gradle DSL method not found: 'runProguard()'
Possible causes:<ul><li>The project 'previewer-android' may be using a version of Gradle that does not contain the method.
<a href="openGradleSettings">Gradle settings</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

![schermafbeelding 2016-06-17 om 15 57 34](https://cloud.githubusercontent.com/assets/19797853/16152909/45b798ea-34a4-11e6-9625-1df514076636.png)

**Comment by alexyves** [comment]
Latest previewer version is 4.4.1
