### ISSUE TITLE
shopify feature does not work properly in the app when published or when previewed

### ISSUE THREAD

**Issue by davidwebs** [Xtraball/SiberianCMS#400]
Has anyone successfully added the shopify feature on SiberianCMS

 PE and had it work correctly?

I added the shopify feature to one of my apps and it did not open properly on the app rather it displays in a small frame below the app menu, which is not even noticeable. I accidentally noticed that that’s where it displays.

Has someone ever encountered this bug?

Siberian CMS Team please look into this bug and fix. So that shopify store owners can use the platform to create a mobile app for their store.

![screenshot_2017-08-11-16-39-03](https://user-images.githubusercontent.com/30932682/29222785-df42d06c-7ebb-11e7-9fac-c774bd2fe29a.png)

**Comment by Slicit** [comment]
Shopify `feature` is only an alias for `Link` feature, so can you try with link?

**Comment by davidwebs** [comment]
I noticed that the Shopify feature is only an alias for Link. So I tried the Link feature and it performs the same way. See the app below that has the shopify feature.

https://apps.mobileappforeveryone.com/5987c4a93e87d/

**Comment by Slicit** [comment]
Seems the webview doesn't handle very well the Shopify css, you must force the use of chrome in this case, we can't do anything on this side.

**Comment by davidwebs** [comment]
Thanks for your response. But just to be clear, is this an issue with Siberian CMS at the moment?

**Comment by Slicit** [comment]
No it's not an issue, it's just that the webview doesn't seem to like shopify.

**Comment by Hyperians** [comment]
so any solution for that issue so far, missing shopify is catastrophic disadvantage
