### ISSUE TITLE
Add payment commerce

### ISSUE THREAD

**Issue by obaviet** [Xtraball/SiberianCMS#401]
Hello,
I would add location payment gateway, how do i work?
Does Siberiancms have documentation?

**Comment by Slicit** [comment]
There is no easy way to do it as of today, payment gateways are in the Siberian core & we yet didn't worked on opening that part of the code, so there is also no documentation about it!

Maybe one day at some point, it's in our long-term schedule if things rules well!

**Comment by Slicit** [comment]
We have changed the API and some code to allow external developers to add new payment gateways for M-Commerce, the documentation should arrive soon too!

http://board.siberiancms.com/b/7AYdMDEpFcmt3eZtb/siberiancms-public-roadmap
