### ISSUE TITLE
Page not found when using Facebook

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#402]
Hello,
Since the version where Facebook's import ban was created, all my applications that use Facebook features have stopped working and if I try to recreate again in the backoof the error message Page not found.
I tried to follow doc.siberiancms.com guidelines, but the documentation is out of date according to the screens that appear on developer.facebook.com.
I need guidance to correct this problem. please.

**Comment by ciadoreino** [comment]
When the facebook name has "." Does not load the page in the application
Example: https://graph.facebook.com/ibn.igrejabatistanacional

**Comment by ciadoreino** [comment]
When the facebook name has "." Does not load the page in the application
Example: https://www.facebook.com/ibn.igrejabatistanacional

**Comment by davidwebs** [comment]
Hi,
I have a problem with facebook page loading, though the facebook name does not have a "."
The facebook page justs keeps loading and blinking continuously. Have you experienced this problem before?
When you add a facebook page and view it from the app, it keeps blinking and loading continuously.
Here’s a video link to see how the facebook page loads continuously.
https://s.nimbus.everhelper.me/share/1065641/el2r82txv2dg0mcnc6w1
Thanks

**Comment by Slicit** [comment]
@ciadoreino it seems `https://www.facebook.com/ibn.igrejabatistanacional` is not a Facebook page, but rather a user, Facebook import works only with pages.

However, the error message is not clear enough!

**Comment by Slicit** [comment]
Closed as inactive/incorrect.
