### ISSUE TITLE
Form - Email

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#408]
E-mails sent from the form module are being sent but not reaching the other party.

v4.12.8

(Test: http://demope.siberiancms.com)

**Comment by clifton11221** [comment]
Did you check the Spam folder?

**Comment by karargaht** [comment]
No, he never comes. You can try demo site.

**Comment by Vdvoem** [comment]
Yes, we also encountered such a problem, we have a person added a function to the photos, that GeoIP and mail were displayed on the photo, we can not check, since letters do not come to the post office )

**Comment by LikoV2** [comment]
Hi,

That's because the VPS are usually shipped with poor SMTP configuration. You have two choices, configurate your server and your domain (with dkim, dmarc, etc...) -> not tested yet, it's just a guess, or use a custom SMTP server, like Mailgun for example.
