### ISSUE TITLE
#4.12.8 radio player busted again

### ISSUE THREAD

**Issue by rogerdavis198** [Xtraball/SiberianCMS#409]
Hi guys the shoutcast fix has busted the player again, before on last fix all worked even opus and aac using phone codecs now with above fix its broken the lot and html5 player sites too.

To add shoutcast streams you only need  ip:port ie  myip:8000 the /listen.pls bit is not needed guys, can we revert back to last update asap please as its breaking all my station apps.

Thanks

**Comment by Slicit** [comment]
Can you send me your stream urls ? I'll test things, and for the ShoutCast fix, it's only adding a ';' at the end to force stream & not HTTP Landing.

**Comment by rogerdavis198** [comment]
mobile.bigl.co.uk

**Comment by rogerdavis198** [comment]
there you go try that lot first 2 are shoutcast

**Comment by Slicit** [comment]
This is an Angular App ...

**Comment by rogerdavis198** [comment]
the html5 one is but other are not but still same

**Comment by Slicit** [comment]
We do not support old Angulars Apps for almost 1 year or more, send me New Ionic App to check and find out issue 👍

**Comment by rogerdavis198** [comment]
http://apps.appnugget.co.uk/5703bad2a6f9c/

**Comment by rogerdavis198** [comment]
thats got nothing to do with that links apps i have simply change that one in the database so it works on windows and html5 properly

**Comment by rogerdavis198** [comment]
the faulty ones are links on lower part of app, just ignore the hml opus ones ,cheers

**Comment by rogerdavis198** [comment]
I take you saw the link to the real app on git hub fella.

Thanks



⁣Sent from BlueMail ​

**Comment by rogerdavis198** [comment]
the icecast ones are dead too guys

**Comment by rogerdavis198** [comment]
its affecting everyone with icecast streams only shoutcast ones work noe can you revert it back please and we can play with it on a test server instead 
cheers

###/////if it's only adding a ';' at the end to force stream & not HTTP Landin~///#

**Comment by rogerdavis198** [comment]
gone back to 4.12.7 via backup as 8 and 9 are still  u/s guys

**Comment by rogerdavis198** [comment]
![qrcode](https://user-images.githubusercontent.com/24929628/29664319-0e560cc4-88c7-11e7-821b-35e32b072f06.png)

**Comment by rogerdavis198** [comment]
that's 4.12.7 working if u wish to install on android 6 or 7 , also we need a way to turn off battery optimization on android 7 and above as it stops all the streams playing after a couple of mins, also html5 apps when used in windows there should be a added script to tell the audio to keep playing when phone goes to sleep. cheers

**Comment by rogerdavis198** [comment]
can we not have a switch added so we can switch ';' at the end of the stream ie for port (shoutcast) or
mounted streams such as icecast to use without the ';' at the end as that would keep your shoutcast fix and add the icecast or mounted stream back into the mix too. thanks

**Comment by Slicit** [comment]
closing as fixed, it was a firewall server issue.
