### ISSUE TITLE
layout translations field list not being update for pt_BR

### ISSUE THREAD

**Issue by lsmod** [Xtraball/SiberianCMS#412]
resources/translations/pt_BR/codename.csv
is being ignored when installing or updating a layout

**Comment by Slicit** [comment]
Having it in the default resources is ok, but you must go in the pt_BR translation page on the backoffice then save it at least once, or after each update.

**Comment by lsmod** [comment]
Yes but that's not the issue. 
If let's say I add an entries into my csv file, then install the newly updated. When going to translation into backoffice my new entries don't get translated (but other languages do). 
By not being translated I mean that the field is not auto filled by fetching data from the csv file.
