### ISSUE TITLE
Web Preview v4.12+

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/SiberianCMS#415]
This new version 4.12 is killing me guys!
It is extremely slow on the source code feature 
Just tested your demo as well

When you make a change the right hand web view just doesn't update - you have to refresh the whole browser to see the change.

Also in the actual mobile APPS - folders and source code tabs takes forever to load!

**Comment by Slicit** [comment]
Can you share me some Apps that are slow, because I'm pretty sure it's not a general issue, but rather specific to some use cases.

**Comment by bluesnap-rock** [comment]
Hi Slicit - please see this app
https://play.google.com/store/apps/details?id=uk.co.rocketappcreator.build.app5548bdcc43206

What about the webview window - whenever you change customer scss - it doesnt update the preview, whenever you change code in source code (tested the siberian demo as well) it doesnt update the preview - you have to refresh the page?

thanks.

**Comment by Slicit** [comment]
Yes the web preview, has some known issues, some modules aren't updating live without refreshing the page, it's something complicated to main, as it's directly linked to the Apps.

**Comment by Slicit** [comment]
I tested the app in 3G and it seems it's working correctly, not super fast, but fast enough for a 3G connection.
However
Can you try to re-install the app without accepting the "offline mode" to see if it's working faster ?
I believe this can helps

**Comment by bluesnap-rock** [comment]
Thanks, its seems the only way is republishing all APPS made prior to 4.12+ in order to work efficiently. The offline mode help a lot as well - thanks. We need the web preview up and running again as soon as possible.

**Comment by Slicit** [comment]
Update to latest version, and if this is still not working consider opening a ticket on the Support Desk

**Comment by bluesnap-rock** [comment]
Slicit - web preview still not updating when editing source code pages - check the siberiandemo - same there.
