### ISSUE TITLE
The scripts do not work in the "Custom Code" function

### ISSUE THREAD

**Issue by Vdvoem** [Xtraball/SiberianCMS#416]
Hello!
Can someone encountered a bug, scripts in the function "Own code" do not work. Maybe that on the server should be configured?

**Comment by clifton11221** [comment]
If you have a script that won't run properly in the Source Code module, I recommend adding the script to an html page, then open the page via the "Link" module.

**Comment by Vdvoem** [comment]
I paste the HTML code, attached it, on your test designer everything works correctly, and my SAE does not run scripts.
[test.zip](https://github.com/Xtraball/SiberianCMS/files/1267417/test.zip)

**Comment by Vdvoem** [comment]
All solved this problem, it was necessary in HTML to insert links not http and https )))
