### ISSUE TITLE
Forms feature does not send email to the app owner or user after filling the form Forms feature does not send email to the app owner or user after filling the form

### ISSUE THREAD

**Issue by davidwebs** [Xtraball/SiberianCMS#418]
Hi people of Siberian CMS,

I have noticed that when a form is created using the form feature, the app owner does not receive any email with details of the submitted form, neither does the user get form submission confirmation.

Has anyone experienced this?
How can this be resolved?

Thanks

**Comment by bluesnap-rock** [comment]
What version are you running?....just checked mine 4.12.9 and i received email just name and message is what is set at client app and it worked. Albeit however these new versions I am having major issues with completing a sale in mcommerce.....will not reach delivery selection just goes all the way back. Your version and server spec might help siberian people.

**Comment by davidwebs** [comment]
Thanks for your response. I'm running the latest 4.12.9 as well but I'm still not able to receive emails from forms feature and the booking feature. At first I thought it was a problem with my mail server, but every other email notification gets delivered from new user registration email to both the user and admin and also when an apk or source code is generated. Only this feature that does not send email to the form owner and user. I've looked at every setting I know. 
Does this have anything to do with php version? I'm using php version 7.0.20
