### ISSUE TITLE
Create an account in two or more app is not possible with the same email

### ISSUE THREAD

**Issue by Gibasam** [Xtraball/SiberianCMS#42]
If do you have two apps instaled in your device dont is possible create an account for each theirs. If you have more than one app from the same platform installed on your device. You will be able to create accounts for each of them to create with a different email. It is not possible to create multiple accounts with the same email.

**Comment by alexyves** [comment]
One account is linked to one app and you can use the same e-mail to create account for 2 or more apps on the same platform.
