### ISSUE TITLE
Fan Wall Not Showing Correct Posting Date

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#424]
I just made a post in Fan Wall module about **10 mins ago** - on **09/07/17** -  and the posting date is incorrectly showing "**60 days ago**".

On using MAE v4.12.9

![img_4661](https://user-images.githubusercontent.com/21089972/30170486-3db85a20-93bd-11e7-86e7-8d2765616133.PNG)

**Comment by Slicit** [comment]
Looks like it took the date for July rather Than September > 09/07/17 = dd/mm/YY
Will check the datepicker

**Comment by theeugenegroup** [comment]
Same with me but when you click on the post it has the correct time/date

**Comment by clifton11221** [comment]
Was this closed because the fix is in the next update?
