### ISSUE TITLE
Problems with the TixiRide module.

### ISSUE THREAD

**Issue by Vdvoem** [Xtraball/SiberianCMS#425]
##There was a problem in the TixiRide module, the passengers do not find drivers, although the drivers are active and waiting for the application, who solved this problem?
Or can someone tell the contacts of the developers of this module?

**Comment by clifton11221** [comment]
You need to open a Support Ticket.

Be sure to include your version of Siberian and the version of the Taxi module that you're using.

**Comment by Vdvoem** [comment]
Hello!
I have SAE - v4.12.9
TaxiRide 1.7.3
Socket V 1.6.1

**Comment by Vdvoem** [comment]
I have increased even the search radius to 1000 km, still it did not help. I attach the screens.
I changed the search radius from 20 to 1001 in the GeneralSettings.php file, it still did not help.
![-3](https://user-images.githubusercontent.com/30751163/30349387-a8b5e5a6-9834-11e7-9c98-b394a67ad4f9.png)
![-1](https://user-images.githubusercontent.com/30751163/30349388-a8b6f9aa-9834-11e7-85f7-84af783581a6.png)
![-2](https://user-images.githubusercontent.com/30751163/30349389-a8b8bcae-9834-11e7-84d6-c93a3b674923.png)

**Comment by Vdvoem** [comment]
In short, I understand that it was in vain to pay for this iodule 159 euros.
Gavno, not the module.

**Comment by Slicit** [comment]
Looks like there is a mis-configuration or something like the socketio server not running probably, for paid modules, the support is provided from Tickets & not from github, here we handle only SAE & Free modules issues.

Check if your socketio server is running well (with ou without https) and try with two phones one driver and one passenger.
Also check you have the latest taxi-ride version ;)

Thanks.

**Comment by Vdvoem** [comment]
That would not write a lot of attached screen, they themselves will see what works and what does not work
![-4](https://user-images.githubusercontent.com/30751163/30367244-88719cee-988f-11e7-800e-dee123c9fbe3.png)

**Comment by clifton11221** [comment]
@ Vdvoem - Send all of info you posted here to Support.

**Comment by Vdvoem** [comment]
We already wrote, there is no solution.

**Comment by Slicit** [comment]
closing, waiting for taxi-ride 2.0 update, thanks.

**Comment by rathodsuraj1** [comment]
I had the same issue where passenger was not able to see driver and socketio was offline always, what fixed the issue for me is to grant permissions over database for host 127.0.0.1. I had only localhost earlier, allowing from 127.0.0.1 fixed it!

Hope this will help someone.

Thanks,
