### ISSUE TITLE
Terms & Conditions Link in Coupons

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/SiberianCMS#426]
Hi guys the button/link to terms and conditions is no longer present in the coupons section.  v4.12.10 - Great new addition wit the revival slider. But we do need the link to full terms and conditions that are set in the Settings tab

**Comment by theeugenegroup** [comment]
Unable to edit/add content to coupons after update to 4.12.10

**Comment by bluesnap-rock** [comment]
The new revival slider - if one coupon is larger than the other (just add a lot more text in the first one), the smaller coupons will then have a bottom background overflow.

**Comment by Slicit** [comment]
It's a slider, we can't have different overflow sizes, and cutting text will be kinda confusing.
Just test and adjust your coupons, so they'll be almost the same size.
Also there is coupon with button & without, the height changes etc ...
Not a real issue IMO
And the "Terms & Conditions" is a link in the Layout 5 it's how it's done, if you want a button, you can use another one, or customize it.

**Comment by bluesnap-rock** [comment]
Hi - yes sorry correct, I forgot that TEXT had to be present in the Terms & Conditions - the link is showing now - but most of all the END DATE doesn't not work - select the date, when saved it shows 0000-00-00 you cannot change it once saved this applies to old coupons and newly added coupons - thanks.

**Comment by Slicit** [comment]
Okay thanks for the issue report, i'll check dates asap!

**Comment by Slicit** [comment]
Fixed in 4.12.11, scheduled for Monday 18th
