### ISSUE TITLE
Problem Translation 

### ISSUE THREAD

**Issue by applimoby** [Xtraball/SiberianCMS#43]
Hello!

again and again the same problems .... since the last update translations do not work ( french ) . eg button " back" , "no items found" ect ......

The problem is present in version MAE and SAE for me .

//

encore et toujours les mêmes problèmes.... depuis la dernière mise à jour les traductions ne marchent plus (francais). ex: button "back", "no items found" ect......

Le problème est présent dans la version MAE et SAE pour moi.

**Comment by SiberianCMS** [comment]
Fixed in 4.2
