### ISSUE TITLE
Error "Read timed out after 10 seconds" in update to 4.12.10

### ISSUE THREAD

**Issue by davidwebs** [Xtraball/SiberianCMS#433]
Today I wanted to update my PE to version 4.12.10 and I got the error “Read timed out after 10 seconds”.
Here's the screen shot of the error below.
![untitled-1](https://user-images.githubusercontent.com/30932682/30508252-5b6142e8-9a8a-11e7-9594-ff0f79934cee.png)

Kindly advise.
Thanks

**Comment by Slicit** [comment]
Can you try again ? our licence server was down.
