### ISSUE TITLE
Glitch in Layout 12 appearance

### ISSUE THREAD

**Issue by tieme002** [Xtraball/SiberianCMS#435]
When loading my app with layout 12 for the first time, the layout doesn't show up as expected. See photos for details.

Resizing the screen for instance by rotating the phone helps bringing up the right layout.
![img_2870](https://user-images.githubusercontent.com/31991487/30540494-bf63c4b6-9c77-11e7-8a18-8a1da1404072.PNG)
![img_2871](https://user-images.githubusercontent.com/31991487/30540495-bf7fe8e4-9c77-11e7-83e2-bf1f330436e1.PNG)

App address: app.woodend.nl/var/apps/browser/index-prod.html

**Comment by tieme002** [comment]
Found a solution for this one.
This CSS line should be added:

`.layout.l17 .metro-line-50{width:100%;}`

Can you add this to the source?

**Comment by Slicit** [comment]
We will check for this fix, thank you :)

**Comment by Vdvoem** [comment]
Another test, then that the pictures in the functions do not load, screens I enclose ..
![default](https://user-images.githubusercontent.com/30751163/30545497-9d85b8e8-9cab-11e7-8f49-1557c66ec2cf.png)
![Uploading Скрин-2.png…]()

**Comment by Vdvoem** [comment]
![-2](https://user-images.githubusercontent.com/30751163/30545565-d0feef46-9cab-11e7-8a15-e8dbcad52e2e.png)

**Comment by Slicit** [comment]
It's already opened in another ticket, please keep only one issue by ticket ;)

I added the CSS for 4.12.12 update thanks.

**Comment by Vdvoem** [comment]
Well, I'm waiting for corrections.

**Comment by Vdvoem** [comment]
When will you eliminate all bugs with the Taxi function?
