### ISSUE TITLE
Unable to add/edit pricing plans in backoffice after upgrade to PE - v4.12.11

### ISSUE THREAD

**Issue by davidwebs** [Xtraball/SiberianCMS#437]
Hi,
I have just upgraded to PE - v4.12.11. Now I am unable to add or edit pricing plan in the backoffice.
When I click save, the ajax loader keeps loading forever.
Here's a video shot of the behaviour of the save button. http://nimb.ws/tjqTIV

**Comment by bluesnap-rock** [comment]
I can concur. I have same issue v4.12.11

**Comment by davidwebs** [comment]
Is there any solution for this yet? I have not been able to add a pricing plan. Please help.

**Comment by Slicit** [comment]
4.12.12 released.
https://updates02.siberiancms.com/release-notes/all/4.12.12.html
