### ISSUE TITLE
Custom Pages Not Saving Any Data After Upgrade To 4.12.11 (From 4.12.10)

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#438]
Ever since I upgraded from MAE 4.12.10 to 4.12.11 today the Custom Pages are not save any changes or if you create a new page nothing is saved.

**Comment by clifton11221** [comment]
This is a **BIG problem**.  If someone have a hot fix please post it.

**Comment by davidwebs** [comment]
I just observed this problem too with the custom pages.
People of SiberiaCMS please look into this ASAP.
Thanks

**Comment by Slicit** [comment]
The fix is scheduled for 4.12.12 scheduled for tomorrow.

**Comment by Spotcloudtk** [comment]
nothing works after the last update. Inbox does not work, dashboard keys to delete cache, etc., etc. do not work

**Comment by Spotcloudtk** [comment]
Also giving these errors


[Tue Sep 19 01:38:06.523150 2017] [autoindex:error] [pid 5641] [client 79.46.252.111:55745] AH01276: Cannot serve directory /public_html/images/application/: No matching DirectoryIndex (index.php) found, and server-generated directory index forbidden by Options directive, referer: /application/customization_publication_app
[Tue Sep 19 01:40:53.324969 2017] [fcgid:warn] [pid 6283] (32)Broken pipe: [client 79.46.252.111:54441] mod_fcgid: ap_pass_brigade failed in handle_request_ipc function, referer: /var/apps/overview/index-prod.html
[Tue Sep 19 01:41:22.759317 2017] [autoindex:error] [pid 6310] [client 79.46.252.111:57905] AH01276: Cannot serve directory /public_html/images/application/: No matching DirectoryIndex (index.php) found, and server-generated directory index forbidden by Options directive, referer: /application/customization_publication_app
[Tue Sep 19 01:42:53.288639 2017] [fcgid:warn] [pid 7230] (32)Broken pipe: [client 79.46.252.111:50626] mod_fcgid: ap_pass_brigade failed in handle_request_ipc function, referer: /var/apps/overview/index-prod.html
[Tue Sep 19 14:53:04.541265 2017] [fcgid:warn] [pid 27240] (32)Broken pipe: [client 192.168.1.2:45636] mod_fcgid: ap_pass_brigade failed in handle_request_ipc function, referer: /app/sae/design/desktop/flat/css/prettyPhoto.css?1500566017
[Tue Sep 19 14:53:46.154634 2017] [fcgid:warn] [pid 5880] (32)Broken pipe: [client 79.46.252.111:63938] mod_fcgid: ap_pass_brigade failed in handle_request_ipc function, referer: /var/apps/overview/index-prod.html

**Comment by Slicit** [comment]
4.12.12 released.
https://updates02.siberiancms.com/release-notes/all/4.12.12.html

**Comment by Spotcloudtk** [comment]
Nooooo inbox no work. Not send messageeeee
