### ISSUE TITLE
Background image error on pages

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#439]
Hello,
After I updated it to PE 4.12.11, the background images of the pages stopped being displayed and only the background image defined in "Design" is displayed on all pages, even with the option to use the image from the home page as background on all features being unchecked.

**Comment by ciadoreino** [comment]
in version 4.12.12 continues with the same problem. It also does not update the app preview in the backoffice.

**Comment by Slicit** [comment]
This issue should be fixed in 4.12.14, release for tomorrow.
