### ISSUE TITLE
Pricing plan Enhancement for PE to create separate resellers plans

### ISSUE THREAD

**Issue by davidwebs** [Xtraball/SiberianCMS#440]
PE owners who want to create resellers should be able to create a separate pricing plan for resellers. Currently, the pricing plans are based on per app. So if you create a reseller plan, it means that for each app the reseller builds they will have to pay the same fee per app. But if there's a separate reseller plan pricing that can be set such that once the reseller subscribes for that plan, all apps in his account will be billed according to how the admin set it.
Example Reseller Plan: 
Plan sample 1: One time fee, then $x/app/year or month
Plan sample 2: One time fee, with capacity to build a limited number of apps, which the PE admin can set.
So the pricing plans can incoprate these kinds of plans for resellers of PE

**Comment by davidwebs** [comment]
Is there any update on this enhancement?

**Comment by Slicit** [comment]
Not that much time for improvements right now, focusing on stability.

**Comment by LikoV2** [comment]
Hi @davidwebs,

I will close this issue, as it's not related to Single-App Edition. Don't worry, we are keeping your enhancement request. Unfortunately, I don't know when the developers will start working on it.
