### ISSUE TITLE
New template for app preview

### ISSUE THREAD

**Issue by Spotcloudit** [Xtraball/SiberianCMS#442]
I wanted to know if you can automatically create this html code to make app preview more beautiful. now I manually include it with <iframe>

demo: https://appbuild.spotcloud.tk/preview/scarlino.html

![device](https://user-images.githubusercontent.com/27977045/30749125-bae2ca02-9fb2-11e7-93a2-c04fdcee8c4f.png)

[name_app.zip](https://github.com/Xtraball/SiberianCMS/files/1324834/name_app.zip)

enjoy

**Comment by Slicit** [comment]
I don't really understand were do you want this to be ? and will it should be portable with every app ?

Give me more details :)

**Comment by Spotcloudtk** [comment]
It should automatically create it for every app you create
