### ISSUE TITLE
InBox does not delete messages. 

### ISSUE THREAD

**Issue by Spotcloudit** [Xtraball/SiberianCMS#446]
InBox does not delete messages. Clicking on the trash can not do anything

**Comment by clifton11221** [comment]
Please confirm the version of Inbox and Siberian that you're using.

**Comment by Spotcloudtk** [comment]
Siberian and Inbox 4.12.13

**Comment by Spotcloudtk** [comment]
News?

**Comment by portalidea** [comment]
News about that? I have Siberian 4.12.17 and Inbox 4.12.13
