### ISSUE TITLE
Mailchimp API other newsletter service API integration (enhancement)

### ISSUE THREAD

**Issue by davidwebs** [Xtraball/SiberianCMS#448]
I suggest that under Settings > APIs, additional field should be added for mailchimp api keys so that new users will be automatically subscribed to mailchimp newsletter if the backoffice admin adds his/her mailchimp api key.
Then in the signup page, a checkbox should be there that says subscribe for updates and should be prechecked

**Comment by Slicit** [comment]
The Mailchimp is develop by weAppz you may contact him directly for improvements on this ;)

https://www.facebook.com/weAppz/

Thanks ;)
