### ISSUE TITLE
MCommerce

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/SiberianCMS#450]
I only and have only ever used MCommerce in Siberian albeit very slow - I did switch some APPS for ios (couldn't do it with Android because of APK signing) from como.com - all which are now on Siberian - however, now app analytics from itunes.apple is saying 100% APP crashes from opt-in users in just 3 months - MCommerce needs a some work - this is one of the most integral parts of monetising from an APP. Please guys show the big boys like como that you can do this better !!!

**Comment by Slicit** [comment]
please check latest versions and re-open if still relevant
