### ISSUE TITLE
Radio Module Not Working With iOS v11

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#451]
The Radio module is not working with iOS v11. It works fine with v10.

I'm using MAE v4.12.13

I tested with two different streams.  See below:

http://s4.streammonster.com:8419/stream

http://vip.livecastnet.com:8000/lowcountryradio.mp3

**Comment by gonzoradio** [comment]
Working with iOS v11.01 SAE v4.12.13
**Tested on this app:** https://itunes.apple.com/us/app/durham-radio-news/id1136853618?ls=1&mt=8
**With streams:** 
https://playerservices.streamtheworld.com/api/livestream-redirect/CKGEFMDROID.mp3
https://playerservices.streamtheworld.com/api/livestream-redirect/CJKXFMDROID.mp3
https://playerservices.streamtheworld.com/api/livestream-redirect/CKDOFMDROID.mp3

**BUT...not working with your stream links above.**

Maybe something to do with the port numbers?

**Comment by clifton11221** [comment]
The weird thing is it worked fine on iOS 10.

**Comment by clifton11221** [comment]
Apparently I'm not the only one with this issue:

[https://www.siberiancms.com/forums/topic/radio-module-does-not-work/](url)

**Comment by clifton11221** [comment]
Another thing worth mentioning is I tried using a third party player... It would work fine on web but when I use the Source Code module open the page with the Link module the volume doesn't work either.

**Comment by clifton11221** [comment]
This is another one that stopped working (but works in App Simulator):
https://stream.radio.co/sa2b95733d/listen

This one still works:
http://stream.zenolive.com/0v104zr0974tv

**Comment by singfa** [comment]
Hello all,
Yes after the last 3-4 updates i have some issues.
Now i have the MAE - v4.12.16

The the biggest of them is the radio player which is not working anymore.
Here is a video and it shows the issue.

http://188.165.212.154/FolderIssue2.mp4

I have a lot of applications with radio players so i hope someone from Xtraball to solve this.

Another issue is with the Icon Manager where the new uploeded custom icons can't be deleted.

**Comment by clifton11221** [comment]
More issues with the audio Siberian.

If you go to: http://buzapps.net/_download/public/_delete/radio/index.html and press 'Play' the audio works fine.

However, if you open the url in the "Link" module or put it in an iframe in the Source Code Module the audio doesn't play.  I tested with 2 other scripts and had the same problem.

I'm testing with MAE 4.12.17

**Comment by rogerdavis198** [comment]
can we not have a switch added so we can switch ';' at the end of the stream ie for port (shoutcast) or
mounted streams such as icecast to use without the ';' at the end as that would keep your shoutcast fix and add the icecast or mounted stream back into the mix too. thanks

**Comment by Slicit** [comment]
This is fixed in 4.13+ updates, there was an issue with the MusicControl plugin
