### ISSUE TITLE
Publishing App Bugs in Payment

### ISSUE THREAD

**Issue by winkertk** [Xtraball/SiberianCMS#453]
I realize there’s a bug in your payment module.. My client select offline payment for the first time, but I have cancel the payment.. And they did 2nd payment via paypal.. But the date of billing is next month.. So the system didn’t capture the cancellation of the first offline payment.. Assume it is paid for August 2017.. And the 2nd online payment is for September 2017..

**Comment by LikoV2** [comment]
Hi @winkertk,

As your issue is linked to commercial editions, please create a support ticket, or send us a mail to contact@siberiancms.com.

Thanks.
