### ISSUE TITLE
Publishing Apps with Description Error

### ISSUE THREAD

**Issue by winkertk** [Xtraball/SiberianCMS#454]
<img width="402" alt="screen shot 2017-09-29 at 3 29 45 pm" src="https://user-images.githubusercontent.com/32384508/31051971-cc43a0ca-a6a9-11e7-87c9-7b8d780e17a4.png">

While descriptions has been filled.. But error still pop and won't save description.

**Comment by LikoV2** [comment]
Hi,

Do you still have the issue on the version 4.12.23 ? Thanks.

**Comment by winkertk** [comment]
Hi,
It's working fine on ver PE - v4.12.23. Thanks.
