### ISSUE TITLE
IOS not receiving push

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/SiberianCMS#456]
I can confirm the iOS APPS do not receive any push notifications. They dont even appear in the list. Received with Android.

**Comment by Spotcloudtk** [comment]
I confirm

**Comment by bluesnap-rock** [comment]
Yes no changes to the .pem - existing APPS - not receiving push notifications on iOS devices only.

**Comment by Spotcloudtk** [comment]
strange. it works for me

**Comment by Slicit** [comment]
Closing as inactive/probably fixed.
