### ISSUE TITLE
Icon Pack Social and Shop

### ISSUE THREAD

**Issue by Spotcloudtk** [Xtraball/SiberianCMS#459]
![185958-social-media-icons](https://user-images.githubusercontent.com/27977045/31072418-27071df2-a768-11e7-9ab9-a60306855a3f.png)
[download](https://www.spotcloud.tk/whmcs-bridge/download/)

**Comment by Slicit** [comment]
I'm pretty sure it's not the right place to share these icon packs :)
However ! it's really cool from you to share theses!

If you agree we look to upload these packs on our marketplace!

**Comment by Spotcloudtk** [comment]
ok

**Comment by Spotcloudtk** [comment]
if you create or many icon packs, do you give me Classifield? ehehehehe

**Comment by Slicit** [comment]
Nope! Also GitHub is not the good place to share your Icon Packs, have you thinked of creating a small website, or blog page for that ?

You can also join & share them on the Siberian FB Group
https://www.facebook.com/groups/617340045067269/

Thanks. Closing for clean-up purposes.
