### ISSUE TITLE
More than 180,000 iPhone apps won't be compatible with iOS 11

### ISSUE THREAD

**Issue by Vdvoem** [Xtraball/SiberianCMS#461]
With the release of iOS 11 on Tuesday, a long-predicted change will arrive with it: Apple will no longer support 32-bit apps.

You can read more here: http://www.businessinsider.com/apple-ios-11-32-bit-apps-compatibility-2017-8

What do you think about it?

**Comment by Slicit** [comment]
As we are using cordova, it's ok from almost 2015, IPA are 32/64bits ;)

**Comment by Vdvoem** [comment]
So this is not how it will affect our applications?
