### ISSUE TITLE
Gallery Module Only Importing 10 Images

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#465]
After upgrading to v4.12.16 (or it could have been since 4.12.15) I can't import more than 10 images via the Gallery module. In addition, when I attempt to edit the Gallery (Manage Content) I receive the error message "Cannot refresh row as parent is missing".

I'm using MAE v4.12.16.

**Comment by portalidea** [comment]
After upgrading...facebook gallery shows only 25 images

**Comment by rivman** [comment]
Also gallery show only 10 images and those images are not shown on Content (stand alone gallery).

**Comment by portalidea** [comment]
Facebook gallery now shows all images but no description.
The custom image gallery doesn't save image in the db

**Comment by clifton11221** [comment]
The update to 4.12.17 fixed my issue.

**Comment by Slicit** [comment]
Closing as fixed.
