### ISSUE TITLE
image got deleted in /var/tmp after any update/install

### ISSUE THREAD

**Issue by lsmod** [Xtraball/SiberianCMS#466]
Since 4.12.x installing / updating any module or layout, or updating the platform remove image from var/tmp. 
Considering that's the folder where images (sent through layout options using function: addSimpleImage) are going, it's pretty annoying for layout's having custom image.

**Comment by lsmod** [comment]
apk also got removed

**Comment by rivman** [comment]
The photo gallery images was also deleted upon upgrade. 
The gallery don’t show any images. Where those photos suppose to be (to looking after them in backups). My 6 clients lost all images in gallery, very disappointing.

**Comment by Vdvoem** [comment]
Hello!
I've already updated to SAE version - v4.12.16, but my clients did not have anything to do.

**Comment by Slicit** [comment]
Nope, var/tmp is, and should remain a Temporary folder, all images are first uploaded to it, but the must be copied elsewhere (in a persistent way).

**Comment by lsmod** [comment]
@Slicit 
In that case shouldn't images be uploaded somewhere else when using addSimpleImage function?

I mean for a module there is no problem to move image afterward withing the module controller. But in the case of a layout, form submission is pointing to application/customization_design_style/formoptions route. So there isn't really a way of moving the image in that case.

**Comment by lsmod** [comment]
Can't we have and addSimpleImage function with destination folder in option?
Or a specialized function for layout?

**Comment by Slicit** [comment]
the addSimpleImage doesn't work alone, you need the part in the save controller to handle images
see https://github.com/Xtraball/Siberian/blob/master/siberian/app/sae/modules/Job/controllers/PlaceController.php#L84

`Siberian_Feature::moveUploadedFile($this->getCurrentOptionValue(), Core_Model_Directory::getTmpDirectory()."/".$values["icon"]);` is what you are searching for, `var/tmp`is a temporary folder and should only be used for temporary storage!

**Comment by lsmod** [comment]
Hi,

I found that work around weeks ago (moving the uploaded file to an other directory). It add extra work of creating a layout controller and code duplication to save param in database (as it al-ready made by the controller responsable for application/customization_design_style/formoptions route). 
And if later the way layout param are stored is changed it will make layouts break. 
I think a better design would be to have a "media folder param" in layout option. 

Anyway the work around is working expect one details:
when displaying the layout form the image element (created by addSimpleImage) still look for the image in /var/tmp. Resulting in a 404 error soon as cache get cleared.

So I suggest add-in an option to addSimpleImage to tell where to look for the images. And Also a function to save feature param would avoid duplicated and enforce separation of concerns.
