### ISSUE TITLE
APK fails: Android SDK is marked for update

### ISSUE THREAD

**Issue by lampela** [Xtraball/SiberianCMS#468]
I have the latest version MAE.
Cron is running (marked green), required extensions also marked green in backoffice dashboard.

For some reason APK generation fails. It used to work, last time I used it about a year ago.

In backoffice Settings/Advanced/Cron there is red "Restart" button in System tasks/androidtools row. I push the button and I get in the top: "Android SDK is marked for update". 

I tested with several apps, the errors differ. One error is:

* What went wrong:
Execution failed for task ':CordovaLib:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

The other error is:
* What went wrong:
A problem occurred configuring root project 'myappname'.
> You have not accepted the license agreements of the following SDK components:
  [SDK Patch Applier v4].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

According to this thread: https://github.com/Xtraball/SiberianCMS/issues/268 I did this:
go inside var/apps/ionic/tools
delete the folder android-sdk
rm -rf android-sdk
then run
php -f sdk-updater.php

and cleared all the caches. But no help.

**Comment by Spotcloudtk** [comment]
For license resolve:

`mkdir "$ANDROID_HOME/licenses"
echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"`

**Comment by lampela** [comment]
And may I ask who might you be?
This reply isn’t in github.

Ystävällisesti - kind regards
- Katja

Katja Lampela
-----------------
Lieska-Tuotanto Oy - www.lieska.net
+358 10 2713 201, skype: katjalampela
kotisivut - sovellukset - printtimedia

**Comment by LikoV2** [comment]
Hi,

The fix you tried was for the license agreements. Now you should not have this issue. Regarding aapt, you have to install this:
–> Debian/Ubuntu:
apt-get install lib32stdc++6 lib32z1 lib32z1-dev

–> CentOS/Fedora:
yum install libstdc++.i686
yum install zlib.i686

**Comment by Indiaexcite** [comment]
I have the same issue after updating to MAE - v4.13.20
Will the above solution work for me?

As an alternative, I used to build manually in the android studio.
Once I updated the cms to MAE - v4.13.20 

Now Android Studio builds also failed.  Tried updating Android SDK. Yet appt plugin error persists.
Any guidance will be helpful.

Thank you.
Regards,
Venkat Chinniah
