### ISSUE TITLE
Database information error

### ISSUE THREAD

**Issue by onedayweb** [Xtraball/SiberianCMS#469]
Hello,

I have the **error** message when entering the **database** infos.
I looked in the **.htaccess** the **mod_rewrite** is enable, but still it's not working.
I contacted the host and they tell me that the **mod_rewrite** is always enable with them.

I have this message : 

(Sorry it's translated from french)

Blocking a Cross-Origin Request: The "Same Origin" policy does not allow you to view the remote resource located at https://fortunes.ch/test/installer/installation_database/check. Reason: The CORS "Access-Control-Allow-Origin" header is missing.

Thank you for your help

**Comment by Slicit** [comment]
Try to delete .htaccess, and copy htaccess.txt to .htaccess (there was probably a bad .htaccess by default, and it wasn't replaced by the Siberian one)

Let me know!

**Comment by onedayweb** [comment]
Hey there, thanks for the reply, I have tried another option.

I had wordpress on the website, so I removed it to see if it was that and it work now.

I don't really know why but it's seems that Siberian can't work with wordpress, but if someone have a solution to get it to work together i will gladly take it !

Thank you.

**Comment by Slicit** [comment]
Siberian is complete application in itself, having other websites can leads to lot of mis-configurations, it's better to have a single VPS or small server to install it.
