### ISSUE TITLE
Error in placing order in MCommerce

### ISSUE THREAD

**Issue by aftabaftab** [Xtraball/SiberianCMS#475]
Hi,

I am using SAE version 4.12.16.

When I select Cart > Proceed > Next, I always get the following error message:

ERROR
Please fill in the following fields
  - Phone

I have tried the following:
1. Giving a phone number by setting the Phone number field as mandatory
2. Setting the Phone number field as optional
3. Even hiding the setting the Phone number field

Any suggestions ?

**Comment by uygulamasepetim** [comment]
Check your PHP version. Don't use 7.1
