### ISSUE TITLE
Evaluate the application created on SAE - v4.12.16

### ISSUE THREAD

**Issue by Vdvoem** [Xtraball/SiberianCMS#476]
Hello! Evaluate the application created on SAE - v4.12.16
created it 5 days)
https://armbooking.ru/overview/

In the archive of Android APK
[armbooking_1_android_source-release.zip](https://github.com/Xtraball/SiberianCMS/files/1385317/armbooking_1_android_source-release.zip)
![default](https://user-images.githubusercontent.com/30751163/31583461-4c69c5d0-b1be-11e7-802e-3ae5ed17ac53.png)

**Comment by aftabaftab** [comment]
Hi,

Sorry I don't understand Russian. Otherwise would have given a feedback.

**Comment by Vdvoem** [comment]
Will be with us in Russia, I invite you to visit us in Tyumen, fish )

**Comment by Slicit** [comment]
@Vdvoem please do not use the GitHub for marketing purpose, this does not follow the guidelines.
