### ISSUE TITLE
Offline content download stuck at 98%

### ISSUE THREAD

**Issue by winkertk** [Xtraball/SiberianCMS#479]
Is anyone getting the same as fresh installation get stuck on offline content getting stuck at 98%
![screenshot_2017-10-18-12-20-19](https://user-images.githubusercontent.com/32384508/31711179-eb0879da-b429-11e7-97b8-8e87b3d82301.png)

**Comment by gonzoradio** [comment]
I get the same thing. Haven't found a solution yet.

**Comment by userdevel** [comment]
Any news?

**Comment by winkertk** [comment]
Issue has been resolve after new updates
