### ISSUE TITLE
Folder not opening if have more than 12-15 pages inside

### ISSUE THREAD

**Issue by singfa** [Xtraball/SiberianCMS#483]
Hello, 

I have the last version of MAE - v4.12.16
After the last 4-5 updates to arrive to this last version my folders which have 20-21 pages don't want to display anymore this pages. I have or a white page or display the background image and the endless loading icon.
I tried to rebuild the app and install it on my android phone but i have the same issue both on the phone and in the editor too.

**Comment by Vdvoem** [comment]
Hello!
Update to version - 4.12.17, I have more than 100 pages in the folder, all open without problems.

**Comment by singfa** [comment]
I updated to 4.12.17 version but unfortunately i have the same issue.

**Comment by clifton11221** [comment]
@Vdvoem - What version of Siberian are you using?

**Comment by Vdvoem** [comment]
I have SAE - v4.12.17

**Comment by singfa** [comment]
my version is for MAE

**Comment by Vdvoem** [comment]
And what is the difference between the folders? This is standard functionality)

**Comment by Vdvoem** [comment]
Here is an example of a post-production pack https://play.google.com/store/apps/details?id=en.armbooking.androidoverview

**Comment by singfa** [comment]
The link don't work.

**Comment by Vdvoem** [comment]
I'm sorry.
https://play.google.com/store/apps/details?id=en.armbooking.androidoverview

**Comment by Vdvoem** [comment]
[https://play.google.com/store/apps/details?id=ru.armbooking.androidoverview](url)

**Comment by Vdvoem** [comment]
`https://play.google.com/store/apps/details?id=ru.armbooking.androidoverview`

**Comment by Slicit** [comment]
The actual folder has some issues when used with lot of features, there will be an update in 4.12.24
