### ISSUE TITLE
Error message when sending image in Forms Page

### ISSUE THREAD

**Issue by bcannon123** [Xtraball/SiberianCMS#484]
When creating a form, and setting the "form field type" to Image, two problems occur:

1) When clicking the "Add Image" button.... Only two options appear (Import From Library) and (Cancel).  
I believe it should be showing (Take Photo) (Photo Library) (iCloud) and (Cancel). 
It is only when the (Import from library) link is pressed, that the other options appear. 

2) When adding an image and clicking (Send) we get the following error message; "An unknown error occurred". 

Thanks for the support,
Bill

**Comment by LikoV2** [comment]
Hi Bill,

Please check if upload_max_filesize is set to 100MB minimum.
