### ISSUE TITLE
Gallery Doesn't Save Imported Images

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#485]
Upon creating a Gallery and importing images into "My Gallery", the Gallery doesn't save the images. The import process goes fine but after clicking "Save", nothing is there.

I'm using MAE v4.12.17

**Comment by clifton11221** [comment]
FYI - Support let me know that the issue only affected a very limited number of Siberian installs.  Today they fixed my issue (not exactly sure how).

**Comment by Slicit** [comment]
Fixed in 4.12.18 ;)
