### ISSUE TITLE
ERROR - MISSING BACK BUTTON.

### ISSUE THREAD

**Issue by euroonesistemi** [Xtraball/SiberianCMS#487]
To reproduce.
Use Layout 9.
Use a "Folder item" to first item in this layout.
Add more item to the first Folder ( custom page ).
Now, start App.
You see the list of Item added to Folder in the first screen.
Click on first item.
**Now impossible to turn back. ( ERROR )**
If you press button back of Phone, APP exit.
I add Video at this link.
i add Photo here.
![screenshot_20171027-173412](https://user-images.githubusercontent.com/1251660/32112715-4d0865f8-bb3e-11e7-9521-ad8465b02168.jpg)
![screenshot_20171027-173424](https://user-images.githubusercontent.com/1251660/32112724-506b1984-bb3e-11e7-82e4-21c12856bdf0.jpg)
To see in action, watch video.
https://drive.google.com/open?id=0B9nAOlTDyxagcFlxMmFmZTZLeDQ

**Comment by Spotcloudtk** [comment]
Ciao, si sto modificando il template anche io, purtroppo questo template non ha il tasto indietro. Appena implementerò il back lo pubblicherò sul mio sito

**Comment by Slicit** [comment]
Issue has been fixed in latest updates, please update accordingly! Thanks
