### ISSUE TITLE
What is the version of Woocommerce now?

### ISSUE THREAD

**Issue by Vdvoem** [Xtraball/SiberianCMS#489]
Hello!
Tell me what is the version of the module Woocommerce?

**Comment by clifton11221** [comment]
The current download version of WooCommerce is 1.1.1

**Comment by Vdvoem** [comment]
Tell me, update will be?
And then in version 1.1.1 there are so many bugs )

**Comment by clifton11221** [comment]
Not sure... You would have to send a note to Support listing the bugs in detail.

**Comment by Vdvoem** [comment]
Hello!
Yes already wrote to them, there is no sense, we already have customers swear.

**Comment by Vdvoem** [comment]
I will pay for the work of Ravindre, that he would remove all the bugs, you as developers can help, you need to enable authorization in this module through facebook and vk.com ?

**Comment by clifton11221** [comment]
I am not a developer of Siberian. I use it like you...

**Comment by Vdvoem** [comment]
We completely rewrote the module, removed all the bugs and changed the appearance, how do you?
![default](https://user-images.githubusercontent.com/30751163/32479489-405a00c2-c3b4-11e7-9ba2-4c4d71a0c0c9.png)

**Comment by clifton11221** [comment]
I like it... Please share!!!

**Comment by Vdvoem** [comment]
By the way, this is how this module works now
https://play.google.com/store/apps/details?id=ru.trcklv.androidoverview

**Comment by portalidea** [comment]
Please Share!

**Comment by Vdvoem** [comment]
Write to me on the mail vdvoem.com@mail.ru discuss )

**Comment by clifton11221** [comment]
Email sent...

**Comment by Vdvoem** [comment]
Answered

**Comment by Vdvoem** [comment]
Hello everyone, I post the module with all the corrections and changes, who needs it. 
[woocommerce.1.1.8.zip](https://github.com/Xtraball/SiberianCMS/files/1554931/woocommerce.1.1.8.zip)

**Comment by Slicit** [comment]
Please do not share publicly modules that are under commercial licence, you can always fix it for your client as a service if he own the licence, but not sharing it here!
