### ISSUE TITLE
Title position on android devices

### ISSUE THREAD

**Issue by Alboorii** [Xtraball/SiberianCMS#49]
Hi!

In the app pages, When i enter from iPhone the title is centred
But if i enter from android device its not.

Regards

**Comment by applimoby** [comment]
same problem!

**Comment by SiberianCMS** [comment]
I confirm the issue

![screenshot_20160716-234250](https://cloud.githubusercontent.com/assets/7977082/16897722/0c806a48-4bba-11e6-9a75-8fd1990d5acc.png)

**Comment by alexyves** [comment]
Titles are generally aligned left on Android, we will not change it, but may consider it as an option.
