### ISSUE TITLE
Bug - Custom Page as Iframe cannot write anything. Just as App

### ISSUE THREAD

**Issue by erol55** [Xtraball/SiberianCMS#490]
The Problem is, if i use Custom Page as Iframe, i cannot write anything in this. The keyboard is open but if i give anything, the app crashs.

Play Console says :
Null Pointer exception
Webviewclass...

In them a lot of problems. The app im playstore with name "Radyo Yaman"
I try any pages as iframe (shoutbox & a email Form) all the Same. Cannot write anything

https://ibb.co/m0HzLw
https://ibb.co/cbEPnb

**Comment by Slicit** [comment]
related to cordova webview, we can't do anything.
