### ISSUE TITLE
Installation ok up until creating application

### ISSUE THREAD

**Issue by imylomylo** [Xtraball/SiberianCMS#491]
Hi

From git clone.
The install goes well on subdomain up until application creation @ build.businessapps.com.au
The first/admin user is created.
The first app doesn't seem to work.
The AJAX call has the spinner with "Creating application" and it returns quickly but nothing.  I can't see anything in the logs but in the console it looks like a 400 error is returned.

I refresh the page and it gives me the login screen at /admin/account/login.  I can log in ok.
But it redirects to an error message (for security reasons error messages are not shown).

I change the config, environment to "development" and the error message is:

`Error log: error__5a01c38b466e6.log

Stack Trace:

Fatal Error: 
ArrayObject Object
(
    [storage:ArrayObject:private] => Array
        (
            [exception] => Zend_Db_Statement_Exception Object
                (
                    [_previous:Zend_Exception:private] => 
                    [message:protected] => SQLSTATE[HY093]: Invalid parameter number: no parameters were bound
                    [string:Exception:private] => 
                    [code:protected] => 0
                    [file:protected] => /var/www/vhosts/businessapps.com.au/build.businessapps.com.au/lib/Zend/Db/Statement/Pdo.php
                    [line:protected] => 234
                    [trace:Exception:private] => Array
                        (
                            [0] => Array
                                (
                                    [file] => /var/www/vhosts/businessapps.com.au/build.businessapps.com.au/lib/Zend/Db/Statement.php
                                    [line] => 303
                                    [function] => _execute
                                    [class] => Zend_Db_Statement_Pdo
                                    [type] => ->
                                    [args] => Array
                                        (
                                            [0] => Array
                                                (
                                                )

                                        )

                                )

                            [1] => Array
                                (
                                    [file] => /var/www/vhosts/businessapps.com.au/build.businessapps.com.au/lib/Zend/Db/Adapter/Abstract.php
                                    [line] => 480
                                    [function] => execute
                                    [class] => Zend_Db_Statement
                                    [type] => ->
                                    [args] => Array
                                        (
                                            [0] => Array
                                                (
                                                )

                                        )

                                )

                            [2] => Array
                                (
                                    [file] => /var/www/vhosts/businessapps.com.au/build.businessapps.com.au/lib/Zend/Db/Adapter/Pdo/Abstract.php
                                    [line] => 238
                                    [function] => query
                                    [class] => Zend_Db_Adapter_Abstract
                                    [type] => ->
                                    [args] => Array
                                        (
                                            [0] => SELECT `aao`.* FROM `application_acl_option` AS `aao` WHERE (aao.app_id = ?) AND (aao.admin_id = '1')
                                            [1] => Array
                                                (
                                                )

                                        )

                                )

                            [3] => Array
                                (
                                    [file] => /var/www/vhosts/businessapps.com.au/build.businessapps.com.au/lib/Siberian/Db/Adapter/Pdo/Mysql.php
                                    [line] => 11
                                    [function] => query
                                    [class] => Zend_Db_Adapter_Pdo_Abstract
                                    [type] => ->
                                    [args] => Array
                                        (
                                            [0] => Zend_Db_Table_Select Object
                                                (
                                                    [_info:protected] => Array
                                                        (
                                                            [schema] => 
                                                            [name] => application_acl_option
                                                            [cols] => Array
                                                                (
                                                                    [0] => application_acl_option_id
                                                                    [1] => app_id
                                                                    [2] => admin_id
                                                                    [3] => value_id
                                                                    [4] => resource_code
                                                                )

                                                            [primary] => Array
                                                                (
                                                                    [1] => application_acl_option_id
                                                                )

                                                            [metadata] => Array
                                                                (
                                                                    [application_acl_option_id] => Array
                                                                        (
                                                                            [SCHEMA_NAME] => 
                                                                            [TABLE_NAME] => application_acl_option
                                                                            [COLUMN_NAME] => application_acl_option_id
                                                                            [COLUMN_POSITION] => 1
                                                                            [DATA_TYPE] => int
                                                                            [DEFAULT] => 
                                                                            [NULLABLE] => 
                                                                            [LENGTH] => 
                                                                            [SCALE] => 
                                                                            [PRECISION] => 
                                                                            [UNSIGNED] => 1
                                                                            [PRIMARY] => 1
                                                                            [PRIMARY_POSITION] => 1
                                                                            [IDENTITY] => 1
                                                                        )

                                                                    [app_id] => Array
                                                                        (
                                                                            [SCHEMA_NAME] => 
                                                                            [TABLE_NAME] => application_acl_option
                                                                            [COLUMN_NAME] => app_id
                                                                            [COLUMN_POSITION] => 2
                                                                            [DATA_TYPE] => int
                                                                            [DEFAULT] => 
                                                                            [NULLABLE] => 
                                                                            [LENGTH] => 
                                                                            [SCALE] => 
                                                                            [PRECISION] => 
                                                                            [UNSIGNED] => 1
                                                                            [PRIMARY] => 
                                                                            [PRIMARY_POSITION] => 
                                                                            [IDENTITY] => 
                                                                        )

                                                                    [admin_id] => Array
                                                                        (
                                                                            [SCHEMA_NAME] => 
                                                                            [TABLE_NAME] => application_acl_option
                                                                            [COLUMN_NAME] => admin_id
                                                                            [COLUMN_POSITION] => 3
                                                                            [DATA_TYPE] => int
                                                                            [DEFAULT] => 
                                                                            [NULLABLE] => 
                                                                            [LENGTH] => 
                                                                            [SCALE] => 
                                                                            [PRECISION] => 
                                                                            [UNSIGNED] => 1
                                                                            [PRIMARY] => 
                                                                            [PRIMARY_POSITION] => 
                                                                            [IDENTITY] => 
                                                                        )

CUT SHORT FOR ISSUE
`

Be nice to check out.
Thanks
Mylo

**Comment by marcelser** [comment]
Interesting, having exactly the same error here. Could not create application because it returns status 400 and when I reload I get also this Zend database error when I try to login. Did you find a solution meanwhile or will this be fixed because obviously you're not alone!

**Comment by marcelser** [comment]
update: I used web developer in chrome to see what the reponse of the 400 Bad request is and that clearly shows that it is a bug in current release, it says:

{"message":"AdminId is required to save the Application."}

But admin has just been created in previous step

**Comment by Slicit** [comment]
We fixed lot of changes between regular packages and github, 

Thus the new Github is here https://github.com/Xtraball/Siberian

Move there for your updates and next installations, thanks!

**Comment by nikhilborwankar** [comment]
I'm struggling with exactly the same error. Any assistance would be greatly appreciated. Thanks in advance.

**Comment by DiabolicAngeL** [comment]
Same here. Doesn't work after latest update
