### ISSUE TITLE
Places - Updating the Button with an Image

### ISSUE THREAD

**Issue by uygulamasepetim** [Xtraball/SiberianCMS#492]
Hi,

When adding button(s) to Places first time, everything works ok. But when I want to update a button with a new Image, saving doesn't result to a green validation and after refreshing the page the button(s) disappear.

**Comment by clifton11221** [comment]
Which buttons are you referring to?  Please send screenshots...

**Comment by uygulamasepetim** [comment]
![scr01](https://user-images.githubusercontent.com/33625164/32736751-4d9638e2-c8a9-11e7-8eda-aa3eb9b17418.png)
![scr02](https://user-images.githubusercontent.com/33625164/32736754-4f3bf0ba-c8a9-11e7-8c5e-a4846e162a4b.png)
![scr03](https://user-images.githubusercontent.com/33625164/32736759-533c3abc-c8a9-11e7-92f5-6965bcdc1f96.png)
![scr05](https://user-images.githubusercontent.com/33625164/32736763-557832d6-c8a9-11e7-90f9-9832a5956832.png)

**Comment by Slicit** [comment]
This issue have been fixed in the latest releases, please update accordingly.

Thanks.

**Comment by uygulamasepetim** [comment]
This is my current version : PE - v4.12.19  and it doesn't look like it is fixed. Can you please tell me in which version it has been fixed?
