### ISSUE TITLE
Need help with adding hash key Facebook

### ISSUE THREAD

**Issue by Vdvoem** [Xtraball/SiberianCMS#494]
Hello, can anyone tell me how to get key hashes to track Facebook statistics how many downloaded applications?

**Comment by Vdvoem** [comment]
Hello everyone, tell me how to fix it, I created a hash key, but in Facebook says that: events in sdk are not configured
Do not know how to fix it?

**Comment by Slicit** [comment]
Siberian doesn't support Facebook tracking!
