### ISSUE TITLE
Icecast streams NOT WORKING since Shoutcast fix //

### ISSUE THREAD

**Issue by rogerdavis198** [Xtraball/SiberianCMS#495]
Hi Icecast or any stream with a mountpoint has been broken since the shoutcast fix can we please take this out the player ';' as it will stop any mountpoint, shoutcast just needs the port without a mountpoint ...

###/////if it's only adding a ';' at the end to force stream & not HTTP Landin~///#

I wouldnt mind but I am running a fully paid for MAE version and still we have this bug since 

Release Notes 4.12.8
All versions - Aug 18, 2017
Debug
Feature > Radio

Fixes SHOUTCast streams not working when trailing `/;` is missing.
so I am even having to run 4.12.7 due to this bug I can not update, its a shame as before you could run opus and aac streams with this player.

Cheers

**Comment by rogerdavis198** [comment]
can we not have a switch added so we can switch ';'  at the end of the stream ie for port (shoutcast) or
mounted streams such as icecast to use without the ';'  at the end as that would keep your shoutcast fix and add the icecast or mounted stream back into the mix too. thanks

**Comment by rogerdavis198** [comment]
This has got to be a bug some place else as I edit RadioController.php manualy and a copy of a working script and it will only do shoutcast ?? over to you fella.

**Comment by Slicit** [comment]
closing as fixed! firewall issue

**Comment by rogerdavis198** [comment]
Just a heads up on this Bug as is not firewall ??

After checking out the new player the problem was the new player had not been updated in siberiancms 

I installed a separate single system and copied the new php player and it works fine so this was an update issue and most likely others with same problem should check there one too, working copy below of new player and old one below U/S after 4.12.7.

There is also a bug in siberian cms more a missing switch to tell android 7 and 8 to bypass battery optimization otherwise unless you tell everyone to turn it off and possibly also the wifi saving the player will not keep playing after max 5 mins so we need to address this problem guys..

working
<?php

/**
 * Class Radio_Mobile_RadioController
 */
class Radio_Mobile_RadioController extends Application_Controller_Mobile_Default {

    /**
     * @param $radio
     * @return array
     */
    public function _toJson($radio){
        $json = array(
            'url' => addslashes($radio->getData('link')),
            'title' => $radio->getTitle(),
            'background' => $this->getRequest()->getBaseUrl() .
                '/images/application' . $radio->getBackground(),
        );

        return $json;
    }

    /**
     * Find action
     */
    public function findAction() {
        if ($valueId = $this->getRequest()->getParam('value_id')) {
            try {
                $radio = (new Radio_Model_Radio())
                    ->find([
                        'value_id' => $valueId
                    ]);

                // Fix for shoutcast, force stream!
                $contentType = Siberian_Request::testStream($this->getData('link'));
                if(!in_array(explode('/', $contentType)[0], ['audio']) &&
                    !in_array($contentType, ['application/ogg'])) {
                    if(strrpos($this->getData('link'), ';') === false) {
                        $this->setData('link', $this->getData('link') . '/;');
                    }
                }

                $data = [
                    'radio' => $this->_toJson($radio)
                ];
            } catch (Exception $e) {
                $data = [
                    'error' => true,
                    'message' => $e->getMessage()
                ];
            }
        } else {
            $data = [
                'error' => true,
                'message' => __('An error occurred while loading. Please try again later.')
            ];
        }

        $this->_sendJson($data);
    }

}


non working below


<?php

class Radio_Mobile_RadioController extends Application_Controller_Mobile_Default {

    public function _toJson($radio){
        $json = array(
            "url" => $url = addslashes($radio->getLink()),
            'title' => $radio->getTitle()
        );

        return $json;
    }

    public function findAction() {

        if($value_id = $this->getRequest()->getParam('value_id')) {
            
            try {
                
                $radio_repository = new Radio_Model_Radio();
                $radio = $radio_repository->find(array('value_id' => $value_id));

                if(substr($radio->getLink(), -1) == "/") {
                    $stream_tag = ";";
//                    $stream_tag = ";stream.nsv&type=mp3";
                } else {
                    if(mb_stripos($radio->getLink(), "/", 8) > 0) {
                        $stream_tag = "";
//                        $stream_tag = "?stream.nsv&type=mp3";
                    } else {
//                        $stream_tag = "/;stream.nsv&type=mp3";
                        $stream_tag = "/;";
                    }
                }

                $radio->setLink($radio->getLink().$stream_tag);

                $data = array("radio" => $this->_toJson($radio));
            }
            catch(Exception $e) {
                $data = array('error' => 1, 'message' => $e->getMessage());
            }

        } else {
            $data = array('error' => 1, 'message' => $this->_("An error occurred while loading. Please try again later."));
        }

        $this->_sendHtml($data);

    }

}

**Comment by rogerdavis198** [comment]
NON WORKING

<?php

class Radio_Mobile_RadioController extends Application_Controller_Mobile_Default {

    public function _toJson($radio){
        $json = array(
            "url" => $url = addslashes($radio->getLink()),
            'title' => $radio->getTitle()
        );

        return $json;
    }

    public function findAction() {

        if($value_id = $this->getRequest()->getParam('value_id')) {
            
            try {
                
                $radio_repository = new Radio_Model_Radio();
                $radio = $radio_repository->find(array('value_id' => $value_id));

                if(substr($radio->getLink(), -1) == "/") {
                    $stream_tag = ";";
//                    $stream_tag = ";stream.nsv&type=mp3";
                } else {
                    if(mb_stripos($radio->getLink(), "/", 8) > 0) {
                        $stream_tag = "";
//                        $stream_tag = "?stream.nsv&type=mp3";
                    } else {
//                        $stream_tag = "/;stream.nsv&type=mp3";
                        $stream_tag = "/;";
                    }
                }

                $radio->setLink($radio->getLink().$stream_tag);

                $data = array("radio" => $this->_toJson($radio));
            }
            catch(Exception $e) {
                $data = array('error' => 1, 'message' => $e->getMessage());
            }

        } else {
            $data = array('error' => 1, 'message' => $this->_("An error occurred while loading. Please try again later."));
        }

        $this->_sendHtml($data);

    }

}
