### ISSUE TITLE
Link Module: Webview (Navbar) Not Working On Android

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#497]
With the Link module, when opening a link on Android the navbar is missing.  The page opens in a browser window with no way to get back to the app. 

On iOS it works properly.

I'm using Siberian MAE 4.12.18.

**Comment by Vdvoem** [comment]
That you need a code to edit, write me a post vdvoem.com@mail.ru I will help )

**Comment by clifton11221** [comment]
Message sent.

You should also post it here so it will be a permanent fix.

**Comment by clifton11221** [comment]
Does anyone know of a hotfix for this until a permanent fix is added to the build?

**Comment by clifton11221** [comment]
Any confirmation that this is a bug?  I had a couple of different people test on Android and it's not working.

**Comment by LikoV2** [comment]
Hi,

It's a bug, unfortunately we do not have a hot fix yet, and if we find it, we will update Siberian.

**Comment by Marcapps888** [comment]
Hello,
Is it possible to make the gyroscope works on iOS using a deep link in the source code module? Or allow the possibility to link the "Webview (Navbar)" module using "in-app" inside the source code module as the "links" module?

**Comment by Indiaexcite** [comment]
//Link Module: Webview (Navbar) Not Working On Android//

Is there any solution?  No way coming back to APP if links are clicked.  Please update.  Thanks.

**Comment by LikoV2** [comment]
Hi,

The update will come tomorrow (4.13.7) and will fix this issue.

**Comment by Indiaexcite** [comment]
I need to re build apk. right?
Thanks buddy

**Comment by w3sbari** [comment]
if hide navbar, there is a solution for insert a closed javascript? more user don't understand that they can go back.

**Comment by Slicit** [comment]
It's know incorrect naming of the options.

Options are not consistent across Android/iOS and thus never worked as expected, it's scheduled to be fixed in 4.18.0 when iOS is updated with the CustomTabs plugin.

**Comment by w3sbari** [comment]
but is there a way, if I set hide navbar in the link form, to show a back in the webview page?
