### ISSUE TITLE
translation not fetched for layout

### ISSUE THREAD

**Issue by lsmod** [Xtraball/SiberianCMS#498]
This problem occur on some 4.12.9 platform.
Translations have been saved in backoffice for French and English.

But on loading of the app: 
http://host.com/xxxx/front/mobile/loadv3?sb-token=484848648646464684 only send translation along with layout parameter for english language. None are sent for FR (when editor set to French or on mobile device where it is default language).

Working smoothly with the exact same layout & platform version on other domains. I Tried rebuild manifest clearing cache not making a difference.

**Comment by LikoV2** [comment]
Hi,

Do you still have the issue on 4.12.23 ? Are the other domains in the same server ?

**Comment by lsmod** [comment]
Good question. Will check with the client whom reported that issue.
Nope other domain were on different server.

**Comment by lsmod** [comment]
Just checked on client's platform it seems to be working fine now :+1: 
What's was the issue ?

**Comment by LikoV2** [comment]
Hi,

Not sure, but it could be from the app manifest broken, or a cache issue. Updating helps, as it will rebuild the manifest and clear the cache.
