### ISSUE TITLE
BUG on iOS push notifications

### ISSUE THREAD

**Issue by franciscocsysteames** [Xtraball/SiberianCMS#50]
When a push notification is sent, recived the error "Please provide a certificate.". In the database, I can see that the message has app_id 1, however in push_certificate the certificate has app_id = 0. If I change in push_certificate app_id = 1 gives the following error:

string(9) "Erreurs :"
array(1) {
  [24] => object(Exception)#185 (7) {
    ["message":protected] => string(0) ""
    ["string":"Exception":private] => string(0) ""
    ["code":protected] => int(0)
    ["file":protected] => string(100) "/var/www/vhosts/appautosegui.systeamcloud.com/httpdocs/app/sae/modules/Push/Model/Iphone/Message.php"
    ["line":protected] => int(83)
    ["trace":"Exception":private] => array(9) {
      [0] => array(6) {
        ["file"] => string(100) "/var/www/vhosts/appautosegui.systeamcloud.com/httpdocs/app/sae/modules/Push/Model/Iphone/Message.php"
        ["line"] => int(98)
        ["function"] => string(16) "createConnection"
        ["class"] => string(25) "Push_Model_Iphone_Message"
        ["type"] => string(2) "->"
        ["args"] => array(0) {
        }
      }
      [1] => array(6) {
        ["file"] => string(93) "/var/www/vhosts/appautosegui.systeamcloud.com/httpdocs/app/sae/modules/Push/Model/Message.php"
        ["line"] => int(116)
        ["function"] => string(4) "push"
        ["class"] => string(25) "Push_Model_Iphone_Message"
        ["type"] => string(2) "->"
        ["args"] => array(0) {
        }
      }
      [2] => array(6) {
        ["file"] => string(109) "/var/www/vhosts/appautosegui.systeamcloud.com/httpdocs/app/sae/modules/Push/controllers/MessageController.php"
        ["line"] => int(30)
        ["function"] => string(4) "push"
        ["class"] => string(18) "Push_Model_Message"
        ["type"] => string(2) "->"
        ["args"] => array(0) {
        }
      }
      [3] => array(6) {
        ["file"] => string(85) "/var/www/vhosts/appautosegui.systeamcloud.com/httpdocs/lib/Zend/Controller/Action.php"
        ["line"] => int(516)
        ["function"] => string(10) "sendAction"
        ["class"] => string(22) "Push_MessageController"
        ["type"] => string(2) "->"
        ["args"] => array(0) {
        }
      }
      [4] => array(6) {
        ["file"] => string(98) "/var/www/vhosts/appautosegui.systeamcloud.com/httpdocs/lib/Zend/Controller/Dispatcher/Standard.php"
        ["line"] => int(308)
        ["function"] => string(8) "dispatch"
        ["class"] => string(22) "Zend_Controller_Action"
        ["type"] => string(2) "->"
        ["args"] => array(1) {
          [0] => &string(10) "sendAction"
        }
      }
      [5] => array(6) {
        ["file"] => string(84) "/var/www/vhosts/appautosegui.systeamcloud.com/httpdocs/lib/Zend/Controller/Front.php"
        ["line"] => int(954)
        ["function"] => string(8) "dispatch"
        ["class"] => string(35) "Zend_Controller_Dispatcher_Standard"
        ["type"] => string(2) "->"
        ["args"] => array(2) {
          [0] => object(Siberian_Controller_Request_Http)#35 (26) {
            ["_is_application":protected] => bool(false)
            ["_language_code":protected] => NULL
            ["_force_language_code":protected] => bool(false)
            ["_is_native":protected] => bool(false)
            ["_use_application_key":protected] => bool(false)
            ["_white_label_editor":protected] => object(Core_Model_Default)#30 (7) {
              ["_db_table":protected] => NULL
              ["_is_cachable":protected] => bool(true)
              ["_action_view":protected] => string(4) "find"
              ["_data":protected] => array(1) {
                ["is_active"] => bool(false)
              }
              ["_orig_data":protected] => array(0) {
              }
              ["_specific_import_data":protected] => array(0) {
              }
              ["_mandatory_columns":protected] => array(0) {
              }
            }
            ["_application":protected] => NULL
            ["_application_key":protected] => bool(false)
            ["_ionic_path":protected] => bool(false)
            ["_is_installing":protected] => bool(false)
            ["_mediaUrl":protected] => NULL
            ["_paramSources":protected] => array(2) {
              [0] => string(4) "_GET"
              [1] => string(5) "_POST"
            }
            ["_requestUri":protected] => string(18) "/push/message/send"
            ["_baseUrl":protected] => string(40) "http://www.appautosegui.systeamcloud.com"
            ["_basePath":protected] => NULL
            ["_pathInfo":protected] => string(18) "/push/message/send"
            ["_params":protected] => array(3) {
              ["module"] => string(4) "push"
              ["controller"] => string(7) "message"
              ["action"] => string(4) "send"
            }
            ["_rawBody":protected] => NULL
            ["_aliases":protected] => array(0) {
            }
            ["_dispatched":protected] => bool(true)
            ["_module":protected] => string(4) "push"
            ["_moduleKey":protected] => string(6) "module"
            ["_controller":protected] => string(7) "message"
            ["_controllerKey":protected] => string(10) "controller"
            ["_action":protected] => string(4) "send"
            ["_actionKey":protected] => string(6) "action"
          }
          [1] => object(Zend_Controller_Response_Http)#60 (8) {
            ["_body":protected] => array(0) {
            }
            ["_exceptions":protected] => array(0) {
            }
            ["_headers":protected] => array(0) {
            }
            ["_headersRaw":protected] => array(0) {
            }
            ["_httpResponseCode":protected] => int(200)
            ["_isRedirect":protected] => bool(false)
            ["_renderExceptions":protected] => bool(false)
            ["headersSentThrowsException"] => bool(true)
          }
        }
      }
      [6] => array(6) {
        ["file"] => string(72) "/var/www/vhosts/appautosegui.systeamcloud.com/httpdocs/app/Bootstrap.php"
        ["line"] => int(252)
        ["function"] => string(8) "dispatch"
        ["class"] => string(21) "Zend_Controller_Front"
        ["type"] => string(2) "->"
        ["args"] => array(1) {
          [0] => object(Siberian_Controller_Request_Http)#35 (26) {
            ["_is_application":protected] => bool(false)
            ["_language_code":protected] => NULL
            ["_force_language_code":protected] => bool(false)
            ["_is_native":protected] => bool(false)
            ["_use_application_key":protected] => bool(false)
            ["_white_label_editor":protected] => object(Core_Model_Default)#30 (7) {
              ["_db_table":protected] => NULL
              ["_is_cachable":protected] => bool(true)
              ["_action_view":protected] => string(4) "find"
              ["_data":protected] => array(1) {
                ["is_active"] => bool(false)
              }
              ["_orig_data":protected] => array(0) {
              }
              ["_specific_import_data":protected] => array(0) {
              }
              ["_mandatory_columns":protected] => array(0) {
              }
            }
            ["_application":protected] => NULL
            ["_application_key":protected] => bool(false)
            ["_ionic_path":protected] => bool(false)
            ["_is_installing":protected] => bool(false)
            ["_mediaUrl":protected] => NULL
            ["_paramSources":protected] => array(2) {
              [0] => string(4) "_GET"
              [1] => string(5) "_POST"
            }
            ["_requestUri":protected] => string(18) "/push/message/send"
            ["_baseUrl":protected] => string(40) "http://www.appautosegui.systeamcloud.com"
            ["_basePath":protected] => NULL
            ["_pathInfo":protected] => string(18) "/push/message/send"
            ["_params":protected] => array(3) {
              ["module"] => string(4) "push"
              ["controller"] => string(7) "message"
              ["action"] => string(4) "send"
            }
            ["_rawBody":protected] => NULL
            ["_aliases":protected] => array(0) {
            }
            ["_dispatched":protected] => bool(true)
            ["_module":protected] => string(4) "push"
            ["_moduleKey":protected] => string(6) "module"
            ["_controller":protected] => string(7) "message"
            ["_controllerKey":protected] => string(10) "controller"
            ["_action":protected] => string(4) "send"
            ["_actionKey":protected] => string(6) "action"
          }
        }
      }
      [7] => array(6) {
        ["file"] => string(79) "/var/www/vhosts/appautosegui.systeamcloud.com/httpdocs/lib/Zend/Application.php"
        ["line"] => int(366)
        ["function"] => string(3) "run"
        ["class"] => string(9) "Bootstrap"
        ["type"] => string(2) "->"
        ["args"] => array(0) {
        }
      }
      [8] => array(6) {
        ["file"] => string(64) "/var/www/vhosts/appautosegui.systeamcloud.com/httpdocs/index.php"
        ["line"] => int(49)
        ["function"] => string(3) "run"
        ["class"] => string(16) "Zend_Application"
        ["type"] => string(2) "->"
        ["args"] => array(0) {
        }
      }
    }
    ["previous":"Exception":private] => NULL
  }
}
done

**Comment by franciscocsysteames** [comment]
i solved the problem, so there are a bug because when you save the certificated in the database the app_id save 0 instead of 1

**Comment by SiberianCMS** [comment]
Let see & resolve asap :)

**Comment by SiberianCMS** [comment]
Fixed in 4.2
