### ISSUE TITLE
Radio

### ISSUE THREAD

**Issue by alisgold** [Xtraball/SiberianCMS#501]
The problem with the radio function does not work on IOS in the background
Put different links to threads that have updated the version in the AppStore, the error persists

**Comment by clifton11221** [comment]
Please post the radio stream you're using so it can be tested.

**Comment by alisgold** [comment]
https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=1314785163&mt=8Use the links to the stream:
1. http://62.210.36.44:9110
2. http://ep128.hostingradio.ru:8030/ep128
3. http://icecast.russkoeradio.cdnvideo.ru/rr.mp3
4. http://ic2.101.ru:8000/v3_1

**Comment by Slicit** [comment]
Radio & Background modes are fixed in latest version 4.13+ for iOS.
