### ISSUE TITLE
Installing on localhost (Ubuntu)

### ISSUE THREAD

**Issue by guit4eva** [Xtraball/SiberianCMS#502]
Hey guys,

I have been trying to get Siberian up and running for 2 days now, hoping you can assist me. Where I currently am is the following:

1) Installed a fresh copy of Ubuntu Gnome
2) Installed Apache, MySQL and PHP
3) Localhost works successfully
4) Tried copying index.php of Siberian Zip into /var/www/html and running the install
 - After clicking install, it starts downloading the goes to HTTP ERROR 500
5) Tried downloading from Github and unzipping all files to /var/www/html
- Navigating to localhost/siberian results in HTTP ERROR 500

Hoping that you can assist! Thanks so much in advance!

**Comment by Slicit** [comment]
Check if you have installed every requirements and all the configurations

https://developers.siberiancms.com/documentation/

**Comment by deni1984** [comment]
I had the same problem. I tried to install siberian on localhost but it shows an error. I read on Siberian FAQ that 7.0 or 7.2 is needed. So I unistalled my 7.3 version of xampp and after downloading 7.2 it runs!
