### ISSUE TITLE
APK build failure, Failed to apply plugin [id 'com.android.application']

### ISSUE THREAD

**Issue by akandari391** [Xtraball/SiberianCMS#505]
**Java version is 1.8.0_151 , Gradle version 2.1 , also tried with gradle 4.4**
**Logs:**

Picked up _JAVA_OPTIONS: -Xmx384m -Xms384m -XX:MaxPermSize=384m
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0

FAILURE: Build failed with an exception.

* Where:
Build file '/var/www/html/siberian/var/tmp/applications/ionic/android/miracleemployees-1/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'miracleemployees-1'.
> Failed to apply plugin [id 'com.android.application']
   > Could not create an instance of type com.android.build.gradle.internal.dsl.SigningConfig_Decorated.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.605 secs

**Comment by Slicit** [comment]
First update to latest version
Try to rebuild
If still not working you can restore apps sources go to this url "/backoffice/advanced_tools"
And click on "Restore Apps" then try rebuild

If still no success, open a support ticket :)
