### ISSUE TITLE
helpppppp MCommerce not memorize system payment on SiberianCMS 4.12.21

### ISSUE THREAD

**Issue by Spotcloudtk** [Xtraball/SiberianCMS#509]
on Siberian 4.12.19 work

**Comment by Spotcloudtk** [comment]
ok work update 4.12.21

**Comment by euroonesistemi** [comment]
when you create save, but wen you modify not save. Confirmed BUG. MAE 4.12.21

**Comment by Spotcloudtk** [comment]
ok work after update 4.12.22
