### ISSUE TITLE
Error while installation (Only showing 1% installing core)

### ISSUE THREAD

**Issue by rasikapunde** [Xtraball/SiberianCMS#511]
While installing SAE it is only showing 1% installing core. I have attached screen shot of issue stated.
I am using:
Ubuntu 16.04 LTS
XAMPP 7.0.26-0
![screenshot-2018-1-1 siberian cms - the best way to create your app easily](https://user-images.githubusercontent.com/30660226/34474234-60d87e68-efa2-11e7-842b-7d6281a484f1.png)

**Comment by Team218** [comment]
Did you ever get this problem resolved? I am having the same issue.

**Comment by rasikapunde** [comment]
Yes. I have resolved it.

________________________________

**Comment by LikoV2** [comment]
Hi,

Could you share your fix, if you remember please ? It will be useful for others trying to run Siberian on Ubuntu.

**Comment by BenjaminFarris** [comment]
I need this fix 2 years later. What's the solution?
