### ISSUE TITLE
App Store does not accept applications created on the PE constructor from January 1

### ISSUE THREAD

**Issue by Vdvoem** [Xtraball/SiberianCMS#512]
4. 2 Design: Minimum Functionality
Guideline 4.2.6 - Design - Commercialized Templates and App Generation Services

We noticed that your app appears to be created from an app generation service or a commercialized template, but it was not directly submitted by the provider of the app’s content.

Next Steps

To resolve this issue, this app will need to be submitted by the content provider under their own Apple Developer Program account.

Another acceptable option is to create a single binary to host all your clients’ content in an aggregated or “picker” model, such as a restaurant finder with separate pages for each client restaurant, or as an event app with separate entries for each client event.

Note that regardless of which option you pursue, all apps submitted to the App Store should include features, content, and UI that elevate it beyond a repackaged website. Apps that are not sufficiently useful, unique or "app-like" will be rejected for not meeting the standards outlined in https://developer.apple.com/app-store/review/guidelines/#minimum-functionality">Guideline 4.2.0 of the App Store Review Guidelines.

Resources

For information on transferring an app to another developer account, please review the http://help.apple.com/itunes-connect/developer/#/deved688524f">App transfer overview page in iTunes Connect Developer Help.

For new apps, you will need to ask your client to enroll in the https://developer.apple.com/programs/">Apple Developer Program and submit this app under their own Apple Developer Account.

Best regards,
App Store Review

**Comment by clifton11221** [comment]
It appears that Apple wants the app submitted by the app owner - and not sent via the Siberian module.

I had this issue... Once my client contacted Apple directly, they approved the app.

It's important to note that the Home Page of the app should have a very unique design.  If the Home Page look similar to your average basic app, chances are that Apple won't approve it.

**Comment by Vdvoem** [comment]
They did so now everyone needs to create a separate developer account for their applications.

**Comment by Vdvoem** [comment]
These people decided to make a lot of money for us.
