### ISSUE TITLE
 Suggest more features for TaxiRive

### ISSUE THREAD

**Issue by obaviet** [Xtraball/SiberianCMS#513]
I suggest a driver's account can be converted into a customer. It means that when a driver's account is confirmed, they can simultaneously become customers. This is a very useful feature that helps us not to miss any business opportunity

**Comment by LikoV2** [comment]
Hi,

Thanks for your feedback. We've noted it down for a future update of TaxiRide. 

As this request is not for Siberian Single-App Edition, I will close this ticket.
