### ISSUE TITLE
Custom Page Module: Share Option Not Available

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#516]
The share option isn't visible on Custom Page module.  When you go to a Custom Page the share icon flashes for a quick second but then it disappears.

**Comment by clifton11221** [comment]
It appears that this bug affects Custom Pages from new apps.  When I create (or view) a Custom Page from an old app the problem isn't there.

I'm using MAE - v4.12.23.

**Comment by clifton11221** [comment]
Below is the reply that I received from support:

> Indeed there is an issue with the social share option. It is not shown properly in the overview . However, I have tested it with a new app and the setting is working properly in app (you have to close the app, then restart it to see the changes (social sharing activated or not)

**Comment by LikoV2** [comment]
Hi,

Social Sharing is not working on the overview, it's intended to hide it.
