### ISSUE TITLE
Delivery not view in app

### ISSUE THREAD

**Issue by Spotcloudit** [Xtraball/SiberianCMS#517]
Option delivery enable not view in app mobile. works only "to perform" and "pick-up in store"

Siberian 4.12.22

**Comment by LikoV2** [comment]
Hi,

Make sure you have a valid address for your store (Google Maps have to know it), and your delivery address in the app is in the delivery radius.

It's working on Siberian 4.12.23

**Comment by Spotcloudit** [comment]
Hi, you did not understand what I meant. I said that before the update to 4.12.23 even if you selected delivery, in the app did not appear right, in fact with the last update they have solved
