### ISSUE TITLE
Padlock Module: Security Issue With Internal App Links

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#519]
When using the Padlock module,  if I create an internal app link to a section of the app that is supposed to be locked, the unapproved app user is still able to access the locked section.

For example: If you lock the Fan Wall, then create an internal app link to the Fan Wall (from an unlocked page), the app user will be able to access/view the Fan Wall - without being prompted to login.  If the app user attempts to post, they will be prompted to login but they are not prompted upon initially accessing the Wall.  

This is a problem because the unapproved app user is able to view content that's supposed to be protected.  The same issue will occur if you link to Push Notifications.

**Comment by LikoV2** [comment]
Hi,

Padlock is not a "secure" way to lock your app. It's only hiding the features. In HTML5 for example, if you know the URL of the feature and reach it, you will have access, padlock activated or not.

Maybe Padlock Pro is more secure, but I don't know, maybe it's based on the module Padlock and will work the same.
