### ISSUE TITLE
Translation bugs...

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#52]
The following words cannot be translated.

**Filter your apps**

![1](https://cloud.githubusercontent.com/assets/8930862/16840722/daaf0af6-49de-11e6-9f4f-2d1b4bbcbd11.png)

**From, To**
![2](https://cloud.githubusercontent.com/assets/8930862/16840724/dad1e594-49de-11e6-8ba5-b6dcae3a64b9.png)

**Audio, Code Scan, In-Apps, QR Coupns, Tips Calc.**
![4](https://cloud.githubusercontent.com/assets/8930862/16840726/dae8e7b2-49de-11e6-9927-602a0bdd41d2.png)

**Company, Address, Address 2, State**
![3](https://cloud.githubusercontent.com/assets/8930862/16840887/a70a7590-49df-11e6-89ee-c3d796087332.png)

**Comment by SiberianCMS** [comment]
Fixed in 4.6.1
