### ISSUE TITLE
Event module end time

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#522]
The Event module shows the event end time as AM even though it is entered as PM.

**Comment by LikoV2** [comment]
Hi,

Working fine on SAE 4.12.23:

![image](https://user-images.githubusercontent.com/34651209/35635760-6fbf10e4-06af-11e8-8285-513e0a692c0b.png)

Did you test on the Calendar feature ?

**Comment by karargaht** [comment]
It is not 03:32 PM, it must be 15:32 PM.

**Comment by LikoV2** [comment]
Hi,

That's not how the AM/PM system works. You have from 0 to 12 AM, and 0 to 12 PM. When it gets past 12, you switch on the 24Hours system, hence, you don't need AM/PM anymore. So 03:32PM is 15:32.
