### ISSUE TITLE
Resources are not reachable when placing an order

### ISSUE THREAD

**Issue by Hyperians** [Xtraball/SiberianCMS#523]
Hi , 

I used Mcommerce feature to start restaurant App , 
i configured Google Maps API but due to its located in middle east country its not properly having all addresses specially most clients write in arabic which mess with google ...

when place an order in guest mode after filling the info , i got the message "the Resources are not reachable check your network connection"

I disabled Delivery option thinking it maybe the problem but yet i get the same message so i made it only in store

I made payment mode Cash or Meal Vouchers 

Yet im still facing the issue ...

Any clues?

**Comment by LikoV2** [comment]
Hi,

When exactly do you get the message ? At the "Delivery" step ?

Is your phone connected to internet ? Do you have connectivity issues with other features ?
