### ISSUE TITLE
ERROR After upgrading PE to 4.13.0

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#526]
Hello,

ERROR After updating PE 4.13.0. The browser crashes after clicking add field.

**Comment by clifton11221** [comment]
Clicking "Add" where?  

There is a known issue with Form, Audio, Catalog, and Calendar modules. This should be fixed in the next release (tomorrow hopefully).

**Comment by ciadoreino** [comment]
I checked in form module and Audio

**Comment by Slicit** [comment]
It's fixed in 4.13.1 for Audio/Form/Calendar.
Catalog & RSS will be fixed in 4.13.2 thanks.
