### ISSUE TITLE
Published Android Apps Cover Phone's Icons

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#530]
I'm not sure if it was the 4.13.2 or 4.13.3 update but since upgrading, there's a black line at the top of the screen on my newly published Android app pages. The line covers the phone's icons (battery life, wifi signal, etc).

All app pages have the same thing.

Please see the attached image.

![10_black_bar](https://user-images.githubusercontent.com/21089972/36160530-67de9ce6-10af-11e8-90bd-f5df1b0035d4.png)

**Comment by LikoV2** [comment]
Hi @clifton11221,

Could you send us the model of your device please ? Does it happen in all of your apps ? Could you send us an APK so I can check if it's linked to your device ? Thanks.

**Comment by bluesnap-rock** [comment]
Hi. I am using samsung galaxy 8 and same on my APP. But its not completley black has an opacity effect.

**Comment by clifton11221** [comment]
Yes... All of my Android apps.

**Comment by LikoV2** [comment]
Fixed 4.13.12
