### ISSUE TITLE
How to regenerate front-end js code of origin module.

### ISSUE THREAD

**Issue by minghu6** [Xtraball/SiberianCMS#533]
If I need to  modified the front-end js code to  meet my requirements, where should I focus on ?

I mean that I found that the js code of origin module was packed in `sae/var/apps/(browser|overview|ionic...)/dist/packed`, however I can't find out which code to generate these js file, anyone knows?

**Comment by LikoV2** [comment]
Hi,

If you want some advice on the development, you can ask about it on the Siberian Developers Facebook Group here: https://www.facebook.com/groups/617340045067269/
