### ISSUE TITLE
Custom Pages: Google Maps Addresses Not Displaying Automatically

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#536]
Previously, when using the Address feature on Custom Pages, as you typed in the address, the address from Google Maps automatically begin to appear… so you can simply click one of the displayed addresses. Likewise, the Longitude and Latitude information would automatically appear (after you selected an address). This no longer works. No address appears.

Using MAE v4.13.6

**Comment by clifton11221** [comment]
This issue also applies to the Places module.

**Comment by LikoV2** [comment]
Hi @clifton11221,

It seems to be back on our end, could you retry please ?
