### ISSUE TITLE
App Admin Panel - Limited Access [Feature Request]

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#539]
Many clients want to give their employees access to their App Admin Panel without allowing the staff member access to all of the design features of the app.

For example, the app owner might want to allow his staff to send Push Notifications, or to send messages to other employees Inbox.  However, they may not want to allow the staff member to add or edit existing features or app page content.

A great addition would a "Limited Access" function... Where the app admin could select the app modules that their staff members can access.  This way they can delegate responsibilities while having the comfort of knowing that their app won't get messed up.

Naturally, the "Limited Access" mode would only allow the app admin to grant permissions to the modules that are already included in their particular app.

**Comment by LikoV2** [comment]
Hi,

You can already do that with the "roles" in the backoffice.

**Comment by userdevel** [comment]
If we want to create a new account in /admin/access_management/new or /admin/backoffice_list, there is only:
- Administrator : full access

In the backoffice: acl/backoffice_role_list, there is only:
- Administrator : full access

It is not possible to have other created roles by default?
