### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by Spotcloudit** [Xtraball/SiberianCMS#540]
Can you tell me why this problem?

https://paste.ofcode.org/Z5GvLRB4dAYP4LqgcfwQPs

[]()

**Comment by LikoV2** [comment]
Hi @Spotcloudit,

Sorry about the late answer. The pastebin is not there anymore, did you fix your issue ? If not, could you re-send it ? Thanks.

**Comment by Spotcloudit** [comment]
Thu Mar 29 11:39:45.970726 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP   8. in_array() /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/app/sae/modules/Event/controllers/Mobile/ListController.php:46
[Thu Mar 29 11:39:48.079638 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP Notice:  Undefined index: groups in /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/app/sae/modules/Event/controllers/Mobile/ListController.php on line 46
[Thu Mar 29 11:39:48.079660 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP Stack trace:
[Thu Mar 29 11:39:48.079663 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP   1. {main}() /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/index.php:0
[Thu Mar 29 11:39:48.079665 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP   2. Zend_Application->run() /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/index.php:94
[Thu Mar 29 11:39:48.079667 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP   3. Bootstrap->run() /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/lib/Zend/Application.php:366
[Thu Mar 29 11:39:48.079669 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP   4. Zend_Controller_Front->dispatch() /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/app/Bootstrap.php:337
[Thu Mar 29 11:39:48.079672 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP   5. Siberian_Controller_Dispatcher_Standard->dispatch() /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/lib/Zend/Controller/Front.php:954
[Thu Mar 29 11:39:48.079674 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP   6. Event_Mobile_ListController->dispatch() /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/lib/Zend/Controller/Dispatcher/Standard.php:308
[Thu Mar 29 11:39:48.079676 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP   7. Event_Mobile_ListController->findallAction() /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/lib/Zend/Controller/Action.php:516
[Thu Mar 29 11:39:48.079678 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP Warning:  in_array() expects parameter 2 to be array, null given in /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/app/sae/modules/Event/controllers/Mobile/ListController.php on line 46
[Thu Mar 29 11:39:48.079680 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP Stack trace:
[Thu Mar 29 11:39:48.079682 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP   1. {main}() /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/index.php:0
[Thu Mar 29 11:39:48.079684 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP   2. Zend_Application->run() /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/index.php:94
[Thu Mar 29 11:39:48.079686 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP   3. Bootstrap->run() /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/lib/Zend/Application.php:366
[Thu Mar 29 11:39:48.079688 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP   4. Zend_Controller_Front->dispatch() /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/app/Bootstrap.php:337
[Thu Mar 29 11:39:48.079690 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP   5. Siberian_Controller_Dispatcher_Standard->dispatch() /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/lib/Zend/Controller/Front.php:954
[Thu Mar 29 11:39:48.079692 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP   6. Event_Mobile_ListController->dispatch() /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/lib/Zend/Controller/Dispatcher/Standard.php:308
[Thu Mar 29 11:39:48.079700 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP   7. Event_Mobile_ListController->findallAction() /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/lib/Zend/Controller/Action.php:516
[Thu Mar 29 11:39:48.079702 2018] [fcgid:warn] [pid 15650] [client 151.43.146.245:2234] mod_fcgid: stderr: PHP   8. in_array() /home/spotcloud/domains/appbuild.spotcloud.tk/public_html/app/sae/modules/Event/controllers/Mobile/ListController.php:46

**Comment by Spotcloudit** [comment]
I have no problems. I just wanted to know what I would be and what caused it all
