### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/SiberianCMS#542]
1. Is the ddfault privacy policy GDRP compliant especially with sending push notifications.

2. App user Sign up email. Can this not be modified so it includes the consent to remove account.

3. Platform Editor sign up we need to add an opt in feild and privacy policy, the email needs to include a consent to delete/remove account.

**Comment by LikoV2** [comment]
Hi,

We are currently reviewing all the GDPR directives, to apply them to Siberian. There will be an update (or multiples), to make Siberian GDPR compliant.

**Comment by Slicit** [comment]
Specs & features are in development, a first part will be released by Wednesday 25 April, the next will follow asap.

Thanks.
