### ISSUE TITLE
Fresh install on Local Error

### ISSUE THREAD

**Issue by Ashrafdev** [Xtraball/SiberianCMS#544]
![image](https://user-images.githubusercontent.com/14801084/37779792-33c52510-2e28-11e8-88ae-fcf25c6475e7.png)

error file : SiberianCMS\lib\Siberian\Layout.php

i suspect this code not working properly to get xml file can you check ?
```$front_xml = Siberian_Cache_Design::getBasePath("/layout/front.xml");```

**Comment by LikoV2** [comment]
Hi @Ashrafdev,

Is your server meeting the requirements ? https://doc.siberiancms.com/knowledge-base/siberian-server-requirements/

Please double check every php extensions.

**Comment by Ashrafdev** [comment]
![image](https://user-images.githubusercontent.com/14801084/38082928-c55b8012-337a-11e8-9d23-3679f7994a58.png)

all perfect but im using this ``php -S localhost:8000`` for php built in webserver is it ok?

**Comment by ashishcompwiz** [comment]
same issue here
did u find a solution

**Comment by Ashrafdev** [comment]
@ashishcompwiz use apache webserver

**Comment by Slicit** [comment]
Looks like a cache issue with wrong files, maybe try a new fresh install with latest github version 
which is HERE > https://github.com/Xtraball/Siberian
