### ISSUE TITLE
Apple Rejection

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/SiberianCMS#546]
Processed, cleaned, built and archived the same as previous version, however APP is being rejected because of this - 

Guideline 5.1.5 - Legal - Privacy - Location Services

Your app uses location services but does not clarify the purpose of its use in the location modal alert. Apps that collect, transmit, or use location data must notify and obtain the user’s consent prior to accessing this data.

Please see attached screenshots for details.

Next Steps

To resolve this issue, please specify why the app is requesting the user's location in the location permission modal alert.

Resources

For additional information and instructions on configuring and presenting an alert, please review the Requesting Permission section of the iOS Human Interface Guidelines and the Information Property List Key Reference. You may also want to review the Technical Q&A QA1937: Resolving the Privacy-Sensitive Data App Rejection page for details on how to provide a usage description for permission request alerts.

I checked the string on the location info settings and its the same as previous - 

"APP NAME" would like to use your current location.

**Comment by clifton11221** [comment]
In your App Manager:

1) Select "Settings" from the left-hand-side of the screen.

2) Select "Advanced".

3) Under "IOS NS*DESCRIPTIONS" edit the descriptions so that they state your reasons for using the respective services.

4) Click "Save"

**Comment by bluesnap-rock** [comment]
Thanks. Didnt see the new settings. Thanks again clifton
