### ISSUE TITLE
Mobile view and feature preview bugs 

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#55]
Responsive view. The Insert Page button does not appear. 

Version 4.2 

https://drive.google.com/file/d/0B__JJt1TxdH6dWxKYjliZk5zdXc/view?usp=docslist_api

<iframe src="https://drive.google.com/file/d/0B__JJt1TxdH6dWxKYjliZk5zdXc/preview" width="640" height="480"></iframe>

**Comment by SiberianCMS** [comment]
I renamed the task to avoid confusion :)

**Comment by alexyves** [comment]
Fixed: will be updated soon.

![55-preview-feature-responsive](https://cloud.githubusercontent.com/assets/18324386/18406958/58a1a9ca-7705-11e6-8fa6-2987016c5a25.png)
