### ISSUE TITLE
Problem with loyalty card

### ISSUE THREAD

**Issue by exx06** [Xtraball/SiberianCMS#550]
Hi. We receive complaints from customers that the loyalty points are empty on Android 7
![img_0522](https://user-images.githubusercontent.com/38353714/38737119-e5418bca-3f36-11e8-9307-8d6f6d3938c4.jpg)
In Siberian CMS everything is displayed correctly.
![default](https://user-images.githubusercontent.com/38353714/38737219-3a6b852e-3f37-11e8-87ec-54a1aed8b258.JPG)

**Comment by LikoV2** [comment]
Hi @exx06,

Is the app old ? If you tap 5 times in the title "My account" in the my account feature, is it updating correctly ?
