### ISSUE TITLE
Push Notification 

### ISSUE THREAD

**Issue by ksvaghela** [Xtraball/SiberianCMS#552]
Hello ,
Please find below message from google For GCM is going deprecated .

As of April 10, 2018, Google has deprecated GCM. The GCM server and client APIs are deprecated and will be removed as soon as April 11, 2019. Migrate GCM apps to Firebase Cloud Messaging (FCM), which inherits the reliable and scalable GCM infrastructure, plus many new features. See the migration guide to learn more.

Can you please provide update Push Notification Plugin with FCM. 

https://github.com/phonegap/phonegap-plugin-push 

Thanks in Advance.

Regards,
Ketan

**Comment by LikoV2** [comment]
Hi Ketan,

We received it, and it will be updated.
