### ISSUE TITLE
Download buttons do not work on in-app browser

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#554]
Download buttons do not work on in-app browser.

**Comment by karargaht** [comment]
![screenshot_20180425-224523](https://user-images.githubusercontent.com/8930862/39269159-c4f817f0-48da-11e8-80ba-c86f039fadca.png)

**Comment by karargaht** [comment]
This is a webview site. I'm trying to download a video but do not react when I click Download.

**Comment by karargaht** [comment]
In other CMSs, clicking on the download button starts downloading from an external browser.

**Comment by Slicit** [comment]
InAppBrowser is limited, there is no immediate solution or fix for that.
