### ISSUE TITLE
How to list registration using the "source code"

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#555]
Hello,
I need to list some mysql database records and I am using the "source code" feature. I would like some tip or example if possible.
Thank you very much in advance

**Comment by LikoV2** [comment]
Hi @ciadoreino,

You can ask about it on the Siberian Developers Facebook Group: https://www.facebook.com/groups/617340045067269/

There is much more developers than here. They will surely help you on your customization.
