### ISSUE TITLE
Security bug with assigning Roles in admin area

### ISSUE THREAD

**Issue by Intro2** [Xtraball/SiberianCMS#56]
I first reported this security bug to Siberian back in March and have been repeatedly been told 'it will be fixed soon'. This needs to be fixed right now!

In PE, I create a User with multi-User access, but not white-label access...

When this User logs into the Admin area and adds their own User(s) they can assign 'Administrator' Role to the User(s), even although they don't have administrator role themself.

I think that only Administrators should be able to assign Roles in the Admin area, otherwise the default Role (set in the backoffice) should be used for additional Users.

Please fix this bug asap.

Mick

**Comment by SiberianCMS** [comment]
It's fixed from our side, and should be released in 4.2.1 or 4.2.2 next week.

Thanks

**Comment by Intro2** [comment]
Great news. Thanks!
