### ISSUE TITLE
Privacy on modal

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/SiberianCMS#571]
Hi Guys 
Now you have added the privacy block to logged in users in the modal view.
When your not logged in and click sign up - the form now looks a little silly.

You have
Privacy Policy
I accept the privacy policy
then - 
Privacy: again.

Need to remove this on the signing up of a new account.

Also logged in user who click to view the privacy policy top and bottom + Create Account is present still - tbh not the end of the world, but for good UI would better to hide this on logged in accounts.

**Comment by LikoV2** [comment]
Hi @bluesnap-rock,

Thanks for your feedback. The GDPR updates are not finished yet, it will be improved, and the button for data deletion will be added.
