### ISSUE TITLE
In-App Messages

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/SiberianCMS#573]
Hi
Has the in-app messages stopped working?
On all my APPS in-app messages no longer show up? - push notifications work fine.
Also I have noticed in the database that push notifications and push messages  that the title/text are code? is that right?
Thanks

**Comment by LikoV2** [comment]
Hi @bluesnap-rock,

Not working at the moment. Push title/message are crypted, yes.

**Comment by bluesnap-rock** [comment]
Hi @LikoV2 any update on when the in-app messages will be working again, thanks?

**Comment by LikoV2** [comment]
Hi @bluesnap-rock,

Devs are on the previewer for now, so it will not be fixed in the immediate future. I think devs will have a bit of time after the previewer, but I have no release date yet.

We are not forgetting it though.

**Comment by LikoV2** [comment]
Fixed 4.14.13
