### ISSUE TITLE
Bug - Backgrounds when copying APP

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/SiberianCMS#575]
HI

If you make a copy an existing APP which already has the following option selected
**Use the homepage image as background in all features**

Then the new 'Copy' of the APP will never get rid of the cached background image - even when you clear cache.  You can add a new background obviously, but if you wanted to have your Background color in the 'Copy' APP you can't it will always show the background image from the APP you have copied from. 

So you have to copy the APP with the option (**Use the homepage image as background in all features**
) un-selected in order to be able to have a simple background color in the 'Copy' APP.

Hope that make sense. (v4.13.19 - just checked Siberian demo as well)

**Comment by Slicit** [comment]
That's one of the way too long list of reasons for why we temporary disabled "duplicate" feature.

The new system export/import is actually in beta and when stable enough, it will be used in background to enable again "duplicate" feature.
