### ISSUE TITLE
language files have disappeared in version 4.14.0 for PE

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#579]
Hello,

after I did the update from my Siberiancms PE to version 4.14.0 the files of the language option in the Settings / Translation menu disappeared
![traducao](https://user-images.githubusercontent.com/25539714/41289536-807839e6-6e20-11e8-984e-99f34ae16679.jpg)

**Comment by LikoV2** [comment]
Hi,

Update to 4.14.3, your issue will be fixed.
