### ISSUE TITLE
App User Privileges

### ISSUE THREAD

**Issue by Intro2** [Xtraball/SiberianCMS#58]
This is just a suggestion to help make the PE version more Admin User friendly...

As things are now, if a User only needs access to a single feature in an app, e.g., Commerce store listing page, then this can only be configured from inside the Backoffice Manage>>User section, requiring the PE owner or their staff to make changes on behalf of the client/reseller.

It's my opinion that this task should also be configurable from the, /admin/access_management/edit/ area so that Resellers could manage their own client requirements and access to an app without the need to involve (at extra cost) the PE Owner.

I hope this makes sense.

**Comment by LikoV2** [comment]
Hi @Intro2,

It will be added shortly, Admins will be able to request roles to the Platform owner, and give them to their users. I will close this issue, as it's related to a commercial edition, and not the Single-App Edition.
