### ISSUE TITLE
#443-02: Firebase is not well configured.

### ISSUE THREAD

**Issue by Vdvoem** [Xtraball/SiberianCMS#580]
Hello everyone, after the update produces this error: # 443-02: Firebase is not well configured.

**Comment by Vdvoem** [comment]
Gradle sync failed: Keystore file does not exist: D:\Users\Im\chiserv\V-1_2\1_1_android_source\keystore.pks
			Consult IDE log for more details (Help | Show Log)

**Comment by LikoV2** [comment]
Hi,

Firebase issue is self-explanatory, explained in the release and in the documentation: https://doc.siberiancms.com/knowledge-base/siberian-4-14-0-major-release-documentation/

Keystore issue is fixed in 4.14.3

**Comment by Vdvoem** [comment]
Hi, the error gives, the screen attached.
![default](https://user-images.githubusercontent.com/30751163/41462103-8ed2690e-70b3-11e8-87a6-00f8c6ca304a.png)
