### ISSUE TITLE
QR Code Scanner Not Opening

### ISSUE THREAD

**Issue by MojoJojo43** [Xtraball/SiberianCMS#585]
Hello All,

Newb with SiberianCMS here. 

I recently downloaded the single edition and have it up and running on my server.  I figured I would test out the single edition before making the leap to purchasing the platform edition.

My issue involves the QR Scanner feature. I have been testing the created app on my mobile and everything seems to work fine except for the scanner whether it be the qr coupon feature, qr scanner, or the loyalty scanner. Here are some screenshots:

Code Scanner:
![barcode-scanner-issue](https://user-images.githubusercontent.com/40812247/42252650-83cf2b26-7ef2-11e8-9af4-16c5494771ef.jpg)

Loyalty Scanner:
![loyalty-scanner-issue](https://user-images.githubusercontent.com/40812247/42252659-911e50ea-7ef2-11e8-9bf7-73f737d34a75.jpg)

QR Coupon Scanner:
![qr-coupon-issue](https://user-images.githubusercontent.com/40812247/42252686-a2f0be16-7ef2-11e8-8692-ac0fb7298056.jpg)

As you can see, the Code Scanner asks for the user to input a barcode value.

The rest do nothing after clicking OK from the popup menu. The scanner never opens the camera whatsoever. After clicking ok, nothing happens.

Any suggestions or advice would be greatly appreciated! Thanks!

**Comment by LikoV2** [comment]
Hi @MojoJojo43 

I can't reproduce this issue. Seems like a lack of requirements.
