### ISSUE TITLE
After Siberiancms 5.14.6 the applications do not run

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#587]
Hello,

I need an urgent help, after upgrading to Siberiancms for 4.14.6 and upgrading Android Studio to 3.1.3, I can no longer run APKs. My applications are compiled successfully, but when I run on smatphone they get on the home screen loading and do not get out of it.

Help me please!!!

**Comment by ciadoreino** [comment]
How do I solve this problem? Can someone help me?

Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'
![sem titulo](https://user-images.githubusercontent.com/25539714/42666885-2beb141e-861e-11e8-92c8-89c43eca1e0e.png)

**Comment by LikoV2** [comment]
Hi @ciadoreino 

Check if your SSL certificates are up and running (https must be working, if you activated it), then follow this process: https://www.siberiancms.com/community/d/116-solve-unresponsive-features

**Comment by ciadoreino** [comment]
Hello,
thanks for the feedback.
I am facing a broblema, where I am not able to change HTTP to HTTPS, my SiberianCMS is a PE and is on a CentOS 7 VPS server, using a SENTORA manager.
I do not know how to solve this if you can guide me I'll be very grateful.

**Comment by LikoV2** [comment]
Hi @ciadoreino 

Do you still have the issue ? If so, send us a mail to contact@siberiancms.com or create a ticket.

Github is for Single-App Edition, and not commercial editions.
