### ISSUE TITLE
Pages Icon colors in Folder feature

### ISSUE THREAD

**Issue by Alboorii** [Xtraball/SiberianCMS#59]
Hello

When i create folder feature, then access it to add pages
The pages icon color is transparent so i can't find them without mouse hover.

![screen shot 2016-07-24 at 12 04 08 pm](https://cloud.githubusercontent.com/assets/13621788/17082918/112beb84-5197-11e6-8f66-8ba3045a108f.png)
![screen shot 2016-07-24 at 12 04 13 pm](https://cloud.githubusercontent.com/assets/13621788/17082919/112e1b3e-5197-11e6-86d5-67a82457a93d.png)
![screen shot 2016-07-24 at 12 04 19 pm](https://cloud.githubusercontent.com/assets/13621788/17082920/11308856-5197-11e6-9e7d-a68cdf72ab03.png)

**Comment by SiberianCMS** [comment]
Fixed.
