### ISSUE TITLE
WooCommerce

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/SiberianCMS#594]
@LikoV2 
WooCommerce you can no longer delete an item from the basket.
Also - when you add a second item whether its the same or a different item it doesn't pop up saying item has been added to basket (like the first) ?

Also - any plans to integrate past orders / log into account with this module? desperate for that? (rather than just putting their email)

thanks in advance.

**Comment by LikoV2** [comment]
Hi @bluesnap-rock 

About paid modules, please send us a mail at contact@siberiancms.com
