### ISSUE TITLE
SSL in Siberiancms PE does not work with CentOS 7 and Panel Sentora

### ISSUE THREAD

**Issue by ciadoreino** [Xtraball/SiberianCMS#599]
Hello,
I'm about to give up using Siberiamcms PE because I can not run any applications on Google or Apple after upgrading to the latest versions.

I can not configure SSL on my PE that is in a VPS with CentOS 7 using the Sentry Panel.

I need URGENT help !!!!

**Comment by Slicit** [comment]
With a custom admin panel, you need to upload manually the SSL Certificates.
