### ISSUE TITLE
All the icons in same folder

### ISSUE THREAD

**Issue by lampela** [Xtraball/SiberianCMS#60]
I think it would give much more freedom to deliver all the icons available for all the page types. For example I'm creating a restricted page with an external html page (source code page type->iframe) and I get only a few very unfitting library icons. Specially the source code is full of possibilities - but I really think all the pages can be used creatively for any purpose - so it would be great to have all the icons available while creating the pages.

**Comment by alexyves** [comment]
Will be done in 4.5.x

**Comment by SiberianCMS** [comment]
Done in 4.6.1 thanks.
![screen shot 2016-09-21 at 15 13 45](https://cloud.githubusercontent.com/assets/7977082/18741268/79da7b6e-80ae-11e6-82ee-12f06bec8483.png)
