### ISSUE TITLE
woocommerce module error cdvfile://localhost/temporary/module.js

### ISSUE THREAD

**Issue by qkgm828** [Xtraball/SiberianCMS#601]
woocommerce module is not working with error message "Configuration error. Please contact an administrator" i checked Consumer key and Consumer secret. there are no problem.

also, i can see "cdvfile://localhost/temporary/module.js net::ERR_UNKNOWN_URL_SCHEME"

what is the cdvfile? and the url is not correct?

if someone can help me please let me know how to solve these problems..

![cdvfile](https://user-images.githubusercontent.com/44738639/47959436-053f3000-dfb2-11e8-9058-2c2a28885aa4.jpg)

**Comment by qkgm828** [comment]
it is related to the woocommerce version because siberian woocommerce module use api v1. so if you need to use siberian woocommerce module you have to install woocommerce older version.

i hope that i use woocommerce api v2 or v3 soon.

**Comment by Slicit** [comment]
@qkgm828 you can completely ignore "cdvfile://localhost/temporary/module.js net::ERR_UNKNOWN_URL_SCHEME" it's a specific case only for Apps, nothing wrong here, it's the intended behavior.

For woo-commerce, as it's a paid module, I invite you to open a support ticket/e-mail to look with team.
