### ISSUE TITLE
WOOCOMMERCE MUDULE – PAY ON OUR ONLINE STORE

### ISSUE THREAD

**Issue by qkgm828** [Xtraball/SiberianCMS#603]
my woocommerce version is 3.4.6 and wordpress version is 4.9.8.

now i can see products through woocommerce module.

so i added some porducts on cart. and i clicked "Pay on our online store", however, i met login page.

1. do i have to login again on mobile web even though i logined in woocommerce module?

2. so i logined again on mobile web…but there is no product in cart.

i think that if i click "Pay on our online store", i can see a cart with products automatically without login.
can someone help me solve this problem? 

![login](https://user-images.githubusercontent.com/44738639/49117703-3e905600-f267-11e8-9bdd-3c730518cc74.jpg)

**Comment by Slicit** [comment]
WooCommerce is paid module you'll get support by e-mail at contact@siberiancms.com thanks ;)
