### ISSUE TITLE
When can we upgrade our php version to 7+

### ISSUE THREAD

**Issue by ranjbar2446** [Xtraball/SiberianCMS#608]
As the older php versions have reached EOL when can we upgrade our php version to 7+ without any problems?

**Comment by Slicit** [comment]
For now only PHP 7.0 is supported.

We are working to support 7.1, 7.2 and 7.3 in a a future update, some of our 3rd party libraries are quite old and needs lot of custom work to with these versions, and we can't really "just change" them like ... we can't change ZF1 to ZF3 without breaking everything.

**Comment by ranjbar2446** [comment]
Do you have a plan for changing ZF1 to ZF2 or ZF3?

**Comment by Slicit** [comment]
`we can't change ZF1 to ZF3 without breaking everything.`

So no, we won't.

**Comment by userdevel** [comment]
I have seen a comment from @Slicit about it: https://github.com/Xtraball/Siberian/issues/15#issuecomment-467794293

> As per the roadmap, partial support for php 7.1, 7.2 & 7.3 will be added soon
> 
> https://www.siberiancms.com/community/d/745-roadmap-4-15-4-16

Linked to:
- https://github.com/Xtraball/SiberianCMS/issues/593
- https://github.com/Xtraball/Siberian/issues/15

@SiberianCMS @dbyzero @Slicit @LikoV2: But on the roadmap, I have not seen easy opened bugs (1 year ago):
- https://github.com/Xtraball/SiberianCMS/issues/created_by/userdevel
