### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by thehosting4you** [Xtraball/SiberianCMS#61]
Hey,

Contact page as it is transmitted, we get headed in a message on the screen.
When you click OK, you can use the same information from a contact to send this message seems to be a bug.
normally it would still be empty after sending?

I also tested this in the form module and this is after sending empty.

Sincerely André

**Comment by SiberianCMS** [comment]
Fixed in 4.6.1, on success form is cleared, then redirects back to contact page.
