### ISSUE TITLE
Wordpress Integration Displays A Blank Screen After 15 Posts & Doesn't Show Most Recent Post First

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#62]
There are two bugs with the WordPress integration module. These bugs are in prior versions but they're still in version 4.3.0... 

1) In the post list, after the 15th post, when you click the post Title of the 16th post you're shown a blank screen as opposed to the content of the post. See included image.

2) The most recent post isn't displayed as the "Featured" or 1st post in the post list. Instead, it features the 15th post. This appears to be related to the referenced bug above.

![siberian_wordpress_bug](https://cloud.githubusercontent.com/assets/21089972/17753218/dc8e318e-649c-11e6-836c-57084479b9ae.png)

![siberian_wordpress_bug_2](https://cloud.githubusercontent.com/assets/21089972/17753219/dc90dfd8-649c-11e6-86c1-c942c66bc2b1.png)

**Comment by clifton11221** [comment]
This bug also applies to the displayed posts in the WordPress integration.

**Comment by clifton11221** [comment]
Even though the Release Notes state that this issue is fixed in version 4.5, the bug still exist. 

Both problems are still there:

1) When you click the topic past the 15 topic, you get a blank screen.
2) The 15 topic is selected as the featured topic (at the top of the screen) instead of the latest/newest topic.

**Comment by karargaht** [comment]
The problem continues...v: 4.5.3

**Comment by clifton11221** [comment]
With update 4.5.5 the issue is only fixed in the website previewer.  However, when I tested it on the Siberian App Previewer (that you can download from the App Stores) the issue is still there.

**Comment by SiberianCMS** [comment]
Now completely fixed.
