### ISSUE TITLE
Error when Build APK

### ISSUE THREAD

**Issue by dorian59** [Xtraball/SiberianCMS#63]
Hi, i have a bug when i build APK (i follow step by step) 
`Executing tasks: [:CordovaLib:assembleRelease, :assembleRelease]

Configuration on demand is an incubating feature.
:CordovaLib:compileLint
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl UP-TO-DATE
:CordovaLib:compileReleaseRenderscript UP-TO-DATE
:CordovaLib:generateReleaseBuildConfig UP-TO-DATE
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets UP-TO-DATE
:CordovaLib:generateReleaseResValues UP-TO-DATE
:CordovaLib:generateReleaseResources UP-TO-DATE
:CordovaLib:packageReleaseResources UP-TO-DATE
:CordovaLib:processReleaseManifest UP-TO-DATE
:CordovaLib:processReleaseResources UP-TO-DATE
:CordovaLib:generateReleaseSources UP-TO-DATE
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:compileReleaseJava UP-TO-DATE
:CordovaLib:packageReleaseJar UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease UP-TO-DATE
:CordovaLib:compileReleaseSources UP-TO-DATE
:CordovaLib:assembleRelease UP-TO-DATE
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:compileDebugJava UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:prepareComAndroidSupportSupportCompat2420Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUi2420Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUtils2420Library UP-TO-DATE
:prepareComAndroidSupportSupportFragment2420Library UP-TO-DATE
:prepareComAndroidSupportSupportMediaCompat2420Library UP-TO-DATE
:prepareComAndroidSupportSupportV132420Library UP-TO-DATE
:prepareComAndroidSupportSupportV42420Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAds940Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAdsLite940Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBase940Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBasement940Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesClearcut940Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesGass940Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesGcm940Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesIid940Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesTasks940Library UP-TO-DATE
:prepareOCCordovaLibUnspecifiedReleaseLibrary UP-TO-DATE
:prepareReleaseDependencies
:compileReleaseAidl UP-TO-DATE
:compileReleaseRenderscript UP-TO-DATE
:generateReleaseBuildConfig UP-TO-DATE
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets UP-TO-DATE
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources UP-TO-DATE
:mergeReleaseResources UP-TO-DATE
:processReleaseManifest UP-TO-DATE
:processReleaseResources UP-TO-DATE
:generateReleaseSources UP-TO-DATE
:processReleaseJavaRes UP-TO-DATE
:compileReleaseJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:compileReleaseNdk UP-TO-DATE
:compileReleaseSources
:preDexRelease
AGPBI: {"kind":"SIMPLE","text":"java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0","position":{},"original":"java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.lang.ClassLoader.defineClass1(Native Method)","position":{},"original":"\tat java.lang.ClassLoader.defineClass1(Native Method)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.lang.ClassLoader.defineClass(ClassLoader.java:800)","position":{},"original":"\tat java.lang.ClassLoader.defineClass(ClassLoader.java:800)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)","position":{},"original":"\tat java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader.defineClass(URLClassLoader.java:449)","position":{},"original":"\tat java.net.URLClassLoader.defineClass(URLClassLoader.java:449)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader.access$100(URLClassLoader.java:71)","position":{},"original":"\tat java.net.URLClassLoader.access$100(URLClassLoader.java:71)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader$1.run(URLClassLoader.java:361)","position":{},"original":"\tat java.net.URLClassLoader$1.run(URLClassLoader.java:361)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader$1.run(URLClassLoader.java:355)","position":{},"original":"\tat java.net.URLClassLoader$1.run(URLClassLoader.java:355)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.security.AccessController.doPrivileged(Native Method)","position":{},"original":"\tat java.security.AccessController.doPrivileged(Native Method)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader.findClass(URLClassLoader.java:354)","position":{},"original":"\tat java.net.URLClassLoader.findClass(URLClassLoader.java:354)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.lang.ClassLoader.loadClass(ClassLoader.java:425)","position":{},"original":"\tat java.lang.ClassLoader.loadClass(ClassLoader.java:425)"}
AGPBI: {"kind":"SIMPLE","text":"\tat sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)","position":{},"original":"\tat sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.lang.ClassLoader.loadClass(ClassLoader.java:358)","position":{},"original":"\tat java.lang.ClassLoader.loadClass(ClassLoader.java:358)"}
AGPBI: {"kind":"SIMPLE","text":"\tat sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)","position":{},"original":"\tat sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)"}
AGPBI: {"kind":"SIMPLE","text":"Exception in thread \"main\" ","position":{},"original":"Exception in thread \"main\" "}

AGPBI: {"kind":"SIMPLE","text":"java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0","position":{},"original":"java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.lang.ClassLoader.defineClass1(Native Method)","position":{},"original":"\tat java.lang.ClassLoader.defineClass1(Native Method)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.lang.ClassLoader.defineClass(ClassLoader.java:800)","position":{},"original":"\tat java.lang.ClassLoader.defineClass(ClassLoader.java:800)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)","position":{},"original":"\tat java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader.defineClass(URLClassLoader.java:449)","position":{},"original":"\tat java.net.URLClassLoader.defineClass(URLClassLoader.java:449)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader.access$100(URLClassLoader.java:71)","position":{},"original":"\tat java.net.URLClassLoader.access$100(URLClassLoader.java:71)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader$1.run(URLClassLoader.java:361)","position":{},"original":"\tat java.net.URLClassLoader$1.run(URLClassLoader.java:361)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader$1.run(URLClassLoader.java:355)","position":{},"original":"\tat java.net.URLClassLoader$1.run(URLClassLoader.java:355)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.security.AccessController.doPrivileged(Native Method)","position":{},"original":"\tat java.security.AccessController.doPrivileged(Native Method)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader.findClass(URLClassLoader.java:354)","position":{},"original":"\tat java.net.URLClassLoader.findClass(URLClassLoader.java:354)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.lang.ClassLoader.loadClass(ClassLoader.java:425)","position":{},"original":"\tat java.lang.ClassLoader.loadClass(ClassLoader.java:425)"}
AGPBI: {"kind":"SIMPLE","text":"\tat sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)","position":{},"original":"\tat sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.lang.ClassLoader.loadClass(ClassLoader.java:358)","position":{},"original":"\tat java.lang.ClassLoader.loadClass(ClassLoader.java:358)"}
AGPBI: {"kind":"SIMPLE","text":"\tat sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)","position":{},"original":"\tat sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)"}
AGPBI: {"kind":"SIMPLE","text":"Exception in thread \"main\" ","position":{},"original":"Exception in thread \"main\" "}

AGPBI: {"kind":"SIMPLE","text":"java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0","position":{},"original":"java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.lang.ClassLoader.defineClass1(Native Method)","position":{},"original":"\tat java.lang.ClassLoader.defineClass1(Native Method)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.lang.ClassLoader.defineClass(ClassLoader.java:800)","position":{},"original":"\tat java.lang.ClassLoader.defineClass(ClassLoader.java:800)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)","position":{},"original":"\tat java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader.defineClass(URLClassLoader.java:449)","position":{},"original":"\tat java.net.URLClassLoader.defineClass(URLClassLoader.java:449)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader.access$100(URLClassLoader.java:71)","position":{},"original":"\tat java.net.URLClassLoader.access$100(URLClassLoader.java:71)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader$1.run(URLClassLoader.java:361)","position":{},"original":"\tat java.net.URLClassLoader$1.run(URLClassLoader.java:361)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader$1.run(URLClassLoader.java:355)","position":{},"original":"\tat java.net.URLClassLoader$1.run(URLClassLoader.java:355)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.security.AccessController.doPrivileged(Native Method)","position":{},"original":"\tat java.security.AccessController.doPrivileged(Native Method)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader.findClass(URLClassLoader.java:354)","position":{},"original":"\tat java.net.URLClassLoader.findClass(URLClassLoader.java:354)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.lang.ClassLoader.loadClass(ClassLoader.java:425)","position":{},"original":"\tat java.lang.ClassLoader.loadClass(ClassLoader.java:425)"}
AGPBI: {"kind":"SIMPLE","text":"\tat sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)","position":{},"original":"\tat sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.lang.ClassLoader.loadClass(ClassLoader.java:358)","position":{},"original":"\tat java.lang.ClassLoader.loadClass(ClassLoader.java:358)"}
AGPBI: {"kind":"SIMPLE","text":"\tat sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)","position":{},"original":"\tat sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)"}
AGPBI: {"kind":"SIMPLE","text":"Exception in thread \"main\" ","position":{},"original":"Exception in thread \"main\" "}

AGPBI: {"kind":"SIMPLE","text":"java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0","position":{},"original":"java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.lang.ClassLoader.defineClass1(Native Method)","position":{},"original":"\tat java.lang.ClassLoader.defineClass1(Native Method)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.lang.ClassLoader.defineClass(ClassLoader.java:800)","position":{},"original":"\tat java.lang.ClassLoader.defineClass(ClassLoader.java:800)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)","position":{},"original":"\tat java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader.defineClass(URLClassLoader.java:449)","position":{},"original":"\tat java.net.URLClassLoader.defineClass(URLClassLoader.java:449)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader.access$100(URLClassLoader.java:71)","position":{},"original":"\tat java.net.URLClassLoader.access$100(URLClassLoader.java:71)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader$1.run(URLClassLoader.java:361)","position":{},"original":"\tat java.net.URLClassLoader$1.run(URLClassLoader.java:361)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader$1.run(URLClassLoader.java:355)","position":{},"original":"\tat java.net.URLClassLoader$1.run(URLClassLoader.java:355)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.security.AccessController.doPrivileged(Native Method)","position":{},"original":"\tat java.security.AccessController.doPrivileged(Native Method)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.net.URLClassLoader.findClass(URLClassLoader.java:354)","position":{},"original":"\tat java.net.URLClassLoader.findClass(URLClassLoader.java:354)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.lang.ClassLoader.loadClass(ClassLoader.java:425)","position":{},"original":"\tat java.lang.ClassLoader.loadClass(ClassLoader.java:425)"}
AGPBI: {"kind":"SIMPLE","text":"\tat sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)","position":{},"original":"\tat sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)"}
AGPBI: {"kind":"SIMPLE","text":"\tat java.lang.ClassLoader.loadClass(ClassLoader.java:358)","position":{},"original":"\tat java.lang.ClassLoader.loadClass(ClassLoader.java:358)"}
AGPBI: {"kind":"SIMPLE","text":"\tat sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)","position":{},"original":"\tat sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)"}
AGPBI: {"kind":"SIMPLE","text":"Exception in thread \"main\" ","position":{},"original":"Exception in thread \"main\" "}

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':preDexRelease'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_79\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.797 secs
`

**Comment by SiberianCMS** [comment]
It's not related to siberiancms source. Please check if your android studio and java is up to date with correct SDK version (22 for siberian). If you cannot find any fix, please send us your sources.

**Comment by dorian59** [comment]
i have download last Android studio, (in your tutorial, you say : if you have last versions siberian, you need last version android studio), i go check if all is up to date, ty
Date: Thu, 18 Aug 2016 03:46:53 -0700
