### ISSUE TITLE
"Read All" Verbiage On Audio Player Is Incorrect

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#66]
In the Audio Player module, there is text that says, "Read All". This is incorrect.

Stating "Read All" would be correct if it was a book module. However, the purpose of the link to view all of the tracks so that they can be listened to.  So the correct verbiage is "**View All**" (or "Listen To All").

![languge_update](https://cloud.githubusercontent.com/assets/21089972/18011379/eadba450-6b82-11e6-9680-55defc27a564.png)

**Comment by dbyzero** [comment]
You can change translation in backoffice if you dont want to wait the fix.

**Comment by Slicit** [comment]
Default is changed in 4.12.0 and will be released soon.
