### ISSUE TITLE
Social share feature

### ISSUE THREAD

**Issue by rogeroffer** [Xtraball/SiberianCMS#67]
Social sharing feature is till not pointing to the markets of Google Play and Itunes. Still pointing to the mobile website of the builder

**Comment by Alboorii** [comment]
Go to Backoffice > Manage > Applications
Then find your application and enter it
Then in Device Information section enter the app url
and its should work fine

**Comment by rogeroffer** [comment]
Hi,
this is not the first time that i open a ticket for this. There is also a new ticket now. Did all of it and is not working
