### ISSUE TITLE
assigning roles

### ISSUE THREAD

**Issue by Intro2** [Xtraball/SiberianCMS#70]
This is just a suggestion that can be very useful...

In the Backoffice 'Roles' section it would be good if the owner could choose which roles (checkbox?) can be assigned to Resellers to use for adding their own Users in the Access Management section of the Admin (editor) area.

As things are now, If I add a Reseller User, then this User can assign Reseller privilages to their own Users. This setup undermines my own Reseller sales and allows Resellers to usurp my own business model.

Mick

**Comment by LikoV2** [comment]
Hi @Intro2,

It will be added in a future update, very soon. As it's not related to Single-App Edition, I will close this issue.
