### ISSUE TITLE
Booking date/time issue

### ISSUE THREAD

**Issue by Intro2** [Xtraball/SiberianCMS#72]
In the Booking feature the date and time field keeps being ignored with an error telling me to fill in the date and time of the booking. Is this a bug? I only tested using .apk

**Comment by alexyves** [comment]
Bug confirmed. Will fix asap

**Comment by Intro2** [comment]
Thanks, I look forward to the fix.

Although this doesn't work when using the app, it does work in the admin editor, but the booking email sent to the app owner has the wrong time of the booking. The email has the booking an hour earlier than it should be. Perhaps this is an issue with Summertime Daylight savings where the clocks go forward an hour in springtime and then go back an hour in the Autumn.

**Comment by Intro2** [comment]
It's been a month since I reported this bug and it still hasn't been fixed yet. Come on guys, show a bit of professionalism and get this sorted out.

**Comment by dbyzero** [comment]
Duplicate #182 , fixed in 4.10.
