### ISSUE TITLE
Bug on layouts layouts 3 & 4 - horizontal

### ISSUE THREAD

**Issue by dominguesr** [Xtraball/SiberianCMS#74]
![img_3724](https://cloud.githubusercontent.com/assets/21616744/18163938/4c5c9fde-7035-11e6-9e65-e706766a6271.png)

After logging in/out, the buttons will appear out of place and it's impossible to navigate to the second screen of buttons.

**Comment by alexyves** [comment]
Fixe with the latests updates.

**Comment by dominguesr** [comment]
I've tested this on version 4.5.3 and this has been corrected but another bug is in place. Please check the movie that I record with this: https://drive.google.com/file/d/0B7O_YC1Is1uGdXM1Q285Z1Fta2c/view?usp=sharing
