### ISSUE TITLE
Fan Wall Module: Calculation Of "Days Ago" Posted Is Incorrect

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#75]
In the Fan Wall module, the calculation of the amount of days ago the post was made is incorrect.  

I made a post today (09/01/16) but the "Days Ago" shows that the post was made 235 Days Ago.  

See attached...

![fan_wall_bug](https://cloud.githubusercontent.com/assets/21089972/18178897/27ba8844-704e-11e6-9be9-857967198455.png)

**Comment by clifton11221** [comment]
This issue is with the News Wall module as well.  Is there an ETA on when this issue will be fixed?  I have a few apps that I need to implement these modules but I can't because of the bug.

**Comment by dbyzero** [comment]
Issue is a bug with Zend Framework 1.12. Sometimes DD/MM/YY is read as MM/DD/YY. I add it to bug tracker.

**Comment by PofMagicfingers** [comment]
Newswall and Fanwall has been changed for post date calculation. This should work correctly after 4.9.0 upcoming update. Thanks for the help !
