### ISSUE TITLE
Ability To Link To In-App Modules From Within The App

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#77]
A great addition would be the ability to create links to other in-app modules from within the app.

For example in a Custom Page you can have the text/link “Click here to contact us”…  That can be a link to a Contact Form.

Other examples would be linking to the “Booking” module, “Discount” modules, etc.

**Comment by dbyzero** [comment]
Already added to bug tracker

**Comment by SiberianCMS** [comment]
Added in 4.8.11-beta.4
