### ISSUE TITLE
Padlock Module: Need Option To Prevent Public Registrations

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#78]
The Padlock module have good features.  However, one feature that's missing and needed is the ability to prevent public registrations.  This way if a company (family, school, etc) would like to have a closed app - one where they can control the users to add to the app - they can have it.

Currently, anybody can click the "Register" option to become a member.

**Comment by SiberianCMS** [comment]
You can try padlock pro module from our partner, which offers multiple group access, and thus prevents user from having to padlock even when registered

http://extensions.siberiancms.com/downloads/padlock-pro-lock-your-feature-based-on-each-userroles/
