### ISSUE TITLE
The shortcomings of translation

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#81]
**Version: 4.5.1 PE**

![85451](https://cloud.githubusercontent.com/assets/8930862/18387817/8c145f68-76a7-11e6-9893-2673126e23b2.png)

![8798465](https://cloud.githubusercontent.com/assets/8930862/18387822/8e8c9684-76a7-11e6-8d35-2ef530d8b74f.png)

![465465](https://cloud.githubusercontent.com/assets/8930862/18387824/90e0c4f0-76a7-11e6-9ae7-9ab058be72d7.png)

![21561](https://cloud.githubusercontent.com/assets/8930862/18387831/98a797a4-76a7-11e6-9c4e-937c09654519.png)

![22](https://cloud.githubusercontent.com/assets/8930862/18387842/a560d00a-76a7-11e6-8d2a-1678e3fc49ae.png)

![screenshot](https://cloud.githubusercontent.com/assets/8930862/18387846/a9a0230a-76a7-11e6-9d8f-5394cfa6a25b.png)

![rfsfsdfsd](https://cloud.githubusercontent.com/assets/8930862/18388016/7b2a77cc-76a8-11e6-9308-8e63ab9a8763.png)

**Comment by SiberianCMS** [comment]
Closing as most of them are translated in 4.7.7 please re-open a new one after 4.7.7 for the remaining.
