### ISSUE TITLE
Layout 3 issues...

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#82]
**Version: 4.5.1 PE**

![561651](https://cloud.githubusercontent.com/assets/8930862/18387869/ca60a9e8-76a7-11e6-8b27-2a2711cf3ee5.png)
![5465496](https://cloud.githubusercontent.com/assets/8930862/18387870/ca82859a-76a7-11e6-8115-95c0a14448c0.png)
![21561](https://cloud.githubusercontent.com/assets/8930862/18387871/ca8f0400-76a7-11e6-998c-1f25708adeed.png)
![45654964](https://cloud.githubusercontent.com/assets/8930862/18387872/ca904e82-76a7-11e6-950a-09eda9cc6d1d.png)
![54654](https://cloud.githubusercontent.com/assets/8930862/18387886/d4b74d16-76a7-11e6-9c8a-b920e9c98270.png)

**Comment by SiberianCMS** [comment]
Fixed in 4.7.7
