### ISSUE TITLE
The first loop input problem

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#83]
v: 4.5.3 P.E.

**valid for only the first entry** 

the other entry opens in the correct application

![1](https://cloud.githubusercontent.com/assets/8930862/18409929/485dc348-775d-11e6-9586-6e802124e20f.png)
![2](https://cloud.githubusercontent.com/assets/8930862/18409930/4a264dda-775d-11e6-806e-f75c05dd799f.png)
![3](https://cloud.githubusercontent.com/assets/8930862/18409931/4daedeb8-775d-11e6-9128-08c695e2a278.png)

**Comment by Alboorii** [comment]
Same issue here.

**Comment by clifton11221** [comment]
This happens to me from time-to-time as well.

**Comment by SiberianCMS** [comment]
Partially patched, checking the current app_id on every request.
