### ISSUE TITLE
Custom Page Module: No Sound With YouTube Video Component

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#84]
In the Custom Page Module, if you select "Video" and use a YouTube video, no sound can be heard. The issue is in version 4.5.3 but I suspect it was there in earlier versions as well.

(Without the sound, 90% of the videos are useless.)

**Comment by clifton11221** [comment]
Please, please, please, fix this issue as soon as possible.  It's a big problem with the apps because no audio can be heard in YouTube videos (throughout the app) or mp4 videos (throughout the app).

... BIG problem :-(

**Comment by clifton11221** [comment]
This is NOT bug.  It was my device with the issue!

**Comment by dbyzero** [comment]
ok :)
