### ISSUE TITLE
facebook picutre

### ISSUE THREAD

**Issue by thehosting4you** [Xtraball/SiberianCMS#87]
hello,
Up since the update to MAE: v4.6.0 works fofo of facebook not on the android.
More people are affected, the reports are made public?
With kind regards,
![facebook-fout](https://cloud.githubusercontent.com/assets/8598623/18743090/c0b288ac-80b7-11e6-9f7c-c21abdc09607.PNG)

**Comment by SiberianCMS** [comment]
Fixed in 4.6.1
