### ISSUE TITLE
WordPress Module: Missing Links To Original Post

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#88]
The WordPress module doesn't have the links back to the original post... This option is needed because the app doesn't show any media from the WordPress post. 

The RSS Module has this feature... See the attached images.

v4.6.1

![siberian_rss](https://cloud.githubusercontent.com/assets/21089972/18803027/ac656b5e-81ba-11e6-8934-f96426dc8d0c.png)

![siberian_wordpress](https://cloud.githubusercontent.com/assets/21089972/18803028/ac670202-81ba-11e6-8f8d-9de5523331d2.png)

**Comment by SiberianCMS** [comment]
This works in 4.7.6.
