### ISSUE TITLE
M-Commerce Issues - Order Confirmation Email, Connected Printer Generated Pdf

### ISSUE THREAD

**Issue by MAWPRO** [Xtraball/SiberianCMS#89]
**Order Confirmation Email**
The email I receive as a customer "Order Confirmation" see attachment below
- adds an extra line with the option and wrong quantity 

**Connected Printer** 
The pdf being generated is missing the notes see attachment
so therefore the final printed document does not have the notes either.

See my attachment also for my order I made.
![mail---order-confirmation-1](https://cloud.githubusercontent.com/assets/6164966/18929035/8abbfa5c-8577-11e6-88fe-b2f97f6796db.png)
![order- 2](https://cloud.githubusercontent.com/assets/6164966/18929036/8d72118c-8577-11e6-88df-543dda79acb6.jpg)
![screenshot_2016-09-28-10-33-09](https://cloud.githubusercontent.com/assets/6164966/18929043/8f8628b4-8577-11e6-8e88-8b835622c1ce.png)

**Comment by SiberianCMS** [comment]
Lot of fixes/improvements in 4.7.10, please re-open a new ticket if needed.
