### ISSUE TITLE
Radio module not working...

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#9]
**Radio module not working**

All URL addresses I tried but it didn't work.

**For examples:** 

http://www.radyolojik.com/connect/mp3lo.m3u
or
http://sunucu1.radyolarburada.com:7473/
or
http://sunucu1.radyolarburada.com:7473
or
http://sunucu4.radyolarburada.com:1054/listen.pls

Didn't work at all. (Normally, the links are working)

**Siberian version: P.E. / 4.1.1**

**Comment by thehosting4you** [comment]
And 64 kbps acc + streams also do not work?

The normal streams at me though :-)

Here is an example URL: http://streams.olympia-radio.nl/olympia64

**Comment by arttex** [comment]
I can not add a response to tech support. Because then I write.
The stream from this address in version 4.1.5 V- stopped working. 
http://nlradio.net/aplayer/player.html
Address to insert the platform: http://nradio.net/nlradio

**Comment by thehosting4you** [comment]
hello,
Is there anything known about the battery and radio module for android 6
Because these bugs is already very long open 21 days?
Sincerely André

**Comment by glopr** [comment]
For shoutcast use http://domain-or-ip.com:port/;

For Icecast use http://domain-or-ip.com:port/stream.mp3

**Comment by glopr** [comment]
Radio issue is with Icecast servers. If I use shoutcast, thw music starts fine. This issue needs to be marked as high priority.

**Comment by karargaht** [comment]
in the browser it's working. in application it doesn't work.

**Comment by SiberianCMS** [comment]
Works.
