### ISSUE TITLE
Can't delete fanwall posts

### ISSUE THREAD

**Issue by Intro2** [Xtraball/SiberianCMS#90]
In the admin editor, Features>>Fanwall>>Manage, there are no posts showing although they do show in-app and on the Overview (emulator). 

Any chance that this issue can be put on the next 'fix' list so that we can edit/delete posts?

Thanks

**Comment by Intro2** [comment]
Please fix (or at least acknowledge) this bug. After recent updates I can now see posts from app admins in the 'Manage' list but posts on the App made by Users still don't show in the list in the editor.

**Comment by dbyzero** [comment]
I add it to bug tracker.

**Comment by dbyzero** [comment]
Fixed
