### ISSUE TITLE
Places Module (Advanced Search Bug): Shows Results From Other Apps

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#91]
In the Place Module, the new advanced search feature pulls in data from other apps. 

I added "wash" as a keyword... When I searched for "wash", the results included a place that I added in a different app (that had "Wash" in the title).

![advanced_search_bug](https://cloud.githubusercontent.com/assets/21089972/19042735/270c0758-895b-11e6-8279-165a48b2391f.png)

See attached.

**Comment by SiberianCMS** [comment]
Fixed in 4.6.4
