### ISSUE TITLE
Bug on layouts layouts 3 & 4 - horizontal

### ISSUE THREAD

**Issue by dominguesr** [Xtraball/SiberianCMS#93]
After logging in/out, the buttons on the second screen disappear. There was an attempt to solve this problem on a previous release 4.5.3 but, in solving [this bug](https://github.com/Xtraball/SiberianCMS/issues/74), a new one was created. Please test a menu with over 7 options so that 2 menu screens are tested.

Please check the movie that I record with this: https://drive.google.com/file/d/0B7O_YC1Is1uGdXM1Q285Z1Fta2c/view?usp=sharing

**Comment by clifton11221** [comment]
The video really explains it... Good bug report!

**Comment by SiberianCMS** [comment]
Seems to be fixed, please re-open otherwise.
