### ISSUE TITLE
M-commerce - Some improvements needed !

### ISSUE THREAD

**Issue by louisaas** [Xtraball/SiberianCMS#94]
Some improvements needed on M-commerce module!

1- Change calculation just when the user set Money payment method.

2- Possibility to set open and close time of each store. Limit the times that each store can receive requests. 

3- When use radius tax, if the the consumer are out of range, the app need tell them. "The store does not deliver in your area." or "You need to activate your smartphone GPS to order"

4- Integration with loyalty card or specific loyalty program for m-commerce module !

**Comment by clifton11221** [comment]
Yes... Agreed!  Very good ideas!  Especially numbers 1 and 3.

**Comment by SiberianCMS** [comment]
Improvements in 4.7.10, more to come.

**Comment by louisaas** [comment]
5- Add the possibility to set "Price" for each item of New Multi Choice PRODUCT'S LIST CHOICE OPTIONS.

**Comment by louisaas** [comment]
6-  Add the possibility to choose not to use categories page, but only view products page.
