### ISSUE TITLE
New Loyalty Program type!

### ISSUE THREAD

**Issue by louisaas** [Xtraball/SiberianCMS#95]
Will be very useful a loyalt program based in points!

*The shooper set many prizes based on consumer points.
10 points = 1 cofee
100 points = 1 bread
1000 points = 1 cake

*Consumer change points into prizes

**Comment by clifton11221** [comment]
I agree... This would be very useful.

**Comment by dbyzero** [comment]
Currently, we coding something similar.

**Comment by Slicit** [comment]
We won't do it as an enhancement, as a partner will be publishing a new loyalty module on the market place which does exactly this :)
